/********************************************************************************
** Form generated from reading UI file 'apertures6.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_APERTURES6_H
#define UI_APERTURES6_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_apertures6
{
public:
    QLabel *label;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QCALabel *label_6;
    QLabel *label_7;
    QPushButton *pushButton_2;
    QCALabel *label_8;
    QCAPushButton *pushButton_3;
    QCALabel *label_9;
    QLineEdit *lineEdit;
    QLabel *label_10;
    QCALabel *label_11;
    QLineEdit *lineEdit_2;
    QCALabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QPushButton *pushButton_4;
    QLabel *label_15;
    QCAPushButton *pushButton_5;
    QCALabel *label_16;
    QCALabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QCALabel *label_20;
    QLabel *label_21;
    QLineEdit *lineEdit_3;
    QCAPushButton *pushButton_6;
    QLabel *label_22;
    QPushButton *pushButton_7;
    QCALabel *label_23;
    QCALabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QCALabel *label_27;
    QLabel *label_28;
    QLineEdit *lineEdit_4;
    QCAPushButton *pushButton_8;
    QLabel *label_29;
    QPushButton *pushButton_9;
    QCALabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QCALCDNumber *lcdNumber;
    QLabel *label_33;
    QCAPushButton *pushButton_10;
    QCAPushButton *pushButton_11;
    QCAPushButton *pushButton_12;
    QCAPushButton *pushButton_13;
    QCAPushButton *pushButton_14;
    QCAPushButton *pushButton_15;
    QLabel *label_34;
    QCAPushButton *pushButton_16;
    QCAPushButton *pushButton_17;
    QCALabel *label_35;
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_19;
    QCALabel *label_36;
    QCAPushButton *pushButton_20;
    QCAPushButton *pushButton_21;
    QCALabel *label_37;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_23;
    QCALabel *label_38;
    QCAPushButton *pushButton_24;
    QCAPushButton *pushButton_25;
    QCALabel *label_39;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_27;
    QCALabel *label_40;
    QCAPushButton *pushButton_28;
    QCAPushButton *pushButton_29;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QCAPushButton *pushButton_30;
    QCALabel *label_45;
    QCAPushButton *pushButton_31;
    QCALabel *label_46;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_33;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QFrame *line;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout;
    QLabel *label_2;
    QPushButton *pushButton;

    void setupUi(QDialog *apertures6)
    {
        if (apertures6->objectName().isEmpty())
            apertures6->setObjectName(QStringLiteral("apertures6"));
        apertures6->resize(703, 764);
        label = new QLabel(apertures6);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(260, 20, 111, 16));
        label_3 = new QLabel(apertures6);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 50, 71, 16));
        label_4 = new QLabel(apertures6);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(100, 50, 59, 14));
        label_5 = new QLabel(apertures6);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 70, 81, 16));
        label_6 = new QCALabel(apertures6);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 250, 59, 14));
        label_7 = new QLabel(apertures6);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(110, 250, 59, 14));
        pushButton_2 = new QPushButton(apertures6);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(20, 220, 51, 22));
        label_8 = new QCALabel(apertures6);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(60, 190, 59, 14));
        label_8->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        pushButton_3 = new QCAPushButton(apertures6);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(100, 220, 51, 22));
        pushButton_3->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_9 = new QCALabel(apertures6);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(60, 100, 59, 14));
        lineEdit = new QLineEdit(apertures6);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(30, 120, 113, 22));
        label_10 = new QLabel(apertures6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(210, 50, 71, 16));
        label_11 = new QCALabel(apertures6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(240, 100, 59, 14));
        lineEdit_2 = new QLineEdit(apertures6);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(210, 120, 113, 22));
        label_12 = new QCALabel(apertures6);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(290, 250, 59, 14));
        label_13 = new QLabel(apertures6);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(210, 250, 59, 14));
        label_14 = new QLabel(apertures6);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(230, 70, 81, 16));
        pushButton_4 = new QPushButton(apertures6);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(200, 220, 51, 22));
        label_15 = new QLabel(apertures6);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(280, 50, 59, 14));
        pushButton_5 = new QCAPushButton(apertures6);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(280, 220, 51, 22));
        pushButton_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_16 = new QCALabel(apertures6);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(240, 190, 59, 14));
        label_16->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        label_17 = new QCALabel(apertures6);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(420, 190, 59, 14));
        label_17->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        label_18 = new QLabel(apertures6);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(390, 50, 71, 16));
        label_19 = new QLabel(apertures6);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(410, 70, 91, 16));
        label_20 = new QCALabel(apertures6);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(390, 250, 59, 14));
        label_21 = new QLabel(apertures6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(460, 50, 59, 14));
        lineEdit_3 = new QLineEdit(apertures6);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(390, 120, 113, 22));
        pushButton_6 = new QCAPushButton(apertures6);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(460, 220, 51, 22));
        pushButton_6->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_22 = new QLabel(apertures6);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(470, 250, 59, 14));
        pushButton_7 = new QPushButton(apertures6);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(380, 220, 51, 22));
        label_23 = new QCALabel(apertures6);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(420, 100, 59, 14));
        label_24 = new QCALabel(apertures6);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(590, 190, 59, 14));
        label_24->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        label_25 = new QLabel(apertures6);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(560, 50, 71, 16));
        label_26 = new QLabel(apertures6);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(570, 70, 91, 16));
        label_27 = new QCALabel(apertures6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(640, 250, 59, 14));
        label_28 = new QLabel(apertures6);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(630, 50, 59, 14));
        lineEdit_4 = new QLineEdit(apertures6);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(560, 120, 113, 22));
        pushButton_8 = new QCAPushButton(apertures6);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(630, 220, 51, 22));
        pushButton_8->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_29 = new QLabel(apertures6);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(560, 250, 59, 14));
        pushButton_9 = new QPushButton(apertures6);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(550, 220, 51, 22));
        label_30 = new QCALabel(apertures6);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(590, 100, 59, 14));
        label_31 = new QLabel(apertures6);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(270, 630, 141, 16));
        label_32 = new QLabel(apertures6);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(40, 650, 81, 16));
        lcdNumber = new QCALCDNumber(apertures6);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(40, 670, 64, 23));
        label_33 = new QLabel(apertures6);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(230, 680, 59, 14));
        pushButton_10 = new QCAPushButton(apertures6);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(230, 650, 31, 22));
        pushButton_11 = new QCAPushButton(apertures6);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(270, 680, 31, 22));
        pushButton_12 = new QCAPushButton(apertures6);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(230, 700, 31, 22));
        pushButton_13 = new QCAPushButton(apertures6);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(190, 680, 31, 22));
        pushButton_14 = new QCAPushButton(apertures6);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(360, 670, 61, 22));
        pushButton_15 = new QCAPushButton(apertures6);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(360, 700, 61, 22));
        label_34 = new QLabel(apertures6);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(480, 650, 71, 16));
        pushButton_16 = new QCAPushButton(apertures6);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(480, 670, 81, 22));
        pushButton_17 = new QCAPushButton(apertures6);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(480, 700, 81, 22));
        pushButton_17->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_35 = new QCALabel(apertures6);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(60, 150, 59, 14));
        pushButton_18 = new QCAPushButton(apertures6);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(20, 150, 31, 22));
        pushButton_19 = new QCAPushButton(apertures6);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(130, 150, 31, 22));
        label_36 = new QCALabel(apertures6);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(240, 150, 59, 14));
        pushButton_20 = new QCAPushButton(apertures6);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(310, 150, 31, 22));
        pushButton_21 = new QCAPushButton(apertures6);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(200, 150, 31, 22));
        label_37 = new QCALabel(apertures6);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(420, 150, 59, 14));
        pushButton_22 = new QCAPushButton(apertures6);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(490, 150, 31, 22));
        pushButton_23 = new QCAPushButton(apertures6);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(380, 150, 31, 22));
        label_38 = new QCALabel(apertures6);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(590, 150, 59, 14));
        pushButton_24 = new QCAPushButton(apertures6);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(660, 150, 31, 22));
        pushButton_25 = new QCAPushButton(apertures6);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(550, 150, 31, 22));
        label_39 = new QCALabel(apertures6);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(410, 430, 59, 14));
        pushButton_26 = new QCAPushButton(apertures6);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(480, 430, 31, 22));
        pushButton_27 = new QCAPushButton(apertures6);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(370, 430, 31, 22));
        label_40 = new QCALabel(apertures6);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(210, 430, 59, 14));
        pushButton_28 = new QCAPushButton(apertures6);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(280, 430, 31, 22));
        pushButton_29 = new QCAPushButton(apertures6);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(170, 430, 31, 22));
        label_41 = new QLabel(apertures6);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(240, 460, 59, 14));
        label_42 = new QLabel(apertures6);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(170, 460, 71, 16));
        label_43 = new QLabel(apertures6);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(440, 460, 59, 14));
        label_44 = new QLabel(apertures6);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(370, 460, 71, 16));
        pushButton_30 = new QCAPushButton(apertures6);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(320, 390, 31, 22));
        label_45 = new QCALabel(apertures6);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(310, 360, 59, 14));
        pushButton_31 = new QCAPushButton(apertures6);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(320, 320, 31, 22));
        label_46 = new QCALabel(apertures6);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(310, 510, 59, 14));
        pushButton_32 = new QCAPushButton(apertures6);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(320, 540, 31, 22));
        pushButton_33 = new QCAPushButton(apertures6);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(320, 470, 31, 22));
        label_47 = new QLabel(apertures6);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(280, 290, 71, 16));
        label_48 = new QLabel(apertures6);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(350, 290, 59, 14));
        label_49 = new QLabel(apertures6);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(280, 570, 71, 16));
        label_50 = new QLabel(apertures6);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(350, 570, 59, 14));
        line = new QFrame(apertures6);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 606, 711, 16));
        line->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 0);"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        layoutWidget = new QWidget(apertures6);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(520, 10, 133, 24));
        horizontalLayout = new QHBoxLayout(layoutWidget);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        label_2 = new QLabel(layoutWidget);
        label_2->setObjectName(QStringLiteral("label_2"));

        horizontalLayout->addWidget(label_2);

        pushButton = new QPushButton(layoutWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));

        horizontalLayout->addWidget(pushButton);


        retranslateUi(apertures6);

        QMetaObject::connectSlotsByName(apertures6);
    } // setupUi

    void retranslateUi(QDialog *apertures6)
    {
        apertures6->setWindowTitle(QApplication::translate("apertures6", "Dialog", 0));
        label->setText(QApplication::translate("apertures6", "Aperture S6 ID", 0));
        label_3->setText(QApplication::translate("apertures6", "BLENDE-O", 0));
        label_4->setText(QApplication::translate("apertures6", "(oben)", 0));
        label_5->setText(QApplication::translate("apertures6", "(AUTOPES6L)", 0));
        label_6->setText(QApplication::translate("apertures6", "IN", 0));
        label_6->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWR", 0)));
        label_7->setText(QApplication::translate("apertures6", "OUT", 0));
        label_7->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWF", 0)));
        pushButton_2->setText(QApplication::translate("apertures6", "More", 0));
        label_8->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_8->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L:stMotor", 0)));
        pushButton_3->setText(QApplication::translate("apertures6", "STOP", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.STOP", 0)));
        label_9->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_9->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.RBV", 0)));
        label_10->setText(QApplication::translate("apertures6", "BLENDE-U", 0));
        label_11->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_11->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.RBV", 0)));
        label_12->setText(QApplication::translate("apertures6", "IN", 0));
        label_12->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWR", 0)));
        label_13->setText(QApplication::translate("apertures6", "OUT", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWF", 0)));
        label_14->setText(QApplication::translate("apertures6", "(AUBOTES6L)", 0));
        pushButton_4->setText(QApplication::translate("apertures6", "More", 0));
        label_15->setText(QApplication::translate("apertures6", "(unten)", 0));
        pushButton_5->setText(QApplication::translate("apertures6", "STOP", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.STOP", 0)));
        label_16->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_16->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L:stMotor", 0)));
        label_17->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_17->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L:stMotor", 0)));
        label_18->setText(QApplication::translate("apertures6", "BLENDE-R", 0));
        label_19->setText(QApplication::translate("apertures6", "(AUWALLES6L)", 0));
        label_20->setText(QApplication::translate("apertures6", "IN", 0));
        label_20->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWR", 0)));
        label_21->setText(QApplication::translate("apertures6", "(Mauer)", 0));
        pushButton_6->setText(QApplication::translate("apertures6", "STOP", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.STOP", 0)));
        label_22->setText(QApplication::translate("apertures6", "OUT", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWF", 0)));
        pushButton_7->setText(QApplication::translate("apertures6", "More", 0));
        label_23->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.RBV", 0)));
        label_24->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L:stMotor", 0)));
        label_25->setText(QApplication::translate("apertures6", "BLENDE-L", 0));
        label_26->setText(QApplication::translate("apertures6", "(AURINGES6L)", 0));
        label_27->setText(QApplication::translate("apertures6", "IN", 0));
        label_27->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWR", 0)));
        label_28->setText(QApplication::translate("apertures6", "(Ring)", 0));
        pushButton_8->setText(QApplication::translate("apertures6", "STOP", 0));
        pushButton_8->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.STOP", 0)));
        label_29->setText(QApplication::translate("apertures6", "OUT", 0));
        label_29->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWF", 0)));
        pushButton_9->setText(QApplication::translate("apertures6", "More", 0));
        label_30->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_30->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.RBV", 0)));
        label_31->setText(QApplication::translate("apertures6", "combined movements", 0));
        label_32->setText(QApplication::translate("apertures6", "Tweak Value", 0));
        lcdNumber->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:setTWVal", 0)));
        label_33->setText(QApplication::translate("apertures6", "Gap", 0));
        pushButton_10->setText(QApplication::translate("apertures6", "^", 0));
        pushButton_10->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdGapUp", 0)));
        pushButton_11->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_11->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdGapLeft", 0)));
        pushButton_12->setText(QApplication::translate("apertures6", "v", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdGapDown", 0)));
        pushButton_13->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdGapRight", 0)));
        pushButton_14->setText(QApplication::translate("apertures6", "open", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdOpenAll", 0)));
        pushButton_15->setText(QApplication::translate("apertures6", "close", 0));
        pushButton_15->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdCloseAll", 0)));
        label_34->setText(QApplication::translate("apertures6", "All motors", 0));
        pushButton_16->setText(QApplication::translate("apertures6", "Reference", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdRefAll", 0)));
        pushButton_17->setText(QApplication::translate("apertures6", "Break", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUCES6L:cmdBreakRefAll", 0)));
        label_35->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_35->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWV", 0)));
        pushButton_18->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWR", 0)));
        pushButton_19->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWF", 0)));
        label_36->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_36->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWV", 0)));
        pushButton_20->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWF", 0)));
        pushButton_21->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWR", 0)));
        label_37->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWV", 0)));
        pushButton_22->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWF", 0)));
        pushButton_23->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWR", 0)));
        label_38->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWV", 0)));
        pushButton_24->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_24->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWF", 0)));
        pushButton_25->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_25->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWR", 0)));
        label_39->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_39->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWV", 0)));
        pushButton_26->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWF", 0)));
        pushButton_27->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUWALLES6L.TWR", 0)));
        label_40->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_40->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWV", 0)));
        pushButton_28->setText(QApplication::translate("apertures6", ">", 0));
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWF", 0)));
        pushButton_29->setText(QApplication::translate("apertures6", "<", 0));
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("apertures6", "AURINGES6L.TWR", 0)));
        label_41->setText(QApplication::translate("apertures6", "(Ring)", 0));
        label_42->setText(QApplication::translate("apertures6", "BLENDE-L", 0));
        label_43->setText(QApplication::translate("apertures6", "(Mauer)", 0));
        label_44->setText(QApplication::translate("apertures6", "BLENDE-R", 0));
        pushButton_30->setText(QApplication::translate("apertures6", "v", 0));
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWR", 0)));
        label_45->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWV", 0)));
        pushButton_31->setText(QApplication::translate("apertures6", "^", 0));
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUTOPES6L.TWF", 0)));
        label_46->setText(QApplication::translate("apertures6", "TextLabel", 0));
        label_46->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWV", 0)));
        pushButton_32->setText(QApplication::translate("apertures6", "v", 0));
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWR", 0)));
        pushButton_33->setText(QApplication::translate("apertures6", "^", 0));
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("apertures6", "AUBOTES6L.TWF", 0)));
        label_47->setText(QApplication::translate("apertures6", "BLENDE-O", 0));
        label_48->setText(QApplication::translate("apertures6", "(oben)", 0));
        label_49->setText(QApplication::translate("apertures6", "BLENDE-U", 0));
        label_50->setText(QApplication::translate("apertures6", "(unten)", 0));
        label_2->setText(QApplication::translate("apertures6", "Archive", 0));
        pushButton->setText(QApplication::translate("apertures6", "Related", 0));
    } // retranslateUi

};

namespace Ui {
    class apertures6: public Ui_apertures6 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_APERTURES6_H
