/********************************************************************************
** Form generated from reading UI file 'aperturedialog.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_APERTUREDIALOG_H
#define UI_APERTUREDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_aperturedialog
{
public:
    QLabel *label_18;
    QLabel *label_43;
    QCALabel *label_46;
    QLabel *label_15;
    QLabel *label_7;
    QCALabel *label_16;
    QCALabel *label_17;
    QCAPushButton *pushButton_31;
    QCALabel *label_8;
    QCAPushButton *pushButton_8;
    QCAPushButton *pushButton_17;
    QLabel *label_28;
    QPushButton *pushButton_4;
    QCAPushButton *pushButton_6;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_10;
    QLabel *label_22;
    QLabel *label_21;
    QCAPushButton *pushButton_13;
    QLabel *label_19;
    QLabel *label_31;
    QPushButton *pushButton_7;
    QLabel *label_33;
    QCAPushButton *pushButton_32;
    QCALabel *label_40;
    QLabel *label_25;
    QCAPushButton *pushButton_3;
    QLabel *label;
    QLabel *label_44;
    QLabel *label_50;
    QCAPushButton *pushButton_12;
    QCAPushButton *pushButton_15;
    QLabel *label_49;
    QCALabel *label_6;
    QCAPushButton *pushButton_14;
    QLabel *label_13;
    QLabel *label_4;
    QCALabel *label_12;
    QLabel *label_14;
    QCALabel *label_20;
    QLabel *label_47;
    QCAPushButton *pushButton_11;
    QLabel *label_34;
    QLabel *label_26;
    QPushButton *pushButton_2;
    QCAPushButton *pushButton_30;
    QLabel *label_42;
    QLabel *label_3;
    QCALabel *label_45;
    QFrame *line;
    QCAPushButton *pushButton_16;
    QLabel *label_5;
    QCAPushButton *pushButton_33;
    QCALabel *label_24;
    QCALCDNumber *lcdNumber;
    QCALabel *label_39;
    QCAPushButton *pushButton_28;
    QLabel *label_10;
    QCAPushButton *pushButton_5;
    QLabel *label_48;
    QLabel *label_29;
    QLabel *label_41;
    QCAPushButton *pushButton_27;
    QLabel *label_32;
    QCAPushButton *pushButton_26;
    QPushButton *pushButton_9;
    QCALabel *label_27;
    QLabel *label_2;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QCAAxis *Axis_1;
    QCAAxis *Axis_2;
    QCAAxis *Axis_3;
    QCAAxis *Axis_4;

    void setupUi(QDialog *aperturedialog)
    {
        if (aperturedialog->objectName().isEmpty())
            aperturedialog->setObjectName(QStringLiteral("aperturedialog"));
        aperturedialog->resize(1164, 770);
        label_18 = new QLabel(aperturedialog);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(380, 50, 71, 16));
        label_43 = new QLabel(aperturedialog);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(430, 460, 59, 14));
        label_46 = new QCALabel(aperturedialog);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(300, 510, 59, 14));
        label_15 = new QLabel(aperturedialog);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(270, 50, 59, 14));
        label_7 = new QLabel(aperturedialog);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(100, 250, 59, 14));
        label_16 = new QCALabel(aperturedialog);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(230, 190, 59, 14));
        label_16->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        label_17 = new QCALabel(aperturedialog);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(410, 190, 59, 14));
        label_17->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        pushButton_31 = new QCAPushButton(aperturedialog);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(310, 320, 31, 22));
        label_8 = new QCALabel(aperturedialog);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(50, 190, 59, 14));
        label_8->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        pushButton_8 = new QCAPushButton(aperturedialog);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(620, 220, 51, 22));
        pushButton_8->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        pushButton_17 = new QCAPushButton(aperturedialog);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(470, 730, 81, 22));
        pushButton_17->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_28 = new QLabel(aperturedialog);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(620, 50, 59, 14));
        pushButton_4 = new QPushButton(aperturedialog);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(190, 220, 51, 22));
        pushButton_6 = new QCAPushButton(aperturedialog);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(450, 220, 51, 22));
        pushButton_6->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        pushButton_29 = new QCAPushButton(aperturedialog);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(160, 430, 31, 22));
        pushButton_10 = new QCAPushButton(aperturedialog);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(220, 680, 31, 22));
        label_22 = new QLabel(aperturedialog);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(460, 250, 59, 14));
        label_21 = new QLabel(aperturedialog);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(450, 50, 59, 14));
        pushButton_13 = new QCAPushButton(aperturedialog);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(180, 710, 31, 22));
        label_19 = new QLabel(aperturedialog);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(400, 70, 91, 16));
        label_31 = new QLabel(aperturedialog);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(260, 630, 141, 16));
        pushButton_7 = new QPushButton(aperturedialog);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(370, 220, 51, 22));
        label_33 = new QLabel(aperturedialog);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(220, 710, 59, 14));
        pushButton_32 = new QCAPushButton(aperturedialog);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(310, 540, 31, 22));
        label_40 = new QCALabel(aperturedialog);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(200, 430, 59, 14));
        label_25 = new QLabel(aperturedialog);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(550, 50, 71, 16));
        pushButton_3 = new QCAPushButton(aperturedialog);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(90, 220, 51, 22));
        pushButton_3->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label = new QLabel(aperturedialog);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(320, 20, 111, 16));
        label_44 = new QLabel(aperturedialog);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(360, 460, 71, 16));
        label_50 = new QLabel(aperturedialog);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(340, 570, 59, 14));
        pushButton_12 = new QCAPushButton(aperturedialog);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(220, 730, 31, 22));
        pushButton_15 = new QCAPushButton(aperturedialog);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(350, 730, 61, 22));
        label_49 = new QLabel(aperturedialog);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(270, 570, 71, 16));
        label_6 = new QCALabel(aperturedialog);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 250, 59, 14));
        pushButton_14 = new QCAPushButton(aperturedialog);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(350, 700, 61, 22));
        label_13 = new QLabel(aperturedialog);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(200, 250, 59, 14));
        label_4 = new QLabel(aperturedialog);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(90, 50, 59, 14));
        label_12 = new QCALabel(aperturedialog);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(280, 250, 59, 14));
        label_14 = new QLabel(aperturedialog);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(220, 70, 81, 16));
        label_20 = new QCALabel(aperturedialog);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(380, 250, 59, 14));
        label_47 = new QLabel(aperturedialog);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(270, 290, 71, 16));
        pushButton_11 = new QCAPushButton(aperturedialog);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(260, 710, 31, 22));
        label_34 = new QLabel(aperturedialog);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(470, 680, 71, 16));
        label_26 = new QLabel(aperturedialog);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(560, 70, 91, 16));
        pushButton_2 = new QPushButton(aperturedialog);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 220, 51, 22));
        pushButton_30 = new QCAPushButton(aperturedialog);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(310, 390, 31, 22));
        label_42 = new QLabel(aperturedialog);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(160, 460, 71, 16));
        label_3 = new QLabel(aperturedialog);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 50, 71, 16));
        label_45 = new QCALabel(aperturedialog);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(300, 360, 59, 14));
        line = new QFrame(aperturedialog);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 606, 1161, 16));
        line->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 0);"));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        pushButton_16 = new QCAPushButton(aperturedialog);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(470, 700, 81, 22));
        label_5 = new QLabel(aperturedialog);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(40, 70, 81, 16));
        pushButton_33 = new QCAPushButton(aperturedialog);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(310, 470, 31, 22));
        label_24 = new QCALabel(aperturedialog);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(580, 190, 59, 14));
        label_24->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber = new QCALCDNumber(aperturedialog);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(30, 700, 64, 23));
        label_39 = new QCALabel(aperturedialog);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(400, 430, 59, 14));
        pushButton_28 = new QCAPushButton(aperturedialog);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(270, 430, 31, 22));
        label_10 = new QLabel(aperturedialog);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(200, 50, 71, 16));
        pushButton_5 = new QCAPushButton(aperturedialog);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(270, 220, 51, 22));
        pushButton_5->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_48 = new QLabel(aperturedialog);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(340, 290, 59, 14));
        label_29 = new QLabel(aperturedialog);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(550, 250, 59, 14));
        label_41 = new QLabel(aperturedialog);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(230, 460, 59, 14));
        pushButton_27 = new QCAPushButton(aperturedialog);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(360, 430, 31, 22));
        label_32 = new QLabel(aperturedialog);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(30, 680, 81, 16));
        pushButton_26 = new QCAPushButton(aperturedialog);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(470, 430, 31, 22));
        pushButton_9 = new QPushButton(aperturedialog);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(540, 220, 51, 22));
        label_27 = new QCALabel(aperturedialog);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(630, 250, 59, 14));
        label_2 = new QLabel(aperturedialog);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(940, 50, 91, 16));
        label_51 = new QLabel(aperturedialog);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(940, 70, 141, 16));
        label_52 = new QLabel(aperturedialog);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(940, 100, 191, 16));
        label_53 = new QLabel(aperturedialog);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(940, 110, 101, 16));
        label_54 = new QLabel(aperturedialog);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(940, 130, 101, 16));
        label_55 = new QLabel(aperturedialog);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(940, 150, 171, 16));
        label_56 = new QLabel(aperturedialog);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(940, 190, 201, 16));
        label_57 = new QLabel(aperturedialog);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(940, 220, 201, 16));
        label_58 = new QLabel(aperturedialog);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(940, 240, 81, 16));
        label_59 = new QLabel(aperturedialog);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(940, 300, 171, 16));
        label_60 = new QLabel(aperturedialog);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(940, 320, 151, 16));
        label_61 = new QLabel(aperturedialog);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(940, 340, 91, 16));
        label_62 = new QLabel(aperturedialog);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(960, 630, 181, 16));
        label_63 = new QLabel(aperturedialog);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(960, 650, 121, 16));
        label_64 = new QLabel(aperturedialog);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(350, 680, 59, 14));
        label_65 = new QLabel(aperturedialog);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(960, 670, 201, 16));
        label_66 = new QLabel(aperturedialog);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(960, 690, 171, 16));
        label_67 = new QLabel(aperturedialog);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(960, 710, 201, 16));
        label_68 = new QLabel(aperturedialog);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(960, 730, 161, 16));
        label_69 = new QLabel(aperturedialog);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(960, 750, 171, 16));
        label_70 = new QLabel(aperturedialog);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(940, 120, 221, 16));
        Axis_1 = new QCAAxis(aperturedialog);
        Axis_1->setObjectName(QStringLiteral("Axis_1"));
        Axis_1->setGeometry(QRect(10, 110, 260, 32));
        Axis_2 = new QCAAxis(aperturedialog);
        Axis_2->setObjectName(QStringLiteral("Axis_2"));
        Axis_2->setGeometry(QRect(650, 440, 449, 32));
        Axis_3 = new QCAAxis(aperturedialog);
        Axis_3->setObjectName(QStringLiteral("Axis_3"));
        Axis_3->setGeometry(QRect(70, 350, 449, 32));
        Axis_4 = new QCAAxis(aperturedialog);
        Axis_4->setObjectName(QStringLiteral("Axis_4"));
        Axis_4->setGeometry(QRect(90, 510, 449, 32));

        retranslateUi(aperturedialog);

        QMetaObject::connectSlotsByName(aperturedialog);
    } // setupUi

    void retranslateUi(QDialog *aperturedialog)
    {
        aperturedialog->setWindowTitle(QApplication::translate("aperturedialog", "Dialog", 0));
        label_18->setText(QApplication::translate("aperturedialog", "BLENDE-R", 0));
        label_43->setText(QApplication::translate("aperturedialog", "(Mauer)", 0));
        label_46->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_46->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWV", 0)));
        label_15->setText(QApplication::translate("aperturedialog", "(unten)", 0));
        label_7->setText(QApplication::translate("aperturedialog", "OUT", 0));
        label_7->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWF", 0)));
        label_16->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_16->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L:stMotor", 0)));
        label_17->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_17->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L:stMotor", 0)));
        pushButton_31->setText(QApplication::translate("aperturedialog", "^", 0));
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWF", 0)));
        label_8->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_8->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L:stMotor", 0)));
        pushButton_8->setText(QApplication::translate("aperturedialog", "STOP", 0));
        pushButton_8->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.STOP", 0)));
        pushButton_17->setText(QApplication::translate("aperturedialog", "Break", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdBreakRefAll", 0)));
        label_28->setText(QApplication::translate("aperturedialog", "(Ring)", 0));
        pushButton_4->setText(QApplication::translate("aperturedialog", "More", 0));
        pushButton_6->setText(QApplication::translate("aperturedialog", "STOP", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.STOP", 0)));
        pushButton_29->setText(QApplication::translate("aperturedialog", "<", 0));
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWR", 0)));
        pushButton_10->setText(QApplication::translate("aperturedialog", "^", 0));
        pushButton_10->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdGapUp", 0)));
        label_22->setText(QApplication::translate("aperturedialog", "OUT", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWF", 0)));
        label_21->setText(QApplication::translate("aperturedialog", "(Mauer)", 0));
        pushButton_13->setText(QApplication::translate("aperturedialog", "<", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdGapRight", 0)));
        label_19->setText(QApplication::translate("aperturedialog", "(AUWALLES6L)", 0));
        label_31->setText(QApplication::translate("aperturedialog", "combined movements", 0));
        pushButton_7->setText(QApplication::translate("aperturedialog", "More", 0));
        label_33->setText(QApplication::translate("aperturedialog", "Gap", 0));
        pushButton_32->setText(QApplication::translate("aperturedialog", "v", 0));
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWR", 0)));
        label_40->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_40->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWV", 0)));
        label_25->setText(QApplication::translate("aperturedialog", "BLENDE-L", 0));
        pushButton_3->setText(QApplication::translate("aperturedialog", "STOP", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.STOP", 0)));
        label->setText(QApplication::translate("aperturedialog", "Aperture S6 ID", 0));
        label_44->setText(QApplication::translate("aperturedialog", "BLENDE-R", 0));
        label_50->setText(QApplication::translate("aperturedialog", "(unten)", 0));
        pushButton_12->setText(QApplication::translate("aperturedialog", "v", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdGapDown", 0)));
        pushButton_15->setText(QApplication::translate("aperturedialog", "close", 0));
        pushButton_15->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdCloseAll", 0)));
        label_49->setText(QApplication::translate("aperturedialog", "BLENDE-U", 0));
        label_6->setText(QApplication::translate("aperturedialog", "IN", 0));
        label_6->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWR", 0)));
        pushButton_14->setText(QApplication::translate("aperturedialog", "open", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdOpenAll", 0)));
        label_13->setText(QApplication::translate("aperturedialog", "OUT", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWF", 0)));
        label_4->setText(QApplication::translate("aperturedialog", "(oben)", 0));
        label_12->setText(QApplication::translate("aperturedialog", "IN", 0));
        label_12->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWR", 0)));
        label_14->setText(QApplication::translate("aperturedialog", "(AUBOTES6L)", 0));
        label_20->setText(QApplication::translate("aperturedialog", "IN", 0));
        label_20->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWR", 0)));
        label_47->setText(QApplication::translate("aperturedialog", "BLENDE-O", 0));
        pushButton_11->setText(QApplication::translate("aperturedialog", ">", 0));
        pushButton_11->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdGapLeft", 0)));
        label_34->setText(QApplication::translate("aperturedialog", "All motors", 0));
        label_26->setText(QApplication::translate("aperturedialog", "(AURINGES6L)", 0));
        pushButton_2->setText(QApplication::translate("aperturedialog", "More", 0));
        pushButton_30->setText(QApplication::translate("aperturedialog", "v", 0));
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWR", 0)));
        label_42->setText(QApplication::translate("aperturedialog", "BLENDE-L", 0));
        label_3->setText(QApplication::translate("aperturedialog", "BLENDE-O", 0));
        label_45->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWV", 0)));
        pushButton_16->setText(QApplication::translate("aperturedialog", "Reference", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:cmdRefAll", 0)));
        label_5->setText(QApplication::translate("aperturedialog", "(AUTOPES6L)", 0));
        pushButton_33->setText(QApplication::translate("aperturedialog", "^", 0));
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWF", 0)));
        label_24->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L:stMotor", 0)));
        lcdNumber->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUCES6L:setTWVal", 0)));
        label_39->setText(QApplication::translate("aperturedialog", "TextLabel", 0));
        label_39->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWV", 0)));
        pushButton_28->setText(QApplication::translate("aperturedialog", ">", 0));
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWF", 0)));
        label_10->setText(QApplication::translate("aperturedialog", "BLENDE-U", 0));
        pushButton_5->setText(QApplication::translate("aperturedialog", "STOP", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.STOP", 0)));
        label_48->setText(QApplication::translate("aperturedialog", "(oben)", 0));
        label_29->setText(QApplication::translate("aperturedialog", "OUT", 0));
        label_29->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWF", 0)));
        label_41->setText(QApplication::translate("aperturedialog", "(Ring)", 0));
        pushButton_27->setText(QApplication::translate("aperturedialog", "<", 0));
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWR", 0)));
        label_32->setText(QApplication::translate("aperturedialog", "Tweak Value", 0));
        pushButton_26->setText(QApplication::translate("aperturedialog", ">", 0));
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWF", 0)));
        pushButton_9->setText(QApplication::translate("aperturedialog", "More", 0));
        label_27->setText(QApplication::translate("aperturedialog", "IN", 0));
        label_27->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWR", 0)));
        label_2->setText(QApplication::translate("aperturedialog", "<- Description", 0));
        label_51->setText(QApplication::translate("aperturedialog", "<- EPICS Device Name", 0));
        label_52->setText(QApplication::translate("aperturedialog", "<-  Readback value, eng. units", 0));
        label_53->setText(QApplication::translate("aperturedialog", "<- In Set mode", 0));
        label_54->setText(QApplication::translate("aperturedialog", "<- Drive value,", 0));
        label_55->setText(QApplication::translate("aperturedialog", "<- Tweak buttons and size", 0));
        label_56->setText(QApplication::translate("aperturedialog", "<- Motor state (done, move, ...)", 0));
        label_57->setText(QApplication::translate("aperturedialog", "<- Related display, stop button", 0));
        label_58->setText(QApplication::translate("aperturedialog", "<- Direction", 0));
        label_59->setText(QApplication::translate("aperturedialog", "<- Tweak aperture motors,", 0));
        label_60->setText(QApplication::translate("aperturedialog", "View: look towards the", 0));
        label_61->setText(QApplication::translate("aperturedialog", "photon beam", 0));
        label_62->setText(QApplication::translate("aperturedialog", "<- Tweak Value: stepsize for", 0));
        label_63->setText(QApplication::translate("aperturedialog", "all move comands", 0));
        label_64->setText(QApplication::translate("aperturedialog", "Gap", 0));
        label_65->setText(QApplication::translate("aperturedialog", "<- Gap: move hor./ vert. motors", 0));
        label_66->setText(QApplication::translate("aperturedialog", "to move the constant gap", 0));
        label_67->setText(QApplication::translate("aperturedialog", "<- open/close: Move all motors", 0));
        label_68->setText(QApplication::translate("aperturedialog", "<- Reference drive for all", 0));
        label_69->setText(QApplication::translate("aperturedialog", "motors / Break reference", 0));
        label_70->setText(QApplication::translate("aperturedialog", "<- Limit switches Soft Limit violation", 0));
        Axis_1->setProperty("description", QVariant(QString()));
        Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.TWV", 0)));
        Axis_1->setProperty("units", QVariant(QApplication::translate("aperturedialog", "\302\265m", 0)));
        Axis_1->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUTOPES6L.RBV", 0)));
        Axis_2->setProperty("description", QVariant(QString()));
        Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.TWV", 0)));
        Axis_2->setProperty("units", QVariant(QApplication::translate("aperturedialog", "\302\265m", 0)));
        Axis_2->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUBOTES6L.RBV", 0)));
        Axis_3->setProperty("description", QVariant(QString()));
        Axis_3->setProperty("pvReadback", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.TWV", 0)));
        Axis_3->setProperty("units", QVariant(QApplication::translate("aperturedialog", "\302\265m", 0)));
        Axis_3->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AUWALLES6L.RBV", 0)));
        Axis_4->setProperty("description", QVariant(QString()));
        Axis_4->setProperty("pvReadback", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.TWV", 0)));
        Axis_4->setProperty("units", QVariant(QApplication::translate("aperturedialog", "\302\265m", 0)));
        Axis_4->setProperty("pv", QVariant(QApplication::translate("aperturedialog", "AURINGES6L.RBV", 0)));
    } // retranslateUi

};

namespace Ui {
    class aperturedialog: public Ui_aperturedialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_APERTUREDIALOG_H
