/********************************************************************************
** Form generated from reading UI file 'inputsignals.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_INPUTSIGNALS_H
#define UI_INPUTSIGNALS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include "qcalabel.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_inputsignals
{
public:
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QCALabel *label_11;
    QCALabel *label_12;
    QCALabel *label_13;
    QCALabel *label_14;
    QCALabel *label_15;
    QCALabel *label_16;
    QCALabel *label_17;
    QCALabel *label_18;
    QCALabel *label_19;
    QCALabel *label_20;
    QCALabel *label_21;
    QCALabel *label_22;
    QCALabel *label_23;
    QCALabel *label_24;
    QCALabel *label_25;
    QCALabel *label_26;
    QCALabel *label_27;
    QCALabel *label_28;
    QCALabel *label_29;
    QCALabel *label_30;
    QCALabel *label_31;
    QCALabel *label_32;
    QCALabel *label_33;
    QCALabel *label_34;
    QLabel *label_35;
    QCALabel *label_36;
    QLabel *label_37;
    QCALabel *label_38;
    QCALabel *label_39;
    QCALabel *label_40;
    QLabel *label_41;
    QCALabel *label_42;
    QCALabel *label_43;
    QCALabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QCALabel *label_48;
    QCALabel *label_49;
    QCALabel *label_50;
    QCALabel *label_51;
    QLabel *label_52;
    QCALabel *label_53;
    QCALabel *label_54;
    QCALabel *label_55;
    QCALabel *label_56;
    QCALabel *label_57;
    QCALabel *label_58;
    QCALabel *label_59;
    QCALabel *label_60;
    QCALabel *label_61;
    QCALabel *label_62;
    QLabel *label_63;
    QCALabel *label_64;
    QCALabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QCALabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QCAPushButton *pushButton;
    QCAPushButton *pushButton_2;
    QCAPushButton *pushButton_3;
    QLabel *label_71;
    QPushButton *pushButton_4;

    void setupUi(QDialog *inputsignals)
    {
        if (inputsignals->objectName().isEmpty())
            inputsignals->setObjectName(QStringLiteral("inputsignals"));
        inputsignals->resize(717, 638);
        label = new QLabel(inputsignals);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(190, 20, 391, 16));
        label_2 = new QLabel(inputsignals);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(140, 50, 59, 14));
        label_3 = new QLabel(inputsignals);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(40, 90, 71, 16));
        label_4 = new QLabel(inputsignals);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(40, 120, 71, 16));
        label_5 = new QLabel(inputsignals);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(220, 50, 71, 16));
        label_6 = new QLabel(inputsignals);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 180, 71, 16));
        label_7 = new QLabel(inputsignals);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(40, 150, 71, 16));
        label_8 = new QLabel(inputsignals);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(390, 50, 71, 16));
        label_9 = new QLabel(inputsignals);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(310, 50, 59, 14));
        label_10 = new QLabel(inputsignals);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(520, 50, 171, 16));
        label_11 = new QCALabel(inputsignals);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(130, 90, 59, 14));
        label_12 = new QCALabel(inputsignals);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(130, 120, 59, 14));
        label_13 = new QCALabel(inputsignals);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(130, 150, 59, 14));
        label_14 = new QCALabel(inputsignals);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(130, 180, 59, 14));
        label_15 = new QCALabel(inputsignals);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(220, 90, 59, 14));
        label_16 = new QCALabel(inputsignals);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(220, 120, 59, 14));
        label_17 = new QCALabel(inputsignals);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(220, 150, 59, 14));
        label_18 = new QCALabel(inputsignals);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(220, 180, 59, 14));
        label_19 = new QCALabel(inputsignals);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(310, 90, 59, 14));
        label_20 = new QCALabel(inputsignals);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(310, 120, 59, 14));
        label_21 = new QCALabel(inputsignals);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(310, 150, 59, 14));
        label_22 = new QCALabel(inputsignals);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(310, 180, 59, 14));
        label_23 = new QCALabel(inputsignals);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(390, 90, 59, 14));
        label_24 = new QCALabel(inputsignals);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(390, 120, 59, 14));
        label_25 = new QCALabel(inputsignals);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(390, 150, 59, 14));
        label_26 = new QCALabel(inputsignals);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(390, 180, 59, 14));
        label_27 = new QCALabel(inputsignals);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(470, 90, 59, 14));
        label_28 = new QCALabel(inputsignals);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(470, 120, 59, 14));
        label_29 = new QCALabel(inputsignals);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(470, 150, 59, 14));
        label_30 = new QCALabel(inputsignals);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(470, 180, 59, 14));
        label_31 = new QCALabel(inputsignals);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(570, 90, 59, 14));
        label_32 = new QCALabel(inputsignals);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(570, 120, 59, 14));
        label_33 = new QCALabel(inputsignals);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(570, 150, 59, 14));
        label_34 = new QCALabel(inputsignals);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(570, 180, 59, 14));
        label_35 = new QLabel(inputsignals);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(190, 240, 391, 16));
        label_36 = new QCALabel(inputsignals);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(220, 370, 59, 14));
        label_37 = new QLabel(inputsignals);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(310, 270, 59, 14));
        label_38 = new QCALabel(inputsignals);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(220, 310, 59, 14));
        label_39 = new QCALabel(inputsignals);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(390, 400, 59, 14));
        label_40 = new QCALabel(inputsignals);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(220, 340, 59, 14));
        label_41 = new QLabel(inputsignals);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(40, 370, 71, 16));
        label_42 = new QCALabel(inputsignals);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(390, 340, 59, 14));
        label_43 = new QCALabel(inputsignals);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(130, 310, 59, 14));
        label_44 = new QCALabel(inputsignals);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(310, 340, 59, 14));
        label_45 = new QLabel(inputsignals);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(40, 340, 71, 16));
        label_46 = new QLabel(inputsignals);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(40, 400, 71, 16));
        label_47 = new QLabel(inputsignals);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(390, 270, 71, 16));
        label_48 = new QCALabel(inputsignals);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(310, 370, 59, 14));
        label_49 = new QCALabel(inputsignals);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(570, 400, 59, 14));
        label_50 = new QCALabel(inputsignals);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(130, 400, 59, 14));
        label_51 = new QCALabel(inputsignals);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(310, 400, 59, 14));
        label_52 = new QLabel(inputsignals);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(220, 270, 71, 16));
        label_53 = new QCALabel(inputsignals);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(310, 310, 59, 14));
        label_54 = new QCALabel(inputsignals);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(390, 370, 59, 14));
        label_55 = new QCALabel(inputsignals);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(130, 370, 59, 14));
        label_56 = new QCALabel(inputsignals);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(570, 370, 59, 14));
        label_57 = new QCALabel(inputsignals);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(220, 400, 59, 14));
        label_58 = new QCALabel(inputsignals);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(570, 310, 59, 14));
        label_59 = new QCALabel(inputsignals);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(390, 310, 59, 14));
        label_60 = new QCALabel(inputsignals);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(570, 340, 59, 14));
        label_61 = new QCALabel(inputsignals);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(470, 340, 59, 14));
        label_62 = new QCALabel(inputsignals);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(470, 400, 59, 14));
        label_63 = new QLabel(inputsignals);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(140, 270, 59, 14));
        label_64 = new QCALabel(inputsignals);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(130, 340, 59, 14));
        label_65 = new QCALabel(inputsignals);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(470, 370, 59, 14));
        label_66 = new QLabel(inputsignals);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(520, 270, 171, 16));
        label_67 = new QLabel(inputsignals);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(40, 310, 71, 16));
        label_68 = new QCALabel(inputsignals);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(470, 310, 59, 14));
        label_69 = new QLabel(inputsignals);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(280, 450, 191, 16));
        label_70 = new QLabel(inputsignals);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(40, 490, 311, 16));
        pushButton = new QCAPushButton(inputsignals);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(430, 490, 81, 22));
        pushButton_2 = new QCAPushButton(inputsignals);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(530, 490, 81, 22));
        pushButton_3 = new QCAPushButton(inputsignals);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(630, 490, 81, 22));
        label_71 = new QLabel(inputsignals);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(40, 540, 131, 16));
        pushButton_4 = new QPushButton(inputsignals);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(190, 540, 81, 22));

        retranslateUi(inputsignals);

        QMetaObject::connectSlotsByName(inputsignals);
    } // setupUi

    void retranslateUi(QDialog *inputsignals)
    {
        inputsignals->setWindowTitle(QApplication::translate("inputsignals", "Dialog", 0));
        label->setText(QApplication::translate("inputsignals", "Input Signals of Feedback Support (Mirror in Encoder Counts)", 0));
        label_2->setText(QApplication::translate("inputsignals", "Position", 0));
        label_3->setText(QApplication::translate("inputsignals", "Channel 1:", 0));
        label_4->setText(QApplication::translate("inputsignals", "Channel 2:", 0));
        label_5->setText(QApplication::translate("inputsignals", "Corrected", 0));
        label_6->setText(QApplication::translate("inputsignals", "Channel 4:", 0));
        label_7->setText(QApplication::translate("inputsignals", "Channel 3:", 0));
        label_8->setText(QApplication::translate("inputsignals", "Analog 2", 0));
        label_9->setText(QApplication::translate("inputsignals", "Analog 1", 0));
        label_10->setText(QApplication::translate("inputsignals", "Range of heydemann DAQ", 0));
        label_11->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_11->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos1", 0)));
        label_12->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_12->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos2", 0)));
        label_13->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos3", 0)));
        label_14->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_14->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos4", 0)));
        label_15->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_15->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos1", 0)));
        label_16->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_16->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos2", 0)));
        label_17->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_17->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos3", 0)));
        label_18->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_18->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos4", 0)));
        label_19->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_19->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_1", 0)));
        label_20->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_20->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_2", 0)));
        label_21->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_21->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_3", 0)));
        label_22->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_4", 0)));
        label_23->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_1", 0)));
        label_24->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_2", 0)));
        label_25->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_3", 0)));
        label_26->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_26->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_4", 0)));
        label_27->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_27->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin1", 0)));
        label_28->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_28->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin2", 0)));
        label_29->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_29->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin3", 0)));
        label_30->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_30->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin4", 0)));
        label_31->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_31->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax1", 0)));
        label_32->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_32->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax2", 0)));
        label_33->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax3", 0)));
        label_34->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_34->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax4", 0)));
        label_35->setText(QApplication::translate("inputsignals", "Input Signals of Feedback Support (Grating in Encoder Counts)", 0));
        label_36->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_36->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos7", 0)));
        label_37->setText(QApplication::translate("inputsignals", "Analog 1", 0));
        label_38->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos5", 0)));
        label_39->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_39->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_8", 0)));
        label_40->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_40->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos6", 0)));
        label_41->setText(QApplication::translate("inputsignals", "Channel 7:", 0));
        label_42->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_42->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_6", 0)));
        label_43->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_43->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos5", 0)));
        label_44->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_44->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_6", 0)));
        label_45->setText(QApplication::translate("inputsignals", "Channel 6:", 0));
        label_46->setText(QApplication::translate("inputsignals", "Channel 8:", 0));
        label_47->setText(QApplication::translate("inputsignals", "Analog 2", 0));
        label_48->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_48->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_7", 0)));
        label_49->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_49->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax8", 0)));
        label_50->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_50->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos8", 0)));
        label_51->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_51->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_8", 0)));
        label_52->setText(QApplication::translate("inputsignals", "Corrected", 0));
        label_53->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_53->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog1_5", 0)));
        label_54->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_54->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_7", 0)));
        label_55->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_55->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos7", 0)));
        label_56->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_56->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax7", 0)));
        label_57->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_57->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKCPos8", 0)));
        label_58->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_58->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax5", 0)));
        label_59->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_59->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKAnalog2_5", 0)));
        label_60->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_60->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax6", 0)));
        label_61->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_61->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin6", 0)));
        label_62->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_62->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin8", 0)));
        label_63->setText(QApplication::translate("inputsignals", "Position", 0));
        label_64->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_64->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKPos6", 0)));
        label_65->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_65->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin7", 0)));
        label_66->setText(QApplication::translate("inputsignals", "Range of heydemann DAQ", 0));
        label_67->setText(QApplication::translate("inputsignals", "Channel 5:", 0));
        label_68->setText(QApplication::translate("inputsignals", "TextLabel", 0));
        label_68->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin5", 0)));
        label_69->setText(QApplication::translate("inputsignals", "Set Heydemann DAQ Range", 0));
        label_70->setText(QApplication::translate("inputsignals", "Set min/max  to current Position of any channel", 0));
        pushButton->setText(QApplication::translate("inputsignals", "a2min", 0));
        pushButton->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmin.PROC", 0)));
        pushButton_2->setText(QApplication::translate("inputsignals", "a2max", 0));
        pushButton_2->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:liIKmax.PROC", 0)));
        pushButton_3->setText(QApplication::translate("inputsignals", "clear", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("inputsignals", "u411pgm1:loFbSetMinMax.PROC", 0)));
        label_71->setText(QApplication::translate("inputsignals", "View Position Date:", 0));
        pushButton_4->setText(QApplication::translate("inputsignals", "wf", 0));
    } // retranslateUi

};

namespace Ui {
    class inputsignals: public Ui_inputsignals {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_INPUTSIGNALS_H
