/********************************************************************************
** Form generated from reading UI file 'smu2_peaxism5.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU2_PEAXISM5_H
#define UI_SMU2_PEAXISM5_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu2_peaxism5
{
public:
    QLabel *label_23;
    QCAPushButton *pushButton_68;
    QCAPushButton *pushButton_59;
    QLabel *label_62;
    QCALabel *label_24;
    QCALabel *label_45;
    QCAPushButton *pushButton_47;
    QLabel *label_46;
    QCALabel *label_47;
    QLabel *label_39;
    QCAPushButton *pushButton_53;
    QCAPushButton *pushButton_5;
    QLabel *label_83;
    QLabel *label_43;
    QLabel *label_82;
    QLabel *label_18;
    QCAPushButton *pushButton_56;
    QCAPushButton *pushButton_73;
    QCAPushButton *pushButton_51;
    QCAPushButton *pushButton_36;
    QCALabel *label_42;
    QLabel *label_84;
    QCAPushButton *pushButton_4;
    QCAPushButton *pushButton_66;
    QCALCDNumber *lcdNumber_14;
    QLabel *label_61;
    QCAPushButton *pushButton_42;
    QCAPushButton *pushButton_49;
    QCAPushButton *pushButton_70;
    QLabel *label_48;
    QLabel *label_70;
    QCAPushButton *pushButton_13;
    QLabel *label_80;
    QCAPushButton *pushButton_38;
    QLabel *label_78;
    QLabel *label_59;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_20;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_35;
    QLabel *label_77;
    QCAPushButton *pushButton_41;
    QLabel *label_66;
    QCAPushButton *pushButton_34;
    QCAPushButton *pushButton_30;
    QLabel *label_19;
    QCAPushButton *pushButton_63;
    QLabel *label_74;
    QCAPushButton *pushButton_71;
    QCAPushButton *pushButton_67;
    QLabel *label_60;
    QCAPushButton *pushButton_48;
    QLabel *label_63;
    QLabel *label_75;
    QLabel *label_69;
    QCALabel *label_41;
    QCAPushButton *pushButton_17;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_65;
    QLabel *label_20;
    QCAPushButton *pushButton_37;
    QLabel *label_65;
    QCAPushButton *pushButton_28;
    QLabel *label_54;
    QLabel *label_73;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_46;
    QScrollBar *horizontalScrollBar_2;
    QCAPushButton *pushButton_62;
    QLabel *label_56;
    QCAPushButton *pushButton_54;
    QCAPushButton *pushButton_6;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_52;
    QCALCDNumber *lcdNumber_15;
    QLabel *label_68;
    QLabel *label_57;
    QCAPushButton *pushButton_19;
    QCAPushButton *pushButton_31;
    QLabel *label_76;
    QCAPushButton *pushButton_45;
    QLabel *label_26;
    QCALabel *label_25;
    QLabel *label_64;
    QCAPushButton *pushButton_27;
    QLabel *label_67;
    QLabel *label_58;
    QCAPushButton *pushButton_60;
    QLabel *label_51;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_32;
    QLabel *label_79;
    QLabel *label_44;
    QCALabel *label_13;
    QCALCDNumber *lcdNumber_13;
    QLabel *label_81;
    QLabel *label_55;
    QCALCDNumber *lcdNumber_11;
    QLabel *label_53;
    QCAPushButton *pushButton_74;
    QCAPushButton *pushButton_64;
    QCAPushButton *pushButton_58;
    QLabel *label_40;
    QCAPushButton *pushButton_23;
    QLabel *label_85;
    QCAPushButton *pushButton_72;
    QLabel *label_86;
    QCAPushButton *pushButton_21;
    QCAPushButton *pushButton_44;
    QLabel *label_71;
    QCALCDNumber *lcdNumber_16;
    QLabel *label_49;
    QCALabel *label_38;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_69;
    QCAPushButton *pushButton_12;
    QCAAxis *max5Axis_2;
    QCAPushButton *pushButton_16;
    QCAAxis *sofn5Axis_2;
    QCAAxis *acc5Axis_2;
    QPushButton *pushButton_14;
    QCAAxis *sofp5Axis_2;
    QCAPushButton *pushButton_40;
    QCAAxis *ref5Axis_2;
    QCALabel *label_37;
    QLabel *label_32;
    QLabel *label_36;
    QCAAxis *curr5Axis_2;
    QCAAxis *speed5Axis_2;
    QCALabel *label_33;
    QCAAxis *Axis5;

    void setupUi(QDialog *smu2_peaxism5)
    {
        if (smu2_peaxism5->objectName().isEmpty())
            smu2_peaxism5->setObjectName(QStringLiteral("smu2_peaxism5"));
        smu2_peaxism5->resize(1167, 694);
        label_23 = new QLabel(smu2_peaxism5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(1000, 20, 59, 14));
        pushButton_68 = new QCAPushButton(smu2_peaxism5);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(530, 470, 31, 21));
        pushButton_59 = new QCAPushButton(smu2_peaxism5);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(480, 490, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_62 = new QLabel(smu2_peaxism5);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(410, 490, 59, 14));
        label_24 = new QCALabel(smu2_peaxism5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(1030, 130, 81, 16));
        label_45 = new QCALabel(smu2_peaxism5);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(40, 40, 59, 14));
        pushButton_47 = new QCAPushButton(smu2_peaxism5);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(560, 550, 31, 21));
        label_46 = new QLabel(smu2_peaxism5);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(40, 30, 59, 14));
        label_47 = new QCALabel(smu2_peaxism5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(210, 300, 101, 16));
        label_39 = new QLabel(smu2_peaxism5);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(890, 70, 111, 16));
        pushButton_53 = new QCAPushButton(smu2_peaxism5);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(560, 610, 31, 21));
        pushButton_5 = new QCAPushButton(smu2_peaxism5);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(140, 120, 81, 22));
        label_83 = new QLabel(smu2_peaxism5);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(450, 210, 81, 16));
        label_83->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_43 = new QLabel(smu2_peaxism5);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(890, 110, 91, 16));
        label_82 = new QLabel(smu2_peaxism5);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(610, 410, 71, 16));
        label_18 = new QLabel(smu2_peaxism5);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(820, 60, 59, 14));
        label_18->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_56 = new QCAPushButton(smu2_peaxism5);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(560, 310, 31, 21));
        pushButton_73 = new QCAPushButton(smu2_peaxism5);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(480, 330, 31, 21));
        pushButton_73->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_51 = new QCAPushButton(smu2_peaxism5);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(560, 590, 31, 21));
        pushButton_36 = new QCAPushButton(smu2_peaxism5);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(530, 450, 31, 21));
        label_42 = new QCALabel(smu2_peaxism5);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1030, 150, 91, 16));
        label_84 = new QLabel(smu2_peaxism5);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(610, 590, 71, 16));
        pushButton_4 = new QCAPushButton(smu2_peaxism5);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(40, 91, 81, 51));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_66 = new QCAPushButton(smu2_peaxism5);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(560, 530, 31, 21));
        lcdNumber_14 = new QCALCDNumber(smu2_peaxism5);
        lcdNumber_14->setObjectName(QStringLiteral("lcdNumber_14"));
        lcdNumber_14->setGeometry(QRect(450, 280, 64, 23));
        lcdNumber_14->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_14->setMode(QLCDNumber::Hex);
        lcdNumber_14->setSegmentStyle(QLCDNumber::Filled);
        label_61 = new QLabel(smu2_peaxism5);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(410, 470, 59, 14));
        pushButton_42 = new QCAPushButton(smu2_peaxism5);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(530, 510, 31, 21));
        pushButton_49 = new QCAPushButton(smu2_peaxism5);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(560, 570, 31, 21));
        pushButton_70 = new QCAPushButton(smu2_peaxism5);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(530, 330, 31, 21));
        label_48 = new QLabel(smu2_peaxism5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(50, 340, 111, 16));
        label_70 = new QLabel(smu2_peaxism5);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(610, 490, 71, 16));
        pushButton_13 = new QCAPushButton(smu2_peaxism5);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(230, 120, 81, 22));
        label_80 = new QLabel(smu2_peaxism5);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(610, 370, 71, 16));
        pushButton_38 = new QCAPushButton(smu2_peaxism5);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(560, 350, 31, 21));
        label_78 = new QLabel(smu2_peaxism5);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(410, 350, 59, 14));
        label_59 = new QLabel(smu2_peaxism5);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(610, 330, 71, 16));
        pushButton_43 = new QCAPushButton(smu2_peaxism5);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(560, 510, 31, 21));
        pushButton_20 = new QCAPushButton(smu2_peaxism5);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(260, 460, 31, 31));
        pushButton_55 = new QCAPushButton(smu2_peaxism5);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(480, 410, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_18 = new QCAPushButton(smu2_peaxism5);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(530, 120, 81, 22));
        pushButton_35 = new QCAPushButton(smu2_peaxism5);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(480, 350, 31, 21));
        pushButton_35->setStyleSheet(QStringLiteral(""));
        label_77 = new QLabel(smu2_peaxism5);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(610, 610, 71, 16));
        pushButton_41 = new QCAPushButton(smu2_peaxism5);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(560, 490, 31, 21));
        label_66 = new QLabel(smu2_peaxism5);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(610, 510, 71, 16));
        pushButton_34 = new QCAPushButton(smu2_peaxism5);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(530, 430, 31, 21));
        pushButton_30 = new QCAPushButton(smu2_peaxism5);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(480, 370, 31, 21));
        pushButton_30->setStyleSheet(QStringLiteral(""));
        label_19 = new QLabel(smu2_peaxism5);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(890, 90, 111, 16));
        pushButton_63 = new QCAPushButton(smu2_peaxism5);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(480, 570, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_74 = new QLabel(smu2_peaxism5);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(410, 430, 59, 14));
        pushButton_71 = new QCAPushButton(smu2_peaxism5);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(560, 330, 31, 21));
        pushButton_67 = new QCAPushButton(smu2_peaxism5);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(530, 570, 31, 21));
        label_60 = new QLabel(smu2_peaxism5);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(410, 450, 59, 14));
        pushButton_48 = new QCAPushButton(smu2_peaxism5);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(530, 410, 31, 21));
        label_63 = new QLabel(smu2_peaxism5);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(610, 350, 71, 16));
        label_75 = new QLabel(smu2_peaxism5);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(610, 550, 71, 16));
        label_69 = new QLabel(smu2_peaxism5);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(610, 530, 71, 16));
        label_41 = new QCALabel(smu2_peaxism5);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(1030, 70, 91, 16));
        pushButton_17 = new QCAPushButton(smu2_peaxism5);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(430, 120, 81, 22));
        pushButton_33 = new QCAPushButton(smu2_peaxism5);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(560, 410, 31, 21));
        pushButton_61 = new QCAPushButton(smu2_peaxism5);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(480, 530, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_65 = new QCAPushButton(smu2_peaxism5);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(480, 610, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        label_20 = new QLabel(smu2_peaxism5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(890, 130, 91, 16));
        pushButton_37 = new QCAPushButton(smu2_peaxism5);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(560, 450, 31, 21));
        label_65 = new QLabel(smu2_peaxism5);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(410, 550, 59, 14));
        pushButton_28 = new QCAPushButton(smu2_peaxism5);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(480, 310, 31, 21));
        label_54 = new QLabel(smu2_peaxism5);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(50, 300, 111, 16));
        label_73 = new QLabel(smu2_peaxism5);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(410, 310, 59, 14));
        pushButton_26 = new QCAPushButton(smu2_peaxism5);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(530, 350, 31, 21));
        pushButton_50 = new QCAPushButton(smu2_peaxism5);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(530, 590, 31, 21));
        pushButton_46 = new QCAPushButton(smu2_peaxism5);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(530, 550, 31, 21));
        horizontalScrollBar_2 = new QScrollBar(smu2_peaxism5);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(100, 470, 151, 16));
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        pushButton_62 = new QCAPushButton(smu2_peaxism5);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(480, 550, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_56 = new QLabel(smu2_peaxism5);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(610, 430, 71, 16));
        pushButton_54 = new QCAPushButton(smu2_peaxism5);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(480, 390, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        pushButton_6 = new QCAPushButton(smu2_peaxism5);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(330, 120, 81, 22));
        pushButton_39 = new QCAPushButton(smu2_peaxism5);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(560, 470, 31, 21));
        pushButton_29 = new QCAPushButton(smu2_peaxism5);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(560, 370, 31, 21));
        pushButton_52 = new QCAPushButton(smu2_peaxism5);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(530, 610, 31, 21));
        lcdNumber_15 = new QCALCDNumber(smu2_peaxism5);
        lcdNumber_15->setObjectName(QStringLiteral("lcdNumber_15"));
        lcdNumber_15->setGeometry(QRect(530, 250, 64, 23));
        lcdNumber_15->setMode(QLCDNumber::Hex);
        label_68 = new QLabel(smu2_peaxism5);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(410, 610, 59, 14));
        label_57 = new QLabel(smu2_peaxism5);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(410, 390, 59, 14));
        pushButton_19 = new QCAPushButton(smu2_peaxism5);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(60, 460, 31, 31));
        pushButton_31 = new QCAPushButton(smu2_peaxism5);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(560, 390, 31, 21));
        label_76 = new QLabel(smu2_peaxism5);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(410, 570, 59, 14));
        pushButton_45 = new QCAPushButton(smu2_peaxism5);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(530, 370, 31, 21));
        label_26 = new QLabel(smu2_peaxism5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(790, 210, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_25 = new QCALabel(smu2_peaxism5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(1030, 110, 91, 16));
        label_64 = new QLabel(smu2_peaxism5);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(410, 530, 59, 14));
        pushButton_27 = new QCAPushButton(smu2_peaxism5);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(530, 310, 31, 21));
        label_67 = new QLabel(smu2_peaxism5);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(410, 590, 59, 14));
        label_58 = new QLabel(smu2_peaxism5);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(410, 370, 59, 14));
        pushButton_60 = new QCAPushButton(smu2_peaxism5);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(480, 510, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        label_51 = new QLabel(smu2_peaxism5);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(50, 220, 121, 16));
        label_51->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_22 = new QCAPushButton(smu2_peaxism5);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(270, 340, 61, 22));
        pushButton_32 = new QCAPushButton(smu2_peaxism5);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(530, 390, 31, 21));
        label_79 = new QLabel(smu2_peaxism5);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(610, 570, 71, 16));
        label_44 = new QLabel(smu2_peaxism5);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(330, 20, 71, 16));
        label_13 = new QCALabel(smu2_peaxism5);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(540, 80, 59, 14));
        lcdNumber_13 = new QCALCDNumber(smu2_peaxism5);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(150, 440, 64, 23));
        label_81 = new QLabel(smu2_peaxism5);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(610, 470, 71, 16));
        label_55 = new QLabel(smu2_peaxism5);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(610, 390, 71, 16));
        lcdNumber_11 = new QCALCDNumber(smu2_peaxism5);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(340, 80, 64, 23));
        label_53 = new QLabel(smu2_peaxism5);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(50, 370, 121, 16));
        pushButton_74 = new QCAPushButton(smu2_peaxism5);
        pushButton_74->setObjectName(QStringLiteral("pushButton_74"));
        pushButton_74->setGeometry(QRect(530, 490, 31, 21));
        pushButton_64 = new QCAPushButton(smu2_peaxism5);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(480, 590, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        pushButton_58 = new QCAPushButton(smu2_peaxism5);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(480, 470, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_40 = new QLabel(smu2_peaxism5);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(890, 150, 101, 16));
        pushButton_23 = new QCAPushButton(smu2_peaxism5);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(180, 340, 61, 22));
        label_85 = new QLabel(smu2_peaxism5);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(610, 450, 71, 16));
        pushButton_72 = new QCAPushButton(smu2_peaxism5);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(480, 430, 31, 21));
        pushButton_72->setStyleSheet(QStringLiteral(""));
        label_86 = new QLabel(smu2_peaxism5);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(410, 410, 59, 14));
        pushButton_21 = new QCAPushButton(smu2_peaxism5);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(180, 370, 151, 22));
        pushButton_44 = new QCAPushButton(smu2_peaxism5);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(530, 530, 31, 21));
        label_71 = new QLabel(smu2_peaxism5);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(610, 310, 71, 16));
        lcdNumber_16 = new QCALCDNumber(smu2_peaxism5);
        lcdNumber_16->setObjectName(QStringLiteral("lcdNumber_16"));
        lcdNumber_16->setGeometry(QRect(530, 280, 64, 23));
        lcdNumber_16->setStyleSheet(QStringLiteral(""));
        lcdNumber_16->setMode(QLCDNumber::Hex);
        label_49 = new QLabel(smu2_peaxism5);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(130, 420, 111, 16));
        label_38 = new QCALabel(smu2_peaxism5);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(1030, 90, 91, 16));
        pushButton_57 = new QCAPushButton(smu2_peaxism5);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(560, 430, 31, 21));
        pushButton_69 = new QCAPushButton(smu2_peaxism5);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(480, 450, 31, 21));
        pushButton_69->setStyleSheet(QStringLiteral(""));
        pushButton_12 = new QCAPushButton(smu2_peaxism5);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(940, 400, 51, 22));
        max5Axis_2 = new QCAAxis(smu2_peaxism5);
        max5Axis_2->setObjectName(QStringLiteral("max5Axis_2"));
        max5Axis_2->setGeometry(QRect(730, 340, 345, 27));
        max5Axis_2->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu2_peaxism5);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(940, 490, 51, 22));
        sofn5Axis_2 = new QCAAxis(smu2_peaxism5);
        sofn5Axis_2->setObjectName(QStringLiteral("sofn5Axis_2"));
        sofn5Axis_2->setGeometry(QRect(730, 430, 345, 27));
        sofn5Axis_2->setMinimumSize(QSize(100, 10));
        acc5Axis_2 = new QCAAxis(smu2_peaxism5);
        acc5Axis_2->setObjectName(QStringLiteral("acc5Axis_2"));
        acc5Axis_2->setGeometry(QRect(730, 370, 345, 27));
        acc5Axis_2->setMinimumSize(QSize(100, 10));
        pushButton_14 = new QPushButton(smu2_peaxism5);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(1000, 400, 51, 22));
        sofp5Axis_2 = new QCAAxis(smu2_peaxism5);
        sofp5Axis_2->setObjectName(QStringLiteral("sofp5Axis_2"));
        sofp5Axis_2->setGeometry(QRect(730, 460, 345, 27));
        sofp5Axis_2->setMinimumSize(QSize(100, 10));
        pushButton_40 = new QCAPushButton(smu2_peaxism5);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(1000, 490, 51, 22));
        ref5Axis_2 = new QCAAxis(smu2_peaxism5);
        ref5Axis_2->setObjectName(QStringLiteral("ref5Axis_2"));
        ref5Axis_2->setGeometry(QRect(730, 280, 345, 27));
        ref5Axis_2->setMinimumSize(QSize(100, 10));
        label_37 = new QCALabel(smu2_peaxism5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(850, 490, 59, 14));
        label_32 = new QLabel(smu2_peaxism5);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(730, 410, 111, 16));
        label_36 = new QLabel(smu2_peaxism5);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(730, 490, 111, 16));
        curr5Axis_2 = new QCAAxis(smu2_peaxism5);
        curr5Axis_2->setObjectName(QStringLiteral("curr5Axis_2"));
        curr5Axis_2->setGeometry(QRect(730, 250, 345, 27));
        curr5Axis_2->setMinimumSize(QSize(100, 10));
        speed5Axis_2 = new QCAAxis(smu2_peaxism5);
        speed5Axis_2->setObjectName(QStringLiteral("speed5Axis_2"));
        speed5Axis_2->setGeometry(QRect(730, 310, 345, 27));
        speed5Axis_2->setMinimumSize(QSize(100, 10));
        label_33 = new QCALabel(smu2_peaxism5);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(850, 410, 59, 14));
        Axis5 = new QCAAxis(smu2_peaxism5);
        Axis5->setObjectName(QStringLiteral("Axis5"));
        Axis5->setGeometry(QRect(50, 240, 360, 32));

        retranslateUi(smu2_peaxism5);

        QMetaObject::connectSlotsByName(smu2_peaxism5);
    } // setupUi

    void retranslateUi(QDialog *smu2_peaxism5)
    {
        smu2_peaxism5->setWindowTitle(QApplication::translate("smu2_peaxism5", "Dialog", 0));
        label_23->setText(QApplication::translate("smu2_peaxism5", "M5", 0));
        pushButton_68->setText(QString());
        pushButton_68->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_62->setText(QApplication::translate("smu2_peaxism5", "DV_OK", 0));
        label_24->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdCaptValM5", 0)));
        label_45->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:ChkAliveM5_.DESC", 0)));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_46->setText(QApplication::translate("smu2_peaxism5", "DESC", 0));
        label_47->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:AbsM5", 0)));
        label_39->setText(QApplication::translate("smu2_peaxism5", "current position", 0));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_5->setText(QApplication::translate("smu2_peaxism5", "LSN", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:LsnM5", 0)));
        label_83->setText(QApplication::translate("smu2_peaxism5", "error codes", 0));
        label_43->setText(QApplication::translate("smu2_peaxism5", "current speed", 0));
        label_82->setText(QApplication::translate("smu2_peaxism5", "EXT ERR", 0));
        label_18->setText(QApplication::translate("smu2_peaxism5", "info set", 0));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_73->setText(QString());
        pushButton_73->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_42->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_42->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdBrakeDistM5", 0)));
        label_84->setText(QApplication::translate("smu2_peaxism5", "LSP", 0));
        pushButton_4->setText(QApplication::translate("smu2_peaxism5", "STOP", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:StopM5", 0)));
        pushButton_66->setText(QString());
        pushButton_66->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        lcdNumber_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_61->setText(QApplication::translate("smu2_peaxism5", "70X I", 0));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_70->setText(QString());
        pushButton_70->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_48->setText(QApplication::translate("smu2_peaxism5", "move continous", 0));
        label_70->setText(QApplication::translate("smu2_peaxism5", "Powerfail", 0));
        pushButton_13->setText(QApplication::translate("smu2_peaxism5", "REF", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:HomeM5", 0)));
        label_80->setText(QApplication::translate("smu2_peaxism5", "Track Err", 0));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_78->setText(QApplication::translate("smu2_peaxism5", "DIR", 0));
        label_59->setText(QApplication::translate("smu2_peaxism5", "POSA", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_20->setText(QApplication::translate("smu2_peaxism5", "+", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:ContPosM5", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_18->setText(QApplication::translate("smu2_peaxism5", "LSP", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:LspM5", 0)));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_77->setText(QApplication::translate("smu2_peaxism5", "LSN", 0));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_66->setText(QApplication::translate("smu2_peaxism5", "Encoder", 0));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_19->setText(QApplication::translate("smu2_peaxism5", "nominal position", 0));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_74->setText(QString());
        pushButton_71->setText(QString());
        pushButton_71->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_67->setText(QString());
        pushButton_67->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_60->setText(QApplication::translate("smu2_peaxism5", "SP", 0));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_63->setText(QApplication::translate("smu2_peaxism5", "Ref Err", 0));
        label_75->setText(QApplication::translate("smu2_peaxism5", "HW Speed", 0));
        label_69->setText(QString());
        label_41->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_41->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdPosM5", 0)));
        pushButton_17->setText(QApplication::translate("smu2_peaxism5", "Lock", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:LockM5", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_20->setText(QApplication::translate("smu2_peaxism5", "capture value", 0));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_65->setText(QApplication::translate("smu2_peaxism5", "LSP", 0));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_54->setText(QApplication::translate("smu2_peaxism5", "move absolute to", 0));
        label_73->setText(QApplication::translate("smu2_peaxism5", "ERROR", 0));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_56->setText(QApplication::translate("smu2_peaxism5", "SW LSP", 0));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_6->setText(QApplication::translate("smu2_peaxism5", "RUN", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:RunM5", 0)));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        lcdNumber_15->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_68->setText(QApplication::translate("smu2_peaxism5", "LOCK", 0));
        label_57->setText(QApplication::translate("smu2_peaxism5", "ABS", 0));
        pushButton_19->setText(QApplication::translate("smu2_peaxism5", "-", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:ContNegM5", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_76->setText(QApplication::translate("smu2_peaxism5", "REF", 0));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_26->setText(QApplication::translate("smu2_peaxism5", "parameter set", 0));
        label_25->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdCurSpeedM5", 0)));
        label_64->setText(QApplication::translate("smu2_peaxism5", "LSN", 0));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_67->setText(QApplication::translate("smu2_peaxism5", "CAPT", 0));
        label_58->setText(QApplication::translate("smu2_peaxism5", "RUN", 0));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_51->setText(QApplication::translate("smu2_peaxism5", "motion commands", 0));
        pushButton_22->setText(QApplication::translate("smu2_peaxism5", "+", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:ContPosM5", 0)));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_79->setText(QApplication::translate("smu2_peaxism5", "DV_ERR", 0));
        label_44->setText(QApplication::translate("smu2_peaxism5", "SMU41_2", 0));
        label_13->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdPosM5.EGU", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSpeedM5", 0)));
        label_81->setText(QString());
        label_55->setText(QApplication::translate("smu2_peaxism5", "SW Speed", 0));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdPosM5", 0)));
        label_53->setText(QApplication::translate("smu2_peaxism5", "move to reference", 0));
        pushButton_74->setText(QString());
        pushButton_74->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_40->setText(QApplication::translate("smu2_peaxism5", "brake distance", 0));
        pushButton_23->setText(QApplication::translate("smu2_peaxism5", "-", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:ContNegM5", 0)));
        label_85->setText(QApplication::translate("smu2_peaxism5", "SW LSN", 0));
        pushButton_72->setText(QString());
        pushButton_72->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        label_86->setText(QApplication::translate("smu2_peaxism5", "OSPD", 0));
        pushButton_21->setText(QApplication::translate("smu2_peaxism5", "GoRef", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:RefM4", 0)));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrStateM5", 0)));
        label_71->setText(QApplication::translate("smu2_peaxism5", "User Stop", 0));
        lcdNumber_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        label_49->setText(QApplication::translate("smu2_peaxism5", "continous mode", 0));
        label_38->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdNomPosM5", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdErrFlagM5", 0)));
        pushButton_69->setText(QString());
        pushButton_69->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdStateM5", 0)));
        pushButton_12->setText(QApplication::translate("smu2_peaxism5", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:AccM5", 0)));
        max5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "maximal speed", 0)));
        max5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdMaxSpeedM5", 0)));
        max5Axis_2->setProperty("units", QVariant(QString()));
        max5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdMaxSpeedM5", 0)));
        pushButton_16->setText(QApplication::translate("smu2_peaxism5", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:SwLimM5", 0)));
        sofn5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "soft limit negativ", 0)));
        sofn5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSwLimNegM5", 0)));
        sofn5Axis_2->setProperty("units", QVariant(QString()));
        sofn5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSwLimNegM5", 0)));
        acc5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "acceleration time", 0)));
        acc5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdAccTimeM5", 0)));
        acc5Axis_2->setProperty("units", QVariant(QString()));
        acc5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdAccTimeM5", 0)));
        pushButton_14->setText(QApplication::translate("smu2_peaxism5", "exp", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:AccM5", 0)));
        sofp5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "soft limit positiv", 0)));
        sofp5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSwLimPosM5", 0)));
        sofp5Axis_2->setProperty("units", QVariant(QString()));
        sofp5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSwLimPosM5", 0)));
        pushButton_40->setText(QApplication::translate("smu2_peaxism5", "on", 0));
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:SwLimM5", 0)));
        ref5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "reference positic", 0)));
        ref5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdRefM5", 0)));
        ref5Axis_2->setProperty("units", QVariant(QString()));
        ref5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdRefM5", 0)));
        label_37->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSwLimM5", 0)));
        label_32->setText(QApplication::translate("smu2_peaxism5", "ramp shape", 0));
        label_36->setText(QApplication::translate("smu2_peaxism5", "soft limit", 0));
        curr5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "current position", 0)));
        curr5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdPosM5", 0)));
        curr5Axis_2->setProperty("units", QVariant(QApplication::translate("smu2_peaxism5", "steps", 0)));
        curr5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdPosM5", 0)));
        speed5Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "speed", 0)));
        speed5Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSpeedM5", 0)));
        speed5Axis_2->setProperty("units", QVariant(QString()));
        speed5Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdSpeedM5", 0)));
        label_33->setText(QApplication::translate("smu2_peaxism5", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdAccM5", 0)));
        Axis5->setProperty("description", QVariant(QApplication::translate("smu2_peaxism5", "motive relative", 0)));
        Axis5->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdRelM5", 0)));
        Axis5->setProperty("units", QVariant(QApplication::translate("smu2_peaxism5", "steps", 0)));
        Axis5->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism5", "SMU41_2:rdRelM5", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu2_peaxism5: public Ui_smu2_peaxism5 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU2_PEAXISM5_H
