/********************************************************************************
** Form generated from reading UI file 'smu2_peaxism2.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU2_PEAXISM2_H
#define UI_SMU2_PEAXISM2_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu2_peaxism2
{
public:
    QLabel *label_44;
    QCAPushButton *pushButton_17;
    QCAPushButton *pushButton_4;
    QCAPushButton *pushButton_6;
    QCALabel *label_13;
    QCALabel *label_45;
    QCAPushButton *pushButton_5;
    QCALCDNumber *lcdNumber_11;
    QCAPushButton *pushButton_13;
    QLabel *label_46;
    QCAPushButton *pushButton_18;
    QLabel *label_15;
    QLabel *label_17;
    QLabel *label_14;
    QCALabel *label_24;
    QCALabel *label_23;
    QLabel *label_16;
    QCALabel *label_21;
    QCALabel *label_25;
    QLabel *label_20;
    QLabel *label_19;
    QCALabel *label_22;
    QLabel *label_18;
    QLabel *label_26;
    QLabel *label_62;
    QCAPushButton *pushButton_28;
    QCAPushButton *pushButton_73;
    QCAPushButton *pushButton_72;
    QCAPushButton *pushButton_67;
    QLabel *label_60;
    QCAPushButton *pushButton_34;
    QCAPushButton *pushButton_42;
    QCAPushButton *pushButton_59;
    QCAPushButton *pushButton_50;
    QLabel *label_83;
    QLabel *label_66;
    QCAPushButton *pushButton_65;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_36;
    QCAPushButton *pushButton_71;
    QLabel *label_80;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_51;
    QCAPushButton *pushButton_54;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_38;
    QCALCDNumber *lcdNumber_15;
    QCAPushButton *pushButton_53;
    QCAPushButton *pushButton_58;
    QCAPushButton *pushButton_56;
    QCALCDNumber *lcdNumber_14;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_31;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_63;
    QCAPushButton *pushButton_27;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_52;
    QLabel *label_68;
    QCAPushButton *pushButton_48;
    QLabel *label_79;
    QCAPushButton *pushButton_46;
    QLabel *label_82;
    QLabel *label_77;
    QLabel *label_63;
    QLabel *label_57;
    QLabel *label_70;
    QLabel *label_74;
    QCAPushButton *pushButton_30;
    QLabel *label_61;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_35;
    QCAPushButton *pushButton_29;
    QLabel *label_67;
    QCAPushButton *pushButton_60;
    QLabel *label_64;
    QLabel *label_85;
    QCAPushButton *pushButton_69;
    QLabel *label_56;
    QLabel *label_73;
    QLabel *label_78;
    QLabel *label_58;
    QLabel *label_55;
    QCAPushButton *pushButton_41;
    QLabel *label_81;
    QCAPushButton *pushButton_45;
    QLabel *label_86;
    QCAPushButton *pushButton_68;
    QCAPushButton *pushButton_37;
    QCAPushButton *pushButton_66;
    QCAPushButton *pushButton_62;
    QLabel *label_84;
    QCAPushButton *pushButton_70;
    QLabel *label_75;
    QLabel *label_59;
    QCAPushButton *pushButton_44;
    QLabel *label_71;
    QCAPushButton *pushButton_49;
    QLabel *label_76;
    QLabel *label_65;
    QCAPushButton *pushButton_47;
    QCAPushButton *pushButton_64;
    QCAPushButton *pushButton_74;
    QCALCDNumber *lcdNumber_16;
    QLabel *label_69;
    QCAPushButton *pushButton_23;
    QCAPushButton *pushButton_21;
    QCAPushButton *pushButton_22;
    QLabel *label_48;
    QLabel *label_54;
    QLabel *label_51;
    QCALabel *label_47;
    QCAPushButton *pushButton_20;
    QCALCDNumber *lcdNumber_13;
    QScrollBar *horizontalScrollBar_2;
    QLabel *label_53;
    QCAPushButton *pushButton_19;
    QLabel *label_49;
    QCAAxis *sofn2Axis_2;
    QLabel *label_32;
    QCAAxis *acc2Axis_2;
    QCALabel *label_37;
    QPushButton *pushButton_14;
    QCAAxis *curr2Axis_2;
    QLabel *label_36;
    QCAAxis *max2Axis_2;
    QCAPushButton *pushButton_16;
    QCAPushButton *pushButton_40;
    QCAAxis *ref2Axis_2;
    QCAAxis *speed2Axis_2;
    QCAPushButton *pushButton_12;
    QCAAxis *sofp2Axis_2;
    QCALabel *label_33;
    QCAAxis *Axis2;

    void setupUi(QDialog *smu2_peaxism2)
    {
        if (smu2_peaxism2->objectName().isEmpty())
            smu2_peaxism2->setObjectName(QStringLiteral("smu2_peaxism2"));
        smu2_peaxism2->resize(1095, 627);
        label_44 = new QLabel(smu2_peaxism2);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(310, 20, 71, 16));
        pushButton_17 = new QCAPushButton(smu2_peaxism2);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(410, 130, 81, 22));
        pushButton_4 = new QCAPushButton(smu2_peaxism2);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(20, 101, 81, 51));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_6 = new QCAPushButton(smu2_peaxism2);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(310, 130, 81, 22));
        label_13 = new QCALabel(smu2_peaxism2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(520, 90, 59, 14));
        label_45 = new QCALabel(smu2_peaxism2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 50, 59, 14));
        pushButton_5 = new QCAPushButton(smu2_peaxism2);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(120, 130, 81, 22));
        lcdNumber_11 = new QCALCDNumber(smu2_peaxism2);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(320, 90, 64, 23));
        pushButton_13 = new QCAPushButton(smu2_peaxism2);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(210, 130, 81, 22));
        label_46 = new QLabel(smu2_peaxism2);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 30, 59, 14));
        pushButton_18 = new QCAPushButton(smu2_peaxism2);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(510, 130, 81, 22));
        label_15 = new QLabel(smu2_peaxism2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(760, 50, 59, 14));
        label_15->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_17 = new QLabel(smu2_peaxism2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(830, 80, 111, 16));
        label_14 = new QLabel(smu2_peaxism2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(940, 20, 59, 14));
        label_24 = new QCALabel(smu2_peaxism2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(970, 120, 81, 16));
        label_23 = new QCALabel(smu2_peaxism2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(970, 100, 91, 16));
        label_16 = new QLabel(smu2_peaxism2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(830, 60, 111, 16));
        label_21 = new QCALabel(smu2_peaxism2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(970, 60, 91, 16));
        label_25 = new QCALabel(smu2_peaxism2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(970, 140, 91, 16));
        label_20 = new QLabel(smu2_peaxism2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(830, 140, 101, 16));
        label_19 = new QLabel(smu2_peaxism2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(830, 120, 91, 16));
        label_22 = new QCALabel(smu2_peaxism2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(970, 80, 91, 16));
        label_18 = new QLabel(smu2_peaxism2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(830, 100, 91, 16));
        label_26 = new QLabel(smu2_peaxism2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(740, 180, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_62 = new QLabel(smu2_peaxism2);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(420, 460, 59, 14));
        pushButton_28 = new QCAPushButton(smu2_peaxism2);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(490, 280, 31, 21));
        pushButton_73 = new QCAPushButton(smu2_peaxism2);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(490, 300, 31, 21));
        pushButton_73->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_72 = new QCAPushButton(smu2_peaxism2);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(490, 400, 31, 21));
        pushButton_72->setStyleSheet(QStringLiteral(""));
        pushButton_67 = new QCAPushButton(smu2_peaxism2);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(540, 540, 31, 21));
        label_60 = new QLabel(smu2_peaxism2);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(420, 420, 59, 14));
        pushButton_34 = new QCAPushButton(smu2_peaxism2);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(540, 400, 31, 21));
        pushButton_42 = new QCAPushButton(smu2_peaxism2);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(540, 480, 31, 21));
        pushButton_59 = new QCAPushButton(smu2_peaxism2);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(490, 460, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_50 = new QCAPushButton(smu2_peaxism2);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(540, 560, 31, 21));
        label_83 = new QLabel(smu2_peaxism2);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(460, 180, 81, 16));
        label_83->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_66 = new QLabel(smu2_peaxism2);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(620, 480, 71, 16));
        pushButton_65 = new QCAPushButton(smu2_peaxism2);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(490, 580, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        pushButton_57 = new QCAPushButton(smu2_peaxism2);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(570, 400, 31, 21));
        pushButton_36 = new QCAPushButton(smu2_peaxism2);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(540, 420, 31, 21));
        pushButton_71 = new QCAPushButton(smu2_peaxism2);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(570, 300, 31, 21));
        label_80 = new QLabel(smu2_peaxism2);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(620, 340, 71, 16));
        pushButton_32 = new QCAPushButton(smu2_peaxism2);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(540, 360, 31, 21));
        pushButton_51 = new QCAPushButton(smu2_peaxism2);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(570, 560, 31, 21));
        pushButton_54 = new QCAPushButton(smu2_peaxism2);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(490, 360, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        pushButton_33 = new QCAPushButton(smu2_peaxism2);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(570, 380, 31, 21));
        pushButton_39 = new QCAPushButton(smu2_peaxism2);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(570, 440, 31, 21));
        pushButton_38 = new QCAPushButton(smu2_peaxism2);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(570, 320, 31, 21));
        lcdNumber_15 = new QCALCDNumber(smu2_peaxism2);
        lcdNumber_15->setObjectName(QStringLiteral("lcdNumber_15"));
        lcdNumber_15->setGeometry(QRect(540, 220, 64, 23));
        lcdNumber_15->setMode(QLCDNumber::Hex);
        pushButton_53 = new QCAPushButton(smu2_peaxism2);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(570, 580, 31, 21));
        pushButton_58 = new QCAPushButton(smu2_peaxism2);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(490, 440, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_56 = new QCAPushButton(smu2_peaxism2);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(570, 280, 31, 21));
        lcdNumber_14 = new QCALCDNumber(smu2_peaxism2);
        lcdNumber_14->setObjectName(QStringLiteral("lcdNumber_14"));
        lcdNumber_14->setGeometry(QRect(460, 250, 64, 23));
        lcdNumber_14->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_14->setMode(QLCDNumber::Hex);
        lcdNumber_14->setSegmentStyle(QLCDNumber::Filled);
        pushButton_55 = new QCAPushButton(smu2_peaxism2);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(490, 380, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_31 = new QCAPushButton(smu2_peaxism2);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(570, 360, 31, 21));
        pushButton_26 = new QCAPushButton(smu2_peaxism2);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(540, 320, 31, 21));
        pushButton_63 = new QCAPushButton(smu2_peaxism2);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(490, 540, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_27 = new QCAPushButton(smu2_peaxism2);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(540, 280, 31, 21));
        pushButton_61 = new QCAPushButton(smu2_peaxism2);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(490, 500, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_52 = new QCAPushButton(smu2_peaxism2);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(540, 580, 31, 21));
        label_68 = new QLabel(smu2_peaxism2);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(420, 580, 59, 14));
        pushButton_48 = new QCAPushButton(smu2_peaxism2);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(540, 380, 31, 21));
        label_79 = new QLabel(smu2_peaxism2);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(620, 540, 71, 16));
        pushButton_46 = new QCAPushButton(smu2_peaxism2);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(540, 520, 31, 21));
        label_82 = new QLabel(smu2_peaxism2);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(620, 380, 71, 16));
        label_77 = new QLabel(smu2_peaxism2);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(620, 580, 71, 16));
        label_63 = new QLabel(smu2_peaxism2);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(620, 320, 71, 16));
        label_57 = new QLabel(smu2_peaxism2);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(420, 360, 59, 14));
        label_70 = new QLabel(smu2_peaxism2);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(620, 460, 71, 16));
        label_74 = new QLabel(smu2_peaxism2);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(420, 400, 59, 14));
        pushButton_30 = new QCAPushButton(smu2_peaxism2);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(490, 340, 31, 21));
        pushButton_30->setStyleSheet(QStringLiteral(""));
        label_61 = new QLabel(smu2_peaxism2);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(420, 440, 59, 14));
        pushButton_43 = new QCAPushButton(smu2_peaxism2);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(570, 480, 31, 21));
        pushButton_35 = new QCAPushButton(smu2_peaxism2);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(490, 320, 31, 21));
        pushButton_35->setStyleSheet(QStringLiteral(""));
        pushButton_29 = new QCAPushButton(smu2_peaxism2);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(570, 340, 31, 21));
        label_67 = new QLabel(smu2_peaxism2);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(420, 560, 59, 14));
        pushButton_60 = new QCAPushButton(smu2_peaxism2);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(490, 480, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        label_64 = new QLabel(smu2_peaxism2);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(420, 500, 59, 14));
        label_85 = new QLabel(smu2_peaxism2);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(620, 420, 71, 16));
        pushButton_69 = new QCAPushButton(smu2_peaxism2);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(490, 420, 31, 21));
        pushButton_69->setStyleSheet(QStringLiteral(""));
        label_56 = new QLabel(smu2_peaxism2);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(620, 400, 71, 16));
        label_73 = new QLabel(smu2_peaxism2);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(420, 280, 59, 14));
        label_78 = new QLabel(smu2_peaxism2);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(420, 320, 59, 14));
        label_58 = new QLabel(smu2_peaxism2);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(420, 340, 59, 14));
        label_55 = new QLabel(smu2_peaxism2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(620, 360, 71, 16));
        pushButton_41 = new QCAPushButton(smu2_peaxism2);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(570, 460, 31, 21));
        label_81 = new QLabel(smu2_peaxism2);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(620, 440, 71, 16));
        pushButton_45 = new QCAPushButton(smu2_peaxism2);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(540, 340, 31, 21));
        label_86 = new QLabel(smu2_peaxism2);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(420, 380, 59, 14));
        pushButton_68 = new QCAPushButton(smu2_peaxism2);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(540, 440, 31, 21));
        pushButton_37 = new QCAPushButton(smu2_peaxism2);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(570, 420, 31, 21));
        pushButton_66 = new QCAPushButton(smu2_peaxism2);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(570, 500, 31, 21));
        pushButton_62 = new QCAPushButton(smu2_peaxism2);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(490, 520, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_84 = new QLabel(smu2_peaxism2);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(620, 560, 71, 16));
        pushButton_70 = new QCAPushButton(smu2_peaxism2);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(540, 300, 31, 21));
        label_75 = new QLabel(smu2_peaxism2);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(620, 520, 71, 16));
        label_59 = new QLabel(smu2_peaxism2);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(620, 300, 71, 16));
        pushButton_44 = new QCAPushButton(smu2_peaxism2);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(540, 500, 31, 21));
        label_71 = new QLabel(smu2_peaxism2);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(620, 280, 71, 16));
        pushButton_49 = new QCAPushButton(smu2_peaxism2);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(570, 540, 31, 21));
        label_76 = new QLabel(smu2_peaxism2);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(420, 540, 59, 14));
        label_65 = new QLabel(smu2_peaxism2);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(420, 520, 59, 14));
        pushButton_47 = new QCAPushButton(smu2_peaxism2);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(570, 520, 31, 21));
        pushButton_64 = new QCAPushButton(smu2_peaxism2);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(490, 560, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        pushButton_74 = new QCAPushButton(smu2_peaxism2);
        pushButton_74->setObjectName(QStringLiteral("pushButton_74"));
        pushButton_74->setGeometry(QRect(540, 460, 31, 21));
        lcdNumber_16 = new QCALCDNumber(smu2_peaxism2);
        lcdNumber_16->setObjectName(QStringLiteral("lcdNumber_16"));
        lcdNumber_16->setGeometry(QRect(540, 250, 64, 23));
        lcdNumber_16->setStyleSheet(QStringLiteral(""));
        lcdNumber_16->setMode(QLCDNumber::Hex);
        label_69 = new QLabel(smu2_peaxism2);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(620, 500, 71, 16));
        pushButton_23 = new QCAPushButton(smu2_peaxism2);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(150, 310, 61, 22));
        pushButton_21 = new QCAPushButton(smu2_peaxism2);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(150, 340, 151, 22));
        pushButton_22 = new QCAPushButton(smu2_peaxism2);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(240, 310, 61, 22));
        label_48 = new QLabel(smu2_peaxism2);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(20, 310, 111, 16));
        label_54 = new QLabel(smu2_peaxism2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(20, 270, 111, 16));
        label_51 = new QLabel(smu2_peaxism2);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(20, 190, 121, 16));
        label_51->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_47 = new QCALabel(smu2_peaxism2);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(180, 270, 101, 16));
        pushButton_20 = new QCAPushButton(smu2_peaxism2);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(230, 430, 31, 31));
        lcdNumber_13 = new QCALCDNumber(smu2_peaxism2);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(120, 410, 64, 23));
        horizontalScrollBar_2 = new QScrollBar(smu2_peaxism2);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(70, 440, 151, 16));
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        label_53 = new QLabel(smu2_peaxism2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(20, 340, 121, 16));
        pushButton_19 = new QCAPushButton(smu2_peaxism2);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(30, 430, 31, 31));
        label_49 = new QLabel(smu2_peaxism2);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(100, 390, 111, 16));
        sofn2Axis_2 = new QCAAxis(smu2_peaxism2);
        sofn2Axis_2->setObjectName(QStringLiteral("sofn2Axis_2"));
        sofn2Axis_2->setGeometry(QRect(710, 400, 345, 27));
        sofn2Axis_2->setMinimumSize(QSize(100, 10));
        label_32 = new QLabel(smu2_peaxism2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(710, 380, 111, 16));
        acc2Axis_2 = new QCAAxis(smu2_peaxism2);
        acc2Axis_2->setObjectName(QStringLiteral("acc2Axis_2"));
        acc2Axis_2->setGeometry(QRect(710, 340, 345, 27));
        acc2Axis_2->setMinimumSize(QSize(100, 10));
        label_37 = new QCALabel(smu2_peaxism2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(830, 460, 59, 14));
        pushButton_14 = new QPushButton(smu2_peaxism2);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(980, 370, 51, 22));
        curr2Axis_2 = new QCAAxis(smu2_peaxism2);
        curr2Axis_2->setObjectName(QStringLiteral("curr2Axis_2"));
        curr2Axis_2->setGeometry(QRect(710, 220, 345, 27));
        curr2Axis_2->setMinimumSize(QSize(100, 10));
        label_36 = new QLabel(smu2_peaxism2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(710, 460, 111, 16));
        max2Axis_2 = new QCAAxis(smu2_peaxism2);
        max2Axis_2->setObjectName(QStringLiteral("max2Axis_2"));
        max2Axis_2->setGeometry(QRect(710, 310, 345, 27));
        max2Axis_2->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu2_peaxism2);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(920, 460, 51, 22));
        pushButton_40 = new QCAPushButton(smu2_peaxism2);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(980, 460, 51, 22));
        ref2Axis_2 = new QCAAxis(smu2_peaxism2);
        ref2Axis_2->setObjectName(QStringLiteral("ref2Axis_2"));
        ref2Axis_2->setGeometry(QRect(710, 250, 345, 27));
        ref2Axis_2->setMinimumSize(QSize(100, 10));
        speed2Axis_2 = new QCAAxis(smu2_peaxism2);
        speed2Axis_2->setObjectName(QStringLiteral("speed2Axis_2"));
        speed2Axis_2->setGeometry(QRect(710, 280, 345, 27));
        speed2Axis_2->setMinimumSize(QSize(100, 10));
        pushButton_12 = new QCAPushButton(smu2_peaxism2);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(920, 370, 51, 22));
        sofp2Axis_2 = new QCAAxis(smu2_peaxism2);
        sofp2Axis_2->setObjectName(QStringLiteral("sofp2Axis_2"));
        sofp2Axis_2->setGeometry(QRect(710, 430, 345, 27));
        sofp2Axis_2->setMinimumSize(QSize(100, 10));
        label_33 = new QCALabel(smu2_peaxism2);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(830, 380, 59, 14));
        Axis2 = new QCAAxis(smu2_peaxism2);
        Axis2->setObjectName(QStringLiteral("Axis2"));
        Axis2->setGeometry(QRect(20, 210, 360, 32));

        retranslateUi(smu2_peaxism2);

        QMetaObject::connectSlotsByName(smu2_peaxism2);
    } // setupUi

    void retranslateUi(QDialog *smu2_peaxism2)
    {
        smu2_peaxism2->setWindowTitle(QApplication::translate("smu2_peaxism2", "Dialog", 0));
        label_44->setText(QApplication::translate("smu2_peaxism2", "SMU41_2", 0));
        pushButton_17->setText(QApplication::translate("smu2_peaxism2", "Lock", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:LockM2", 0)));
        pushButton_4->setText(QApplication::translate("smu2_peaxism2", "STOP", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:StopM2", 0)));
        pushButton_6->setText(QApplication::translate("smu2_peaxism2", "RUN", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:RunM2", 0)));
        label_13->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdPosM2.EGU", 0)));
        label_45->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:ChkAliveM2_.DESC", 0)));
        pushButton_5->setText(QApplication::translate("smu2_peaxism2", "LSN", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:LsnM2", 0)));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdPosM2", 0)));
        pushButton_13->setText(QApplication::translate("smu2_peaxism2", "REF", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:HomeM2", 0)));
        label_46->setText(QApplication::translate("smu2_peaxism2", "DESC", 0));
        pushButton_18->setText(QApplication::translate("smu2_peaxism2", "LSP", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:LspM2", 0)));
        label_15->setText(QApplication::translate("smu2_peaxism2", "info set", 0));
        label_17->setText(QApplication::translate("smu2_peaxism2", "nominal position", 0));
        label_14->setText(QApplication::translate("smu2_peaxism2", "M2", 0));
        label_24->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdCaptValM2", 0)));
        label_23->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdCurSpeedM2", 0)));
        label_16->setText(QApplication::translate("smu2_peaxism2", "current position", 0));
        label_21->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_21->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdPosM2", 0)));
        label_25->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdBrakeDistM2", 0)));
        label_20->setText(QApplication::translate("smu2_peaxism2", "brake distance", 0));
        label_19->setText(QApplication::translate("smu2_peaxism2", "capture value", 0));
        label_22->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdNomPosM2", 0)));
        label_18->setText(QApplication::translate("smu2_peaxism2", "current speed", 0));
        label_26->setText(QApplication::translate("smu2_peaxism2", "parameter set", 0));
        label_62->setText(QApplication::translate("smu2_peaxism2", "DV_OK", 0));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_73->setText(QString());
        pushButton_73->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_72->setText(QString());
        pushButton_72->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_67->setText(QString());
        pushButton_67->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_60->setText(QApplication::translate("smu2_peaxism2", "SP", 0));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_83->setText(QApplication::translate("smu2_peaxism2", "error codes", 0));
        label_66->setText(QApplication::translate("smu2_peaxism2", "Encoder", 0));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_71->setText(QString());
        pushButton_71->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_80->setText(QApplication::translate("smu2_peaxism2", "Track Err", 0));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        lcdNumber_15->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        lcdNumber_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_68->setText(QApplication::translate("smu2_peaxism2", "LOCK", 0));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_79->setText(QApplication::translate("smu2_peaxism2", "DV_ERR", 0));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_82->setText(QApplication::translate("smu2_peaxism2", "EXT ERR", 0));
        label_77->setText(QApplication::translate("smu2_peaxism2", "LSN", 0));
        label_63->setText(QApplication::translate("smu2_peaxism2", "Ref Err", 0));
        label_57->setText(QApplication::translate("smu2_peaxism2", "ABS", 0));
        label_70->setText(QApplication::translate("smu2_peaxism2", "Powerfail", 0));
        label_74->setText(QString());
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        label_61->setText(QApplication::translate("smu2_peaxism2", "70X I", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_67->setText(QApplication::translate("smu2_peaxism2", "CAPT", 0));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        label_64->setText(QApplication::translate("smu2_peaxism2", "LSN", 0));
        label_85->setText(QApplication::translate("smu2_peaxism2", "SW LSN", 0));
        pushButton_69->setText(QString());
        pushButton_69->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        label_56->setText(QApplication::translate("smu2_peaxism2", "SW LSP", 0));
        label_73->setText(QApplication::translate("smu2_peaxism2", "ERROR", 0));
        label_78->setText(QApplication::translate("smu2_peaxism2", "DIR", 0));
        label_58->setText(QApplication::translate("smu2_peaxism2", "RUN", 0));
        label_55->setText(QApplication::translate("smu2_peaxism2", "SW Speed", 0));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_81->setText(QString());
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_86->setText(QApplication::translate("smu2_peaxism2", "OSPD", 0));
        pushButton_68->setText(QString());
        pushButton_68->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_66->setText(QString());
        pushButton_66->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        label_84->setText(QApplication::translate("smu2_peaxism2", "LSP", 0));
        pushButton_70->setText(QString());
        pushButton_70->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_75->setText(QApplication::translate("smu2_peaxism2", "HW Speed", 0));
        label_59->setText(QApplication::translate("smu2_peaxism2", "POSA", 0));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        label_71->setText(QApplication::translate("smu2_peaxism2", "User Stop", 0));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_76->setText(QApplication::translate("smu2_peaxism2", "REF", 0));
        label_65->setText(QApplication::translate("smu2_peaxism2", "LSP", 0));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdStateM2", 0)));
        pushButton_74->setText(QString());
        pushButton_74->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrStateM2", 0)));
        lcdNumber_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdErrFlagM2", 0)));
        label_69->setText(QString());
        pushButton_23->setText(QApplication::translate("smu2_peaxism2", "-", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:ContNegM2", 0)));
        pushButton_21->setText(QApplication::translate("smu2_peaxism2", "GoRef", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:RefM2", 0)));
        pushButton_22->setText(QApplication::translate("smu2_peaxism2", "+", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:ContPosM2", 0)));
        label_48->setText(QApplication::translate("smu2_peaxism2", "move continous", 0));
        label_54->setText(QApplication::translate("smu2_peaxism2", "move absolute to", 0));
        label_51->setText(QApplication::translate("smu2_peaxism2", "motion commands", 0));
        label_47->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:AbsM2", 0)));
        pushButton_20->setText(QApplication::translate("smu2_peaxism2", "+", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:ContPosM2", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSpeedM2", 0)));
        label_53->setText(QApplication::translate("smu2_peaxism2", "move to reference", 0));
        pushButton_19->setText(QApplication::translate("smu2_peaxism2", "-", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:ContNegM2", 0)));
        label_49->setText(QApplication::translate("smu2_peaxism2", "continous mode", 0));
        sofn2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "soft limit negativ", 0)));
        sofn2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSwLimNegM2", 0)));
        sofn2Axis_2->setProperty("units", QVariant(QString()));
        sofn2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSwLimNegM2", 0)));
        label_32->setText(QApplication::translate("smu2_peaxism2", "ramp shape", 0));
        acc2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "acceleration time", 0)));
        acc2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdAccTimeM2", 0)));
        acc2Axis_2->setProperty("units", QVariant(QString()));
        acc2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdAccTimeM2", 0)));
        label_37->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSwLimM2", 0)));
        pushButton_14->setText(QApplication::translate("smu2_peaxism2", "exp", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:AccM2", 0)));
        curr2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "current position", 0)));
        curr2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdPosM2", 0)));
        curr2Axis_2->setProperty("units", QVariant(QApplication::translate("smu2_peaxism2", "steps", 0)));
        curr2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdPosM2", 0)));
        label_36->setText(QApplication::translate("smu2_peaxism2", "soft limit", 0));
        max2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "maximal speed", 0)));
        max2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdMaxSpeedM2", 0)));
        max2Axis_2->setProperty("units", QVariant(QString()));
        max2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdMaxSpeedM2", 0)));
        pushButton_16->setText(QApplication::translate("smu2_peaxism2", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:SwLimM2", 0)));
        pushButton_40->setText(QApplication::translate("smu2_peaxism2", "on", 0));
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:SwLimM2", 0)));
        ref2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "reference positic", 0)));
        ref2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdRefM2", 0)));
        ref2Axis_2->setProperty("units", QVariant(QString()));
        ref2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdRefM2", 0)));
        speed2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "speed", 0)));
        speed2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSpeedM2", 0)));
        speed2Axis_2->setProperty("units", QVariant(QString()));
        speed2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSpeedM2", 0)));
        pushButton_12->setText(QApplication::translate("smu2_peaxism2", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:AccM2", 0)));
        sofp2Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "soft limit positiv", 0)));
        sofp2Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSwLimPosM2", 0)));
        sofp2Axis_2->setProperty("units", QVariant(QString()));
        sofp2Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdSwLimPosM2", 0)));
        label_33->setText(QApplication::translate("smu2_peaxism2", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdAccM2", 0)));
        Axis2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism2", "motive relative", 0)));
        Axis2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdRelM2", 0)));
        Axis2->setProperty("units", QVariant(QApplication::translate("smu2_peaxism2", "steps", 0)));
        Axis2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism2", "SMU41_2:rdRelM2", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu2_peaxism2: public Ui_smu2_peaxism2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU2_PEAXISM2_H
