/********************************************************************************
** Form generated from reading UI file 'smu1_pgm1m1.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU1_PGM1M1_H
#define UI_SMU1_PGM1M1_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu1_pgm1m1
{
public:
    QLabel *label_54;
    QCAPushButton *pushButton_30;
    QLabel *label_20;
    QLabel *label_50;
    QCAPushButton *pushButton_58;
    QLabel *label_49;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_40;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_18;
    QLabel *label_17;
    QCAPushButton *pushButton_36;
    QLabel *label_9;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_6;
    QCAPushButton *pushButton_15;
    QLabel *label_26;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_62;
    QCAPushButton *pushButton_45;
    QLabel *label_45;
    QCAPushButton *pushButton_60;
    QCAPushButton *pushButton_31;
    QCAPushButton *pushButton_24;
    QLabel *label_59;
    QCAPushButton *pushButton_49;
    QCAPushButton *pushButton_56;
    QCALabel *label_4;
    QLabel *label_52;
    QCALabel *label_23;
    QCAPushButton *pushButton_4;
    QCALabel *label_8;
    QCAPushButton *pushButton_51;
    QCALCDNumber *lcdNumber_12;
    QCAPushButton *pushButton_19;
    QCAPushButton *pushButton_46;
    QCALabel *label_2;
    QCAPushButton *pushButton_53;
    QLabel *label_61;
    QLabel *label_18;
    QCALabel *label_21;
    QLabel *label_48;
    QLabel *label_14;
    QCAPushButton *pushButton_2;
    QLabel *label_62;
    QLabel *label;
    QLabel *label_53;
    QCAPushButton *pushButton_5;
    QLabel *label_66;
    QCALCDNumber *lcdNumber_11;
    QCAPushButton *pushButton_63;
    QLabel *label_64;
    QLabel *label_16;
    QCAPushButton *pushButton_44;
    QCAPushButton *pushButton_14;
    QLabel *label_65;
    QLabel *label_43;
    QLabel *label_60;
    QLabel *label_46;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_3;
    QCAPushButton *pushButton_38;
    QLabel *label_10;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_25;
    QCAPushButton *pushButton_65;
    QCALCDNumber *lcdNumber;
    QCAPushButton *pushButton;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_35;
    QCAPushButton *pushButton_7;
    QCALabel *label_22;
    QLabel *label_3;
    QCALCDNumber *lcdNumber_3;
    QCAPushButton *pushButton_37;
    QCAPushButton *pushButton_41;
    QLabel *label_38;
    QCAPushButton *pushButton_10;
    QLabel *label_42;
    QCAPushButton *pushButton_23;
    QLabel *label_40;
    QCAPushButton *pushButton_52;
    QCAPushButton *pushButton_20;
    QScrollBar *horizontalScrollBar;
    QLabel *label_68;
    QCAPushButton *pushButton_29;
    QCALCDNumber *lcdNumber_13;
    QLabel *label_15;
    QLabel *label_47;
    QCAPushButton *pushButton_11;
    QLabel *label_39;
    QLabel *label_19;
    QCAPushButton *pushButton_48;
    QCAPushButton *pushButton_27;
    QLabel *label_44;
    QLabel *label_41;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_28;
    QLabel *label_56;
    QLabel *label_63;
    QCAPushButton *pushButton_34;
    QLabel *label_58;
    QLabel *label_11;
    QCALabel *label_24;
    QCALabel *label_25;
    QLabel *label_55;
    QCAPushButton *pushButton_64;
    QLabel *label_12;
    QLabel *label_5;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_47;
    QCAPushButton *pushButton_21;
    QCAPushButton *pushButton_54;
    QLabel *label_57;
    QLabel *label_13;
    QCAPushButton *pushButton_59;
    QLabel *label_67;
    QLabel *label_51;
    QCAPushButton *pushButton_42;
    QLabel *label_32;
    QCAAxis *ref1Axis;
    QCAAxis *sofn1Axis;
    QLabel *label_36;
    QCAAxis *acc1Axis;
    QCAAxis *sofp1Axis;
    QCAAxis *curr1Axis;
    QCAPushButton *pushButton_12;
    QCALabel *label_37;
    QCAPushButton *pushButton_17;
    QCALabel *label_33;
    QCAAxis *speed1Axis;
    QCAPushButton *pushButton_16;
    QPushButton *pushButton_13;
    QCAAxis *max1Axis;
    QCAAxis *Axis1;

    void setupUi(QDialog *smu1_pgm1m1)
    {
        if (smu1_pgm1m1->objectName().isEmpty())
            smu1_pgm1m1->setObjectName(QStringLiteral("smu1_pgm1m1"));
        smu1_pgm1m1->resize(1049, 623);
        label_54 = new QLabel(smu1_pgm1m1);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(540, 550, 71, 16));
        pushButton_30 = new QCAPushButton(smu1_pgm1m1);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(460, 370, 31, 21));
        label_20 = new QLabel(smu1_pgm1m1);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(760, 140, 101, 16));
        label_50 = new QLabel(smu1_pgm1m1);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(540, 470, 71, 16));
        pushButton_58 = new QCAPushButton(smu1_pgm1m1);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(410, 450, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral(""));
        label_49 = new QLabel(smu1_pgm1m1);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(540, 450, 71, 16));
        pushButton_22 = new QCAPushButton(smu1_pgm1m1);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(410, 330, 31, 21));
        pushButton_22->setStyleSheet(QStringLiteral(""));
        pushButton_40 = new QCAPushButton(smu1_pgm1m1);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(460, 470, 31, 21));
        pushButton_57 = new QCAPushButton(smu1_pgm1m1);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(410, 430, 31, 21));
        pushButton_57->setStyleSheet(QStringLiteral(""));
        pushButton_18 = new QCAPushButton(smu1_pgm1m1);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(410, 290, 31, 21));
        label_17 = new QLabel(smu1_pgm1m1);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(760, 80, 111, 16));
        pushButton_36 = new QCAPushButton(smu1_pgm1m1);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(460, 430, 31, 21));
        label_9 = new QLabel(smu1_pgm1m1);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 270, 111, 16));
        pushButton_39 = new QCAPushButton(smu1_pgm1m1);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(490, 450, 31, 21));
        pushButton_6 = new QCAPushButton(smu1_pgm1m1);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(550, 110, 81, 22));
        pushButton_15 = new QCAPushButton(smu1_pgm1m1);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(220, 430, 31, 31));
        label_26 = new QLabel(smu1_pgm1m1);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(640, 190, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_55 = new QCAPushButton(smu1_pgm1m1);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(410, 390, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_62 = new QCAPushButton(smu1_pgm1m1);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(410, 530, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_45 = new QCAPushButton(smu1_pgm1m1);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(490, 510, 31, 21));
        label_45 = new QLabel(smu1_pgm1m1);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(540, 370, 71, 16));
        pushButton_60 = new QCAPushButton(smu1_pgm1m1);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(410, 490, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        pushButton_31 = new QCAPushButton(smu1_pgm1m1);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(490, 370, 31, 21));
        pushButton_24 = new QCAPushButton(smu1_pgm1m1);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(460, 310, 31, 21));
        label_59 = new QLabel(smu1_pgm1m1);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(340, 410, 59, 14));
        pushButton_49 = new QCAPushButton(smu1_pgm1m1);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(490, 550, 31, 21));
        pushButton_56 = new QCAPushButton(smu1_pgm1m1);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(410, 410, 31, 21));
        pushButton_56->setStyleSheet(QStringLiteral(""));
        label_4 = new QCALabel(smu1_pgm1m1);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(560, 70, 59, 14));
        label_52 = new QLabel(smu1_pgm1m1);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(540, 510, 71, 16));
        label_23 = new QCALabel(smu1_pgm1m1);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(900, 100, 91, 16));
        pushButton_4 = new QCAPushButton(smu1_pgm1m1);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(350, 110, 81, 22));
        label_8 = new QCALabel(smu1_pgm1m1);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(170, 270, 101, 16));
        pushButton_51 = new QCAPushButton(smu1_pgm1m1);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(490, 570, 31, 21));
        lcdNumber_12 = new QCALCDNumber(smu1_pgm1m1);
        lcdNumber_12->setObjectName(QStringLiteral("lcdNumber_12"));
        lcdNumber_12->setGeometry(QRect(450, 230, 64, 23));
        lcdNumber_12->setMode(QLCDNumber::Hex);
        pushButton_19 = new QCAPushButton(smu1_pgm1m1);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(410, 310, 31, 21));
        pushButton_19->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_46 = new QCAPushButton(smu1_pgm1m1);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(460, 530, 31, 21));
        label_2 = new QCALabel(smu1_pgm1m1);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 30, 59, 14));
        pushButton_53 = new QCAPushButton(smu1_pgm1m1);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(490, 590, 31, 21));
        label_61 = new QLabel(smu1_pgm1m1);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(340, 450, 59, 14));
        label_18 = new QLabel(smu1_pgm1m1);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(760, 100, 91, 16));
        label_21 = new QCALabel(smu1_pgm1m1);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(900, 60, 91, 16));
        label_48 = new QLabel(smu1_pgm1m1);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(540, 430, 71, 16));
        label_14 = new QLabel(smu1_pgm1m1);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(870, 20, 59, 14));
        pushButton_2 = new QCAPushButton(smu1_pgm1m1);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(160, 110, 81, 22));
        label_62 = new QLabel(smu1_pgm1m1);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(340, 470, 59, 14));
        label = new QLabel(smu1_pgm1m1);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 59, 14));
        label_53 = new QLabel(smu1_pgm1m1);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(540, 530, 71, 16));
        pushButton_5 = new QCAPushButton(smu1_pgm1m1);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(450, 110, 81, 22));
        label_66 = new QLabel(smu1_pgm1m1);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(340, 550, 59, 14));
        lcdNumber_11 = new QCALCDNumber(smu1_pgm1m1);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(370, 260, 64, 23));
        lcdNumber_11->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_11->setMode(QLCDNumber::Hex);
        lcdNumber_11->setSegmentStyle(QLCDNumber::Filled);
        pushButton_63 = new QCAPushButton(smu1_pgm1m1);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(410, 550, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_64 = new QLabel(smu1_pgm1m1);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(340, 510, 59, 14));
        label_16 = new QLabel(smu1_pgm1m1);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(760, 60, 111, 16));
        pushButton_44 = new QCAPushButton(smu1_pgm1m1);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(460, 510, 31, 21));
        pushButton_14 = new QCAPushButton(smu1_pgm1m1);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(10, 430, 31, 31));
        label_65 = new QLabel(smu1_pgm1m1);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(340, 530, 59, 14));
        label_43 = new QLabel(smu1_pgm1m1);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(540, 330, 71, 16));
        label_60 = new QLabel(smu1_pgm1m1);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(340, 430, 59, 14));
        label_46 = new QLabel(smu1_pgm1m1);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(540, 390, 71, 16));
        pushButton_50 = new QCAPushButton(smu1_pgm1m1);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(460, 570, 31, 21));
        pushButton_3 = new QCAPushButton(smu1_pgm1m1);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(250, 110, 81, 22));
        pushButton_38 = new QCAPushButton(smu1_pgm1m1);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(460, 450, 31, 21));
        label_10 = new QLabel(smu1_pgm1m1);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 310, 111, 16));
        pushButton_61 = new QCAPushButton(smu1_pgm1m1);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(410, 510, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_25 = new QCAPushButton(smu1_pgm1m1);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(490, 310, 31, 21));
        pushButton_65 = new QCAPushButton(smu1_pgm1m1);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(410, 590, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        lcdNumber = new QCALCDNumber(smu1_pgm1m1);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(360, 70, 64, 23));
        pushButton = new QCAPushButton(smu1_pgm1m1);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(40, 90, 81, 51));
        pushButton->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_33 = new QCAPushButton(smu1_pgm1m1);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(490, 390, 31, 21));
        pushButton_35 = new QCAPushButton(smu1_pgm1m1);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(490, 410, 31, 21));
        pushButton_7 = new QCAPushButton(smu1_pgm1m1);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(140, 310, 61, 22));
        label_22 = new QCALabel(smu1_pgm1m1);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(900, 80, 91, 16));
        label_3 = new QLabel(smu1_pgm1m1);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(350, 20, 71, 16));
        lcdNumber_3 = new QCALCDNumber(smu1_pgm1m1);
        lcdNumber_3->setObjectName(QStringLiteral("lcdNumber_3"));
        lcdNumber_3->setGeometry(QRect(110, 410, 64, 23));
        pushButton_37 = new QCAPushButton(smu1_pgm1m1);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(490, 430, 31, 21));
        pushButton_41 = new QCAPushButton(smu1_pgm1m1);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(490, 470, 31, 21));
        label_38 = new QLabel(smu1_pgm1m1);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(340, 290, 59, 14));
        pushButton_10 = new QCAPushButton(smu1_pgm1m1);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(230, 310, 61, 22));
        label_42 = new QLabel(smu1_pgm1m1);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(540, 310, 71, 16));
        pushButton_23 = new QCAPushButton(smu1_pgm1m1);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(410, 350, 31, 21));
        pushButton_23->setStyleSheet(QStringLiteral(""));
        label_40 = new QLabel(smu1_pgm1m1);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(340, 330, 59, 14));
        pushButton_52 = new QCAPushButton(smu1_pgm1m1);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(460, 590, 31, 21));
        pushButton_20 = new QCAPushButton(smu1_pgm1m1);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(460, 290, 31, 21));
        horizontalScrollBar = new QScrollBar(smu1_pgm1m1);
        horizontalScrollBar->setObjectName(QStringLiteral("horizontalScrollBar"));
        horizontalScrollBar->setGeometry(QRect(60, 440, 151, 16));
        horizontalScrollBar->setOrientation(Qt::Horizontal);
        label_68 = new QLabel(smu1_pgm1m1);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(340, 590, 59, 14));
        pushButton_29 = new QCAPushButton(smu1_pgm1m1);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(490, 350, 31, 21));
        lcdNumber_13 = new QCALCDNumber(smu1_pgm1m1);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(450, 260, 64, 23));
        lcdNumber_13->setStyleSheet(QStringLiteral(""));
        lcdNumber_13->setMode(QLCDNumber::Hex);
        label_15 = new QLabel(smu1_pgm1m1);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(690, 50, 59, 14));
        label_15->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_47 = new QLabel(smu1_pgm1m1);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(540, 410, 71, 16));
        pushButton_11 = new QCAPushButton(smu1_pgm1m1);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(140, 340, 151, 22));
        label_39 = new QLabel(smu1_pgm1m1);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(540, 290, 71, 16));
        label_19 = new QLabel(smu1_pgm1m1);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(760, 120, 91, 16));
        pushButton_48 = new QCAPushButton(smu1_pgm1m1);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(460, 550, 31, 21));
        pushButton_27 = new QCAPushButton(smu1_pgm1m1);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(490, 330, 31, 21));
        label_44 = new QLabel(smu1_pgm1m1);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(540, 350, 71, 16));
        label_41 = new QLabel(smu1_pgm1m1);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(340, 350, 59, 14));
        pushButton_26 = new QCAPushButton(smu1_pgm1m1);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(460, 330, 31, 21));
        pushButton_28 = new QCAPushButton(smu1_pgm1m1);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(460, 350, 31, 21));
        label_56 = new QLabel(smu1_pgm1m1);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(540, 590, 71, 16));
        label_63 = new QLabel(smu1_pgm1m1);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(340, 490, 59, 14));
        pushButton_34 = new QCAPushButton(smu1_pgm1m1);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(460, 410, 31, 21));
        label_58 = new QLabel(smu1_pgm1m1);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(340, 390, 59, 14));
        label_11 = new QLabel(smu1_pgm1m1);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 340, 121, 16));
        label_24 = new QCALabel(smu1_pgm1m1);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(900, 120, 81, 16));
        label_25 = new QCALabel(smu1_pgm1m1);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(900, 140, 91, 16));
        label_55 = new QLabel(smu1_pgm1m1);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(540, 570, 71, 16));
        pushButton_64 = new QCAPushButton(smu1_pgm1m1);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(410, 570, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        label_12 = new QLabel(smu1_pgm1m1);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(90, 390, 111, 16));
        label_5 = new QLabel(smu1_pgm1m1);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 190, 121, 16));
        label_5->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_32 = new QCAPushButton(smu1_pgm1m1);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(460, 390, 31, 21));
        pushButton_43 = new QCAPushButton(smu1_pgm1m1);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(490, 490, 31, 21));
        pushButton_47 = new QCAPushButton(smu1_pgm1m1);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(490, 530, 31, 21));
        pushButton_21 = new QCAPushButton(smu1_pgm1m1);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(490, 290, 31, 21));
        pushButton_54 = new QCAPushButton(smu1_pgm1m1);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(410, 370, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        label_57 = new QLabel(smu1_pgm1m1);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(340, 370, 59, 14));
        label_13 = new QLabel(smu1_pgm1m1);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(380, 190, 81, 16));
        label_13->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_59 = new QCAPushButton(smu1_pgm1m1);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(410, 470, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_67 = new QLabel(smu1_pgm1m1);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(340, 570, 59, 14));
        label_51 = new QLabel(smu1_pgm1m1);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(540, 490, 71, 16));
        pushButton_42 = new QCAPushButton(smu1_pgm1m1);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(460, 490, 31, 21));
        label_32 = new QLabel(smu1_pgm1m1);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(640, 380, 111, 16));
        ref1Axis = new QCAAxis(smu1_pgm1m1);
        ref1Axis->setObjectName(QStringLiteral("ref1Axis"));
        ref1Axis->setGeometry(QRect(640, 250, 345, 27));
        ref1Axis->setMinimumSize(QSize(100, 10));
        sofn1Axis = new QCAAxis(smu1_pgm1m1);
        sofn1Axis->setObjectName(QStringLiteral("sofn1Axis"));
        sofn1Axis->setGeometry(QRect(640, 400, 345, 27));
        sofn1Axis->setMinimumSize(QSize(100, 10));
        label_36 = new QLabel(smu1_pgm1m1);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(640, 460, 111, 16));
        acc1Axis = new QCAAxis(smu1_pgm1m1);
        acc1Axis->setObjectName(QStringLiteral("acc1Axis"));
        acc1Axis->setGeometry(QRect(640, 340, 345, 27));
        acc1Axis->setMinimumSize(QSize(100, 10));
        sofp1Axis = new QCAAxis(smu1_pgm1m1);
        sofp1Axis->setObjectName(QStringLiteral("sofp1Axis"));
        sofp1Axis->setGeometry(QRect(640, 430, 345, 27));
        sofp1Axis->setMinimumSize(QSize(100, 10));
        curr1Axis = new QCAAxis(smu1_pgm1m1);
        curr1Axis->setObjectName(QStringLiteral("curr1Axis"));
        curr1Axis->setGeometry(QRect(640, 220, 345, 27));
        curr1Axis->setMinimumSize(QSize(100, 10));
        pushButton_12 = new QCAPushButton(smu1_pgm1m1);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(850, 370, 51, 22));
        label_37 = new QCALabel(smu1_pgm1m1);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(760, 460, 59, 14));
        pushButton_17 = new QCAPushButton(smu1_pgm1m1);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(910, 460, 51, 22));
        label_33 = new QCALabel(smu1_pgm1m1);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(760, 380, 59, 14));
        speed1Axis = new QCAAxis(smu1_pgm1m1);
        speed1Axis->setObjectName(QStringLiteral("speed1Axis"));
        speed1Axis->setGeometry(QRect(640, 280, 345, 27));
        speed1Axis->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu1_pgm1m1);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(850, 460, 51, 22));
        pushButton_13 = new QPushButton(smu1_pgm1m1);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(910, 370, 51, 22));
        max1Axis = new QCAAxis(smu1_pgm1m1);
        max1Axis->setObjectName(QStringLiteral("max1Axis"));
        max1Axis->setGeometry(QRect(640, 310, 345, 27));
        max1Axis->setMinimumSize(QSize(100, 10));
        Axis1 = new QCAAxis(smu1_pgm1m1);
        Axis1->setObjectName(QStringLiteral("Axis1"));
        Axis1->setGeometry(QRect(10, 210, 360, 32));

        retranslateUi(smu1_pgm1m1);

        QMetaObject::connectSlotsByName(smu1_pgm1m1);
    } // setupUi

    void retranslateUi(QDialog *smu1_pgm1m1)
    {
        smu1_pgm1m1->setWindowTitle(QApplication::translate("smu1_pgm1m1", "Dialog", 0));
        label_54->setText(QApplication::translate("smu1_pgm1m1", "DV_ERR", 0));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        label_20->setText(QApplication::translate("smu1_pgm1m1", "brake distance", 0));
        label_50->setText(QApplication::translate("smu1_pgm1m1", "Powerfail", 0));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_49->setText(QString());
        pushButton_22->setText(QString());
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_40->setText(QString());
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_18->setText(QString());
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_17->setText(QApplication::translate("smu1_pgm1m1", "nominal position", 0));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_9->setText(QApplication::translate("smu1_pgm1m1", "move absolute to", 0));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_6->setText(QApplication::translate("smu1_pgm1m1", "LSP", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:LspM1", 0)));
        pushButton_15->setText(QApplication::translate("smu1_pgm1m1", "+", 0));
        pushButton_15->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:ContPosM1", 0)));
        label_26->setText(QApplication::translate("smu1_pgm1m1", "parameter set", 0));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_45->setText(QApplication::translate("smu1_pgm1m1", "SW Speed", 0));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_24->setText(QString());
        pushButton_24->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_59->setText(QString());
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_4->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_4->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdPosM1.EGU", 0)));
        label_52->setText(QString());
        label_23->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdCurSpeedM1", 0)));
        pushButton_4->setText(QApplication::translate("smu1_pgm1m1", "RUN", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:RunM1", 0)));
        label_8->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_8->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:AbsM1", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        lcdNumber_12->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_19->setText(QString());
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        label_2->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_2->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:ChkAliveM1_.DESC", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_61->setText(QApplication::translate("smu1_pgm1m1", "70X I", 0));
        label_18->setText(QApplication::translate("smu1_pgm1m1", "current speed", 0));
        label_21->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_21->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdPosM1", 0)));
        label_48->setText(QApplication::translate("smu1_pgm1m1", "SW LSN", 0));
        label_14->setText(QApplication::translate("smu1_pgm1m1", "M1", 0));
        pushButton_2->setText(QApplication::translate("smu1_pgm1m1", "LSN", 0));
        pushButton_2->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:LsnM1", 0)));
        label_62->setText(QApplication::translate("smu1_pgm1m1", "DV_OK", 0));
        label->setText(QApplication::translate("smu1_pgm1m1", "DESC", 0));
        label_53->setText(QApplication::translate("smu1_pgm1m1", "HW Speed", 0));
        pushButton_5->setText(QApplication::translate("smu1_pgm1m1", "Lock", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:LockM1", 0)));
        label_66->setText(QApplication::translate("smu1_pgm1m1", "REF", 0));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_64->setText(QApplication::translate("smu1_pgm1m1", "LSN", 0));
        label_16->setText(QApplication::translate("smu1_pgm1m1", "current position", 0));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_14->setText(QApplication::translate("smu1_pgm1m1", "-", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:ContNegM1", 0)));
        label_65->setText(QApplication::translate("smu1_pgm1m1", "LSP", 0));
        label_43->setText(QApplication::translate("smu1_pgm1m1", "Ref Err", 0));
        label_60->setText(QApplication::translate("smu1_pgm1m1", "SP", 0));
        label_46->setText(QApplication::translate("smu1_pgm1m1", "EXT ERR", 0));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_3->setText(QApplication::translate("smu1_pgm1m1", "REF", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:HomeM1", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_10->setText(QApplication::translate("smu1_pgm1m1", "move continous", 0));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        pushButton_25->setText(QString());
        pushButton_25->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        lcdNumber->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdPosM1", 0)));
        pushButton->setText(QApplication::translate("smu1_pgm1m1", "STOP", 0));
        pushButton->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:StopM1", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_7->setText(QApplication::translate("smu1_pgm1m1", "-", 0));
        pushButton_7->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:ContNegM1", 0)));
        label_22->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdNomPosM1", 0)));
        label_3->setText(QApplication::translate("smu1_pgm1m1", "SMU41_1", 0));
        lcdNumber_3->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSpeedM1", 0)));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_38->setText(QApplication::translate("smu1_pgm1m1", "ERROR", 0));
        pushButton_10->setText(QApplication::translate("smu1_pgm1m1", "+", 0));
        pushButton_10->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:ContPosM1", 0)));
        label_42->setText(QApplication::translate("smu1_pgm1m1", "POSA", 0));
        pushButton_23->setText(QString());
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_40->setText(QApplication::translate("smu1_pgm1m1", "DIR", 0));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_20->setText(QString());
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_68->setText(QApplication::translate("smu1_pgm1m1", "LOCK", 0));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_15->setText(QApplication::translate("smu1_pgm1m1", "info set", 0));
        label_47->setText(QApplication::translate("smu1_pgm1m1", "SW LSP", 0));
        pushButton_11->setText(QApplication::translate("smu1_pgm1m1", "GoRef", 0));
        pushButton_11->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:RefM1", 0)));
        label_39->setText(QApplication::translate("smu1_pgm1m1", "User Stop", 0));
        label_19->setText(QApplication::translate("smu1_pgm1m1", "capture value", 0));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        label_44->setText(QApplication::translate("smu1_pgm1m1", "Track Err", 0));
        label_41->setText(QApplication::translate("smu1_pgm1m1", "RUN", 0));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        label_56->setText(QApplication::translate("smu1_pgm1m1", "LSN", 0));
        label_63->setText(QApplication::translate("smu1_pgm1m1", "ABS", 0));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        label_58->setText(QApplication::translate("smu1_pgm1m1", "OSPD", 0));
        label_11->setText(QApplication::translate("smu1_pgm1m1", "move to reference", 0));
        label_24->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdCaptValM1", 0)));
        label_25->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdBrakeDistM1", 0)));
        label_55->setText(QApplication::translate("smu1_pgm1m1", "LSP", 0));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_12->setText(QApplication::translate("smu1_pgm1m1", "continous mode", 0));
        label_5->setText(QApplication::translate("smu1_pgm1m1", "motion commands", 0));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_21->setText(QString());
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrFlagM1", 0)));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_57->setText(QApplication::translate("smu1_pgm1m1", "ABS", 0));
        label_13->setText(QApplication::translate("smu1_pgm1m1", "error codes", 0));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdStateM1", 0)));
        label_67->setText(QApplication::translate("smu1_pgm1m1", "CAPT", 0));
        label_51->setText(QApplication::translate("smu1_pgm1m1", "Encoder", 0));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdErrStateM1", 0)));
        label_32->setText(QApplication::translate("smu1_pgm1m1", "ramp shape", 0));
        ref1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "reference positic", 0)));
        ref1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdRefM1", 0)));
        ref1Axis->setProperty("units", QVariant(QString()));
        ref1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdRefM1", 0)));
        sofn1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "soft limit negativ", 0)));
        sofn1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSwLimNegM1", 0)));
        sofn1Axis->setProperty("units", QVariant(QString()));
        sofn1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSwLimNegM1", 0)));
        label_36->setText(QApplication::translate("smu1_pgm1m1", "soft limit", 0));
        acc1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "acceleration time", 0)));
        acc1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdAccTimeM1", 0)));
        acc1Axis->setProperty("units", QVariant(QString()));
        acc1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdAccTimeM1", 0)));
        sofp1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "soft limit positiv", 0)));
        sofp1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSwLimPosM1", 0)));
        sofp1Axis->setProperty("units", QVariant(QString()));
        sofp1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSwLimPosM1", 0)));
        curr1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "current position", 0)));
        curr1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdPosM1", 0)));
        curr1Axis->setProperty("units", QVariant(QApplication::translate("smu1_pgm1m1", "steps", 0)));
        curr1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdPosM1", 0)));
        pushButton_12->setText(QApplication::translate("smu1_pgm1m1", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:AccM1", 0)));
        label_37->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSwLimM1", 0)));
        pushButton_17->setText(QApplication::translate("smu1_pgm1m1", "on", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:SwLimM1", 0)));
        label_33->setText(QApplication::translate("smu1_pgm1m1", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdAccM1", 0)));
        speed1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "speed", 0)));
        speed1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSpeedM1", 0)));
        speed1Axis->setProperty("units", QVariant(QString()));
        speed1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdSpeedM1", 0)));
        pushButton_16->setText(QApplication::translate("smu1_pgm1m1", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:SwLimM1", 0)));
        pushButton_13->setText(QApplication::translate("smu1_pgm1m1", "exp", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:AccM1", 0)));
        max1Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "maximal speed", 0)));
        max1Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdMaxSpeedM1", 0)));
        max1Axis->setProperty("units", QVariant(QString()));
        max1Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdMaxSpeedM1", 0)));
        Axis1->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m1", "move relative", 0)));
        Axis1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdRelM1", 0)));
        Axis1->setProperty("units", QVariant(QApplication::translate("smu1_pgm1m1", "steps", 0)));
        Axis1->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m1", "SMU41_1:rdRelM1", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu1_pgm1m1: public Ui_smu1_pgm1m1 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU1_PGM1M1_H
