/********************************************************************************
** Form generated from reading UI file 'smu2_peaxism3.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU2_PEAXISM3_H
#define UI_SMU2_PEAXISM3_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu2_peaxism3
{
public:
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_28;
    QLabel *label_60;
    QCAPushButton *pushButton_46;
    QCAPushButton *pushButton_44;
    QCALCDNumber *lcdNumber_13;
    QLabel *label_78;
    QCAPushButton *pushButton_35;
    QLabel *label_55;
    QCAPushButton *pushButton_61;
    QLabel *label_56;
    QLabel *label_80;
    QCAPushButton *pushButton_17;
    QCAPushButton *pushButton_51;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_5;
    QCAPushButton *pushButton_60;
    QLabel *label_43;
    QCAPushButton *pushButton_13;
    QLabel *label_20;
    QCAPushButton *pushButton_27;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_49;
    QCAPushButton *pushButton_63;
    QCAPushButton *pushButton_74;
    QLabel *label_71;
    QCAPushButton *pushButton_65;
    QCAPushButton *pushButton_64;
    QCALabel *label_38;
    QCAPushButton *pushButton_42;
    QCAPushButton *pushButton_54;
    QCAPushButton *pushButton_68;
    QCAPushButton *pushButton_34;
    QLabel *label_83;
    QCALabel *label_41;
    QLabel *label_67;
    QCAPushButton *pushButton_73;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_62;
    QCALCDNumber *lcdNumber_16;
    QLabel *label_61;
    QCALabel *label_47;
    QLabel *label_81;
    QCALabel *label_13;
    QCAPushButton *pushButton_66;
    QCAPushButton *pushButton_72;
    QLabel *label_74;
    QLabel *label_77;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_48;
    QCALabel *label_25;
    QScrollBar *horizontalScrollBar_2;
    QLabel *label_26;
    QLabel *label_48;
    QCAPushButton *pushButton_23;
    QLabel *label_23;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_4;
    QLabel *label_82;
    QCAPushButton *pushButton_22;
    QLabel *label_49;
    QCAPushButton *pushButton_19;
    QLabel *label_58;
    QCAPushButton *pushButton_36;
    QLabel *label_66;
    QLabel *label_79;
    QCAPushButton *pushButton_41;
    QCAPushButton *pushButton_30;
    QCAPushButton *pushButton_38;
    QLabel *label_54;
    QLabel *label_57;
    QCAPushButton *pushButton_59;
    QLabel *label_19;
    QLabel *label_85;
    QCAPushButton *pushButton_52;
    QLabel *label_51;
    QLabel *label_39;
    QCAPushButton *pushButton_70;
    QLabel *label_68;
    QLabel *label_62;
    QCAPushButton *pushButton_32;
    QLabel *label_63;
    QLabel *label_59;
    QLabel *label_86;
    QCAPushButton *pushButton_69;
    QCAPushButton *pushButton_56;
    QCALCDNumber *lcdNumber_15;
    QCAPushButton *pushButton_31;
    QLabel *label_46;
    QLabel *label_53;
    QCAPushButton *pushButton_71;
    QCAPushButton *pushButton_53;
    QLabel *label_40;
    QCAPushButton *pushButton_6;
    QLabel *label_84;
    QLabel *label_73;
    QLabel *label_65;
    QLabel *label_70;
    QCAPushButton *pushButton_67;
    QLabel *label_75;
    QCAPushButton *pushButton_50;
    QLabel *label_44;
    QCALabel *label_45;
    QLabel *label_69;
    QCAPushButton *pushButton_37;
    QCAPushButton *pushButton_21;
    QCALabel *label_42;
    QCAPushButton *pushButton_58;
    QLabel *label_18;
    QCAPushButton *pushButton_45;
    QCALCDNumber *lcdNumber_11;
    QCALabel *label_24;
    QCALCDNumber *lcdNumber_14;
    QCAPushButton *pushButton_39;
    QLabel *label_64;
    QLabel *label_76;
    QCAPushButton *pushButton_20;
    QCAPushButton *pushButton_47;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_40;
    QCAPushButton *pushButton_12;
    QCAAxis *ref3Axis_2;
    QCAAxis *max3Axis_2;
    QCAAxis *acc3Axis_2;
    QLabel *label_32;
    QCALabel *label_37;
    QPushButton *pushButton_14;
    QCALabel *label_33;
    QLabel *label_36;
    QCAPushButton *pushButton_16;
    QCAAxis *speed3Axis_2;
    QCAAxis *curr3Axis_2;
    QCAAxis *sofn3Axis_2;
    QCAAxis *sofp3Axis_2;
    QCAAxis *Axis3;

    void setupUi(QDialog *smu2_peaxism3)
    {
        if (smu2_peaxism3->objectName().isEmpty())
            smu2_peaxism3->setObjectName(QStringLiteral("smu2_peaxism3"));
        smu2_peaxism3->resize(1140, 649);
        pushButton_18 = new QCAPushButton(smu2_peaxism3);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(520, 120, 81, 22));
        pushButton_28 = new QCAPushButton(smu2_peaxism3);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(470, 310, 31, 21));
        label_60 = new QLabel(smu2_peaxism3);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(400, 450, 59, 14));
        pushButton_46 = new QCAPushButton(smu2_peaxism3);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(520, 550, 31, 21));
        pushButton_44 = new QCAPushButton(smu2_peaxism3);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(520, 530, 31, 21));
        lcdNumber_13 = new QCALCDNumber(smu2_peaxism3);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(140, 440, 64, 23));
        label_78 = new QLabel(smu2_peaxism3);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(400, 350, 59, 14));
        pushButton_35 = new QCAPushButton(smu2_peaxism3);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(470, 350, 31, 21));
        pushButton_35->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_55 = new QLabel(smu2_peaxism3);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(600, 390, 71, 16));
        pushButton_61 = new QCAPushButton(smu2_peaxism3);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(470, 530, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_56 = new QLabel(smu2_peaxism3);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(600, 430, 71, 16));
        label_80 = new QLabel(smu2_peaxism3);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(600, 370, 71, 16));
        pushButton_17 = new QCAPushButton(smu2_peaxism3);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(420, 120, 81, 22));
        pushButton_51 = new QCAPushButton(smu2_peaxism3);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(550, 590, 31, 21));
        pushButton_55 = new QCAPushButton(smu2_peaxism3);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(470, 410, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_5 = new QCAPushButton(smu2_peaxism3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(130, 120, 81, 22));
        pushButton_60 = new QCAPushButton(smu2_peaxism3);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(470, 510, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        label_43 = new QLabel(smu2_peaxism3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(880, 110, 91, 16));
        pushButton_13 = new QCAPushButton(smu2_peaxism3);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(220, 120, 81, 22));
        label_20 = new QLabel(smu2_peaxism3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(880, 130, 91, 16));
        pushButton_27 = new QCAPushButton(smu2_peaxism3);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(520, 310, 31, 21));
        pushButton_29 = new QCAPushButton(smu2_peaxism3);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(550, 370, 31, 21));
        pushButton_49 = new QCAPushButton(smu2_peaxism3);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(550, 570, 31, 21));
        pushButton_63 = new QCAPushButton(smu2_peaxism3);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(470, 570, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_74 = new QCAPushButton(smu2_peaxism3);
        pushButton_74->setObjectName(QStringLiteral("pushButton_74"));
        pushButton_74->setGeometry(QRect(520, 490, 31, 21));
        label_71 = new QLabel(smu2_peaxism3);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(600, 310, 71, 16));
        pushButton_65 = new QCAPushButton(smu2_peaxism3);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(470, 610, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        pushButton_64 = new QCAPushButton(smu2_peaxism3);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(470, 590, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        label_38 = new QCALabel(smu2_peaxism3);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(1020, 90, 91, 16));
        pushButton_42 = new QCAPushButton(smu2_peaxism3);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(520, 510, 31, 21));
        pushButton_54 = new QCAPushButton(smu2_peaxism3);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(470, 390, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        pushButton_68 = new QCAPushButton(smu2_peaxism3);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(520, 470, 31, 21));
        pushButton_34 = new QCAPushButton(smu2_peaxism3);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(520, 430, 31, 21));
        label_83 = new QLabel(smu2_peaxism3);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(440, 210, 81, 16));
        label_83->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_41 = new QCALabel(smu2_peaxism3);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(1020, 70, 91, 16));
        label_67 = new QLabel(smu2_peaxism3);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(400, 590, 59, 14));
        pushButton_73 = new QCAPushButton(smu2_peaxism3);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(470, 330, 31, 21));
        pushButton_73->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_57 = new QCAPushButton(smu2_peaxism3);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(550, 430, 31, 21));
        pushButton_62 = new QCAPushButton(smu2_peaxism3);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(470, 550, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        lcdNumber_16 = new QCALCDNumber(smu2_peaxism3);
        lcdNumber_16->setObjectName(QStringLiteral("lcdNumber_16"));
        lcdNumber_16->setGeometry(QRect(520, 280, 64, 23));
        lcdNumber_16->setStyleSheet(QStringLiteral(""));
        lcdNumber_16->setMode(QLCDNumber::Hex);
        label_61 = new QLabel(smu2_peaxism3);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(400, 470, 59, 14));
        label_47 = new QCALabel(smu2_peaxism3);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(200, 300, 101, 16));
        label_81 = new QLabel(smu2_peaxism3);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(600, 470, 71, 16));
        label_13 = new QCALabel(smu2_peaxism3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(530, 80, 59, 14));
        pushButton_66 = new QCAPushButton(smu2_peaxism3);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(550, 530, 31, 21));
        pushButton_72 = new QCAPushButton(smu2_peaxism3);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(470, 430, 31, 21));
        pushButton_72->setStyleSheet(QStringLiteral(""));
        label_74 = new QLabel(smu2_peaxism3);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(400, 430, 59, 14));
        label_77 = new QLabel(smu2_peaxism3);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(600, 610, 71, 16));
        pushButton_26 = new QCAPushButton(smu2_peaxism3);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(520, 350, 31, 21));
        pushButton_48 = new QCAPushButton(smu2_peaxism3);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(520, 410, 31, 21));
        label_25 = new QCALabel(smu2_peaxism3);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(1020, 110, 91, 16));
        horizontalScrollBar_2 = new QScrollBar(smu2_peaxism3);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(90, 470, 151, 16));
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        label_26 = new QLabel(smu2_peaxism3);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(780, 210, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_48 = new QLabel(smu2_peaxism3);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(40, 340, 111, 16));
        pushButton_23 = new QCAPushButton(smu2_peaxism3);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(170, 340, 61, 22));
        label_23 = new QLabel(smu2_peaxism3);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(990, 20, 59, 14));
        pushButton_43 = new QCAPushButton(smu2_peaxism3);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(550, 510, 31, 21));
        pushButton_4 = new QCAPushButton(smu2_peaxism3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(30, 91, 81, 51));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        label_82 = new QLabel(smu2_peaxism3);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(600, 410, 71, 16));
        pushButton_22 = new QCAPushButton(smu2_peaxism3);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(260, 340, 61, 22));
        label_49 = new QLabel(smu2_peaxism3);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(120, 420, 111, 16));
        pushButton_19 = new QCAPushButton(smu2_peaxism3);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(50, 460, 31, 31));
        label_58 = new QLabel(smu2_peaxism3);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(400, 370, 59, 14));
        pushButton_36 = new QCAPushButton(smu2_peaxism3);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(520, 450, 31, 21));
        label_66 = new QLabel(smu2_peaxism3);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(600, 510, 71, 16));
        label_79 = new QLabel(smu2_peaxism3);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(600, 570, 71, 16));
        pushButton_41 = new QCAPushButton(smu2_peaxism3);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(550, 490, 31, 21));
        pushButton_30 = new QCAPushButton(smu2_peaxism3);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(470, 370, 31, 21));
        pushButton_30->setStyleSheet(QStringLiteral(""));
        pushButton_38 = new QCAPushButton(smu2_peaxism3);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(550, 350, 31, 21));
        label_54 = new QLabel(smu2_peaxism3);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(40, 300, 111, 16));
        label_57 = new QLabel(smu2_peaxism3);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(400, 390, 59, 14));
        pushButton_59 = new QCAPushButton(smu2_peaxism3);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(470, 490, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_19 = new QLabel(smu2_peaxism3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(880, 90, 111, 16));
        label_85 = new QLabel(smu2_peaxism3);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(600, 450, 71, 16));
        pushButton_52 = new QCAPushButton(smu2_peaxism3);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(520, 610, 31, 21));
        label_51 = new QLabel(smu2_peaxism3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(40, 220, 121, 16));
        label_51->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_39 = new QLabel(smu2_peaxism3);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(880, 70, 111, 16));
        pushButton_70 = new QCAPushButton(smu2_peaxism3);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(520, 330, 31, 21));
        label_68 = new QLabel(smu2_peaxism3);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(400, 610, 59, 14));
        label_62 = new QLabel(smu2_peaxism3);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(400, 490, 59, 14));
        pushButton_32 = new QCAPushButton(smu2_peaxism3);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(520, 390, 31, 21));
        label_63 = new QLabel(smu2_peaxism3);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(600, 350, 71, 16));
        label_59 = new QLabel(smu2_peaxism3);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(600, 330, 71, 16));
        label_86 = new QLabel(smu2_peaxism3);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(400, 410, 59, 14));
        pushButton_69 = new QCAPushButton(smu2_peaxism3);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(470, 450, 31, 21));
        pushButton_69->setStyleSheet(QStringLiteral(""));
        pushButton_56 = new QCAPushButton(smu2_peaxism3);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(550, 310, 31, 21));
        lcdNumber_15 = new QCALCDNumber(smu2_peaxism3);
        lcdNumber_15->setObjectName(QStringLiteral("lcdNumber_15"));
        lcdNumber_15->setGeometry(QRect(520, 250, 64, 23));
        lcdNumber_15->setMode(QLCDNumber::Hex);
        pushButton_31 = new QCAPushButton(smu2_peaxism3);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(550, 390, 31, 21));
        label_46 = new QLabel(smu2_peaxism3);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(30, 30, 59, 14));
        label_53 = new QLabel(smu2_peaxism3);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(40, 370, 121, 16));
        pushButton_71 = new QCAPushButton(smu2_peaxism3);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(550, 330, 31, 21));
        pushButton_53 = new QCAPushButton(smu2_peaxism3);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(550, 610, 31, 21));
        label_40 = new QLabel(smu2_peaxism3);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(880, 150, 101, 16));
        pushButton_6 = new QCAPushButton(smu2_peaxism3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(320, 120, 81, 22));
        label_84 = new QLabel(smu2_peaxism3);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(600, 590, 71, 16));
        label_73 = new QLabel(smu2_peaxism3);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(400, 310, 59, 14));
        label_65 = new QLabel(smu2_peaxism3);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(400, 550, 59, 14));
        label_70 = new QLabel(smu2_peaxism3);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(600, 490, 71, 16));
        pushButton_67 = new QCAPushButton(smu2_peaxism3);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(520, 570, 31, 21));
        label_75 = new QLabel(smu2_peaxism3);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(600, 550, 71, 16));
        pushButton_50 = new QCAPushButton(smu2_peaxism3);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(520, 590, 31, 21));
        label_44 = new QLabel(smu2_peaxism3);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(320, 20, 71, 16));
        label_45 = new QCALabel(smu2_peaxism3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(30, 40, 59, 14));
        label_69 = new QLabel(smu2_peaxism3);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(600, 530, 71, 16));
        pushButton_37 = new QCAPushButton(smu2_peaxism3);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(550, 450, 31, 21));
        pushButton_21 = new QCAPushButton(smu2_peaxism3);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(170, 370, 151, 22));
        label_42 = new QCALabel(smu2_peaxism3);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1020, 150, 91, 16));
        pushButton_58 = new QCAPushButton(smu2_peaxism3);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(470, 470, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_18 = new QLabel(smu2_peaxism3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(810, 60, 59, 14));
        label_18->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_45 = new QCAPushButton(smu2_peaxism3);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(520, 370, 31, 21));
        lcdNumber_11 = new QCALCDNumber(smu2_peaxism3);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(330, 80, 64, 23));
        label_24 = new QCALabel(smu2_peaxism3);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(1020, 130, 81, 16));
        lcdNumber_14 = new QCALCDNumber(smu2_peaxism3);
        lcdNumber_14->setObjectName(QStringLiteral("lcdNumber_14"));
        lcdNumber_14->setGeometry(QRect(440, 280, 64, 23));
        lcdNumber_14->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_14->setMode(QLCDNumber::Hex);
        lcdNumber_14->setSegmentStyle(QLCDNumber::Filled);
        pushButton_39 = new QCAPushButton(smu2_peaxism3);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(550, 470, 31, 21));
        label_64 = new QLabel(smu2_peaxism3);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(400, 530, 59, 14));
        label_76 = new QLabel(smu2_peaxism3);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(400, 570, 59, 14));
        pushButton_20 = new QCAPushButton(smu2_peaxism3);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(250, 460, 31, 31));
        pushButton_47 = new QCAPushButton(smu2_peaxism3);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(550, 550, 31, 21));
        pushButton_33 = new QCAPushButton(smu2_peaxism3);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(550, 410, 31, 21));
        pushButton_40 = new QCAPushButton(smu2_peaxism3);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(980, 480, 51, 22));
        pushButton_12 = new QCAPushButton(smu2_peaxism3);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(920, 390, 51, 22));
        ref3Axis_2 = new QCAAxis(smu2_peaxism3);
        ref3Axis_2->setObjectName(QStringLiteral("ref3Axis_2"));
        ref3Axis_2->setGeometry(QRect(710, 270, 345, 27));
        ref3Axis_2->setMinimumSize(QSize(100, 10));
        max3Axis_2 = new QCAAxis(smu2_peaxism3);
        max3Axis_2->setObjectName(QStringLiteral("max3Axis_2"));
        max3Axis_2->setGeometry(QRect(710, 330, 345, 27));
        max3Axis_2->setMinimumSize(QSize(100, 10));
        acc3Axis_2 = new QCAAxis(smu2_peaxism3);
        acc3Axis_2->setObjectName(QStringLiteral("acc3Axis_2"));
        acc3Axis_2->setGeometry(QRect(710, 360, 345, 27));
        acc3Axis_2->setMinimumSize(QSize(100, 10));
        label_32 = new QLabel(smu2_peaxism3);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(710, 400, 111, 16));
        label_37 = new QCALabel(smu2_peaxism3);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(830, 480, 59, 14));
        pushButton_14 = new QPushButton(smu2_peaxism3);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(980, 390, 51, 22));
        label_33 = new QCALabel(smu2_peaxism3);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(830, 400, 59, 14));
        label_36 = new QLabel(smu2_peaxism3);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(710, 480, 111, 16));
        pushButton_16 = new QCAPushButton(smu2_peaxism3);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(920, 480, 51, 22));
        speed3Axis_2 = new QCAAxis(smu2_peaxism3);
        speed3Axis_2->setObjectName(QStringLiteral("speed3Axis_2"));
        speed3Axis_2->setGeometry(QRect(710, 300, 345, 27));
        speed3Axis_2->setMinimumSize(QSize(100, 10));
        curr3Axis_2 = new QCAAxis(smu2_peaxism3);
        curr3Axis_2->setObjectName(QStringLiteral("curr3Axis_2"));
        curr3Axis_2->setGeometry(QRect(710, 240, 345, 27));
        curr3Axis_2->setMinimumSize(QSize(100, 10));
        sofn3Axis_2 = new QCAAxis(smu2_peaxism3);
        sofn3Axis_2->setObjectName(QStringLiteral("sofn3Axis_2"));
        sofn3Axis_2->setGeometry(QRect(710, 420, 345, 27));
        sofn3Axis_2->setMinimumSize(QSize(100, 10));
        sofp3Axis_2 = new QCAAxis(smu2_peaxism3);
        sofp3Axis_2->setObjectName(QStringLiteral("sofp3Axis_2"));
        sofp3Axis_2->setGeometry(QRect(710, 450, 345, 27));
        sofp3Axis_2->setMinimumSize(QSize(100, 10));
        Axis3 = new QCAAxis(smu2_peaxism3);
        Axis3->setObjectName(QStringLiteral("Axis3"));
        Axis3->setGeometry(QRect(40, 240, 360, 32));

        retranslateUi(smu2_peaxism3);

        QMetaObject::connectSlotsByName(smu2_peaxism3);
    } // setupUi

    void retranslateUi(QDialog *smu2_peaxism3)
    {
        smu2_peaxism3->setWindowTitle(QApplication::translate("smu2_peaxism3", "Dialog", 0));
        pushButton_18->setText(QApplication::translate("smu2_peaxism3", "LSP", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:LspM3", 0)));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_60->setText(QApplication::translate("smu2_peaxism3", "SP", 0));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSpeedM3", 0)));
        label_78->setText(QApplication::translate("smu2_peaxism3", "DIR", 0));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_55->setText(QApplication::translate("smu2_peaxism3", "SW Speed", 0));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_56->setText(QApplication::translate("smu2_peaxism3", "SW LSP", 0));
        label_80->setText(QApplication::translate("smu2_peaxism3", "Track Err", 0));
        pushButton_17->setText(QApplication::translate("smu2_peaxism3", "Lock", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:LockM3", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_5->setText(QApplication::translate("smu2_peaxism3", "LSN", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:LsnM3", 0)));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_43->setText(QApplication::translate("smu2_peaxism3", "current speed", 0));
        pushButton_13->setText(QApplication::translate("smu2_peaxism3", "REF", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:HomeM3", 0)));
        label_20->setText(QApplication::translate("smu2_peaxism3", "capture value", 0));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_74->setText(QString());
        pushButton_74->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_71->setText(QApplication::translate("smu2_peaxism3", "User Stop", 0));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_38->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdNomPosM3", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_68->setText(QString());
        pushButton_68->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_83->setText(QApplication::translate("smu2_peaxism3", "error codes", 0));
        label_41->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_41->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdPosM3", 0)));
        label_67->setText(QApplication::translate("smu2_peaxism3", "CAPT", 0));
        pushButton_73->setText(QString());
        pushButton_73->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        lcdNumber_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_61->setText(QApplication::translate("smu2_peaxism3", "70X I", 0));
        label_47->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:AbsM3", 0)));
        label_81->setText(QString());
        label_13->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdPosM3.EGU", 0)));
        pushButton_66->setText(QString());
        pushButton_66->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_72->setText(QString());
        pushButton_72->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_74->setText(QString());
        label_77->setText(QApplication::translate("smu2_peaxism3", "LSN", 0));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_25->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdCurSpeedM3", 0)));
        label_26->setText(QApplication::translate("smu2_peaxism3", "parameter set", 0));
        label_48->setText(QApplication::translate("smu2_peaxism3", "move continous", 0));
        pushButton_23->setText(QApplication::translate("smu2_peaxism3", "-", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:ContNegM3", 0)));
        label_23->setText(QApplication::translate("smu2_peaxism3", "M3", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_4->setText(QApplication::translate("smu2_peaxism3", "STOP", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:StopM3", 0)));
        label_82->setText(QApplication::translate("smu2_peaxism3", "EXT ERR", 0));
        pushButton_22->setText(QApplication::translate("smu2_peaxism3", "+", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:ContPosM3", 0)));
        label_49->setText(QApplication::translate("smu2_peaxism3", "continous mode", 0));
        pushButton_19->setText(QApplication::translate("smu2_peaxism3", "-", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:ContNegM3", 0)));
        label_58->setText(QApplication::translate("smu2_peaxism3", "RUN", 0));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_66->setText(QApplication::translate("smu2_peaxism3", "Encoder", 0));
        label_79->setText(QApplication::translate("smu2_peaxism3", "DV_ERR", 0));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_54->setText(QApplication::translate("smu2_peaxism3", "move absolute to", 0));
        label_57->setText(QApplication::translate("smu2_peaxism3", "ABS", 0));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_19->setText(QApplication::translate("smu2_peaxism3", "nominal position", 0));
        label_85->setText(QApplication::translate("smu2_peaxism3", "SW LSN", 0));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_51->setText(QApplication::translate("smu2_peaxism3", "motion commands", 0));
        label_39->setText(QApplication::translate("smu2_peaxism3", "current position", 0));
        pushButton_70->setText(QString());
        pushButton_70->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_68->setText(QApplication::translate("smu2_peaxism3", "LOCK", 0));
        label_62->setText(QApplication::translate("smu2_peaxism3", "DV_OK", 0));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_63->setText(QApplication::translate("smu2_peaxism3", "Ref Err", 0));
        label_59->setText(QApplication::translate("smu2_peaxism3", "POSA", 0));
        label_86->setText(QApplication::translate("smu2_peaxism3", "OSPD", 0));
        pushButton_69->setText(QString());
        pushButton_69->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        lcdNumber_15->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_46->setText(QApplication::translate("smu2_peaxism3", "DESC", 0));
        label_53->setText(QApplication::translate("smu2_peaxism3", "move to reference", 0));
        pushButton_71->setText(QString());
        pushButton_71->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_40->setText(QApplication::translate("smu2_peaxism3", "brake distance", 0));
        pushButton_6->setText(QApplication::translate("smu2_peaxism3", "RUN", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:RunM3", 0)));
        label_84->setText(QApplication::translate("smu2_peaxism3", "LSP", 0));
        label_73->setText(QApplication::translate("smu2_peaxism3", "ERROR", 0));
        label_65->setText(QApplication::translate("smu2_peaxism3", "LSP", 0));
        label_70->setText(QApplication::translate("smu2_peaxism3", "Powerfail", 0));
        pushButton_67->setText(QString());
        pushButton_67->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_75->setText(QApplication::translate("smu2_peaxism3", "HW Speed", 0));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        label_44->setText(QApplication::translate("smu2_peaxism3", "SMU41_2", 0));
        label_45->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:ChkAliveM3_.DESC", 0)));
        label_69->setText(QString());
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_21->setText(QApplication::translate("smu2_peaxism3", "GoRef", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:RefM3", 0)));
        label_42->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_42->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdBrakeDistM3", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        label_18->setText(QApplication::translate("smu2_peaxism3", "info set", 0));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrStateM3", 0)));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdPosM3", 0)));
        label_24->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdCaptValM3", 0)));
        lcdNumber_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdStateM3", 0)));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        label_64->setText(QApplication::translate("smu2_peaxism3", "LSN", 0));
        label_76->setText(QApplication::translate("smu2_peaxism3", "REF", 0));
        pushButton_20->setText(QApplication::translate("smu2_peaxism3", "+", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:ContPosM3", 0)));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdErrFlagM3", 0)));
        pushButton_40->setText(QApplication::translate("smu2_peaxism3", "on", 0));
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:SwLimM3", 0)));
        pushButton_12->setText(QApplication::translate("smu2_peaxism3", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:AccM3", 0)));
        ref3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "reference positic", 0)));
        ref3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdRefM3", 0)));
        ref3Axis_2->setProperty("units", QVariant(QString()));
        ref3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdRefM3", 0)));
        max3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "maximal speed", 0)));
        max3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdMaxSpeedM3", 0)));
        max3Axis_2->setProperty("units", QVariant(QString()));
        max3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdMaxSpeedM3", 0)));
        acc3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "acceleration time", 0)));
        acc3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdAccTimeM3", 0)));
        acc3Axis_2->setProperty("units", QVariant(QString()));
        acc3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdAccTimeM3", 0)));
        label_32->setText(QApplication::translate("smu2_peaxism3", "ramp shape", 0));
        label_37->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSwLimM3", 0)));
        pushButton_14->setText(QApplication::translate("smu2_peaxism3", "exp", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:AccM3", 0)));
        label_33->setText(QApplication::translate("smu2_peaxism3", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdAccM3", 0)));
        label_36->setText(QApplication::translate("smu2_peaxism3", "soft limit", 0));
        pushButton_16->setText(QApplication::translate("smu2_peaxism3", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:SwLimM3", 0)));
        speed3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "speed", 0)));
        speed3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSpeedM3", 0)));
        speed3Axis_2->setProperty("units", QVariant(QString()));
        speed3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSpeedM3", 0)));
        curr3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "current position", 0)));
        curr3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdPosM3", 0)));
        curr3Axis_2->setProperty("units", QVariant(QApplication::translate("smu2_peaxism3", "steps", 0)));
        curr3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdPosM3", 0)));
        sofn3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "soft limit negativ", 0)));
        sofn3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSwLimNegM3", 0)));
        sofn3Axis_2->setProperty("units", QVariant(QString()));
        sofn3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSwLimNegM3", 0)));
        sofp3Axis_2->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "soft limit positiv", 0)));
        sofp3Axis_2->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSwLimPosM3", 0)));
        sofp3Axis_2->setProperty("units", QVariant(QString()));
        sofp3Axis_2->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdSwLimPosM3", 0)));
        Axis3->setProperty("description", QVariant(QApplication::translate("smu2_peaxism3", "motive relative", 0)));
        Axis3->setProperty("pvReadback", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdRelM3", 0)));
        Axis3->setProperty("units", QVariant(QApplication::translate("smu2_peaxism3", "steps", 0)));
        Axis3->setProperty("pv", QVariant(QApplication::translate("smu2_peaxism3", "SMU41_2:rdRelM3", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu2_peaxism3: public Ui_smu2_peaxism3 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU2_PEAXISM3_H
