/********************************************************************************
** Form generated from reading UI file 'smu1_m4.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU1_M4_H
#define UI_SMU1_M4_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu1_m4
{
public:
    QCAPushButton *pushButton_2;
    QCALabel *label_2;
    QLabel *label_3;
    QCAPushButton *pushButton_5;
    QCAPushButton *pushButton_4;
    QCALabel *label_4;
    QCAPushButton *pushButton_6;
    QCALCDNumber *lcdNumber;
    QLabel *label;
    QCAPushButton *pushButton;
    QCAPushButton *pushButton_3;
    QLabel *label_15;
    QLabel *label_19;
    QLabel *label_14;
    QCALabel *label_24;
    QCALabel *label_25;
    QLabel *label_16;
    QCALabel *label_21;
    QLabel *label_20;
    QLabel *label_17;
    QCALabel *label_22;
    QLabel *label_18;
    QCALabel *label_23;
    QLabel *label_26;
    QCAPushButton *pushButton_34;
    QLabel *label_40;
    QLabel *label_57;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_65;
    QLabel *label_63;
    QCAPushButton *pushButton_54;
    QCAPushButton *pushButton_53;
    QCAPushButton *pushButton_64;
    QCAPushButton *pushButton_41;
    QCAPushButton *pushButton_58;
    QLabel *label_38;
    QCAPushButton *pushButton_25;
    QCAPushButton *pushButton_49;
    QCAPushButton *pushButton_24;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_19;
    QCAPushButton *pushButton_28;
    QCALCDNumber *lcdNumber_11;
    QLabel *label_41;
    QLabel *label_51;
    QCAPushButton *pushButton_35;
    QCAPushButton *pushButton_21;
    QCAPushButton *pushButton_42;
    QCAPushButton *pushButton_36;
    QLabel *label_68;
    QLabel *label_45;
    QCALCDNumber *lcdNumber_12;
    QLabel *label_39;
    QCAPushButton *pushButton_59;
    QCAPushButton *pushButton_62;
    QLabel *label_62;
    QLabel *label_66;
    QLabel *label_44;
    QCAPushButton *pushButton_63;
    QCAPushButton *pushButton_65;
    QLabel *label_48;
    QCAPushButton *pushButton_60;
    QLabel *label_61;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_44;
    QCAPushButton *pushButton_38;
    QCAPushButton *pushButton_46;
    QLabel *label_55;
    QLabel *label_43;
    QLabel *label_64;
    QLabel *label_56;
    QCAPushButton *pushButton_20;
    QLabel *label_47;
    QLabel *label_54;
    QCAPushButton *pushButton_45;
    QLabel *label_58;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_30;
    QLabel *label_46;
    QLabel *label_42;
    QLabel *label_50;
    QLabel *label_67;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_27;
    QCAPushButton *pushButton_31;
    QCAPushButton *pushButton_51;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_40;
    QCAPushButton *pushButton_48;
    QCAPushButton *pushButton_56;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_55;
    QLabel *label_49;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_32;
    QLabel *label_60;
    QCAPushButton *pushButton_47;
    QCAPushButton *pushButton_52;
    QLabel *label_59;
    QCALCDNumber *lcdNumber_13;
    QCAPushButton *pushButton_23;
    QCAPushButton *pushButton_37;
    QLabel *label_13;
    QLabel *label_12;
    QCAPushButton *pushButton_15;
    QLabel *label_11;
    QCAPushButton *pushButton_10;
    QScrollBar *horizontalScrollBar;
    QLabel *label_5;
    QLabel *label_10;
    QCALabel *label_8;
    QCAPushButton *pushButton_11;
    QCALCDNumber *lcdNumber_3;
    QCAPushButton *pushButton_14;
    QLabel *label_9;
    QCAPushButton *pushButton_7;
    QCAAxis *sofp4Axis_1;
    QCAAxis *sofn4Axis_1;
    QCAAxis *ref4Axis_1;
    QPushButton *pushButton_13;
    QCAAxis *curr4Axis_1;
    QCALabel *label_33;
    QLabel *label_32;
    QCAAxis *acc4Axis_1;
    QLabel *label_36;
    QCAAxis *max4Axis_1;
    QCAPushButton *pushButton_17;
    QCAPushButton *pushButton_16;
    QCAAxis *speed4Axis_1;
    QCAPushButton *pushButton_12;
    QCALabel *label_37;
    QCAAxis *Axis4;

    void setupUi(QDialog *smu1_m4)
    {
        if (smu1_m4->objectName().isEmpty())
            smu1_m4->setObjectName(QStringLiteral("smu1_m4"));
        smu1_m4->resize(1089, 641);
        pushButton_2 = new QCAPushButton(smu1_m4);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(170, 120, 81, 22));
        label_2 = new QCALabel(smu1_m4);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 40, 59, 14));
        label_3 = new QLabel(smu1_m4);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(360, 30, 71, 16));
        pushButton_5 = new QCAPushButton(smu1_m4);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(460, 120, 81, 22));
        pushButton_4 = new QCAPushButton(smu1_m4);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(360, 120, 81, 22));
        label_4 = new QCALabel(smu1_m4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(570, 80, 59, 14));
        pushButton_6 = new QCAPushButton(smu1_m4);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(560, 120, 81, 22));
        lcdNumber = new QCALCDNumber(smu1_m4);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(370, 80, 64, 23));
        label = new QLabel(smu1_m4);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 20, 59, 14));
        pushButton = new QCAPushButton(smu1_m4);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(50, 100, 81, 51));
        pushButton->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_3 = new QCAPushButton(smu1_m4);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(260, 120, 81, 22));
        label_15 = new QLabel(smu1_m4);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(740, 60, 59, 14));
        label_15->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_19 = new QLabel(smu1_m4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(810, 130, 91, 16));
        label_14 = new QLabel(smu1_m4);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(920, 30, 59, 14));
        label_24 = new QCALabel(smu1_m4);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(950, 130, 81, 16));
        label_25 = new QCALabel(smu1_m4);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(950, 150, 91, 16));
        label_16 = new QLabel(smu1_m4);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(810, 70, 111, 16));
        label_21 = new QCALabel(smu1_m4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(950, 70, 91, 16));
        label_20 = new QLabel(smu1_m4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(810, 150, 101, 16));
        label_17 = new QLabel(smu1_m4);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(810, 90, 111, 16));
        label_22 = new QCALabel(smu1_m4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(950, 90, 91, 16));
        label_18 = new QLabel(smu1_m4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(810, 110, 91, 16));
        label_23 = new QCALabel(smu1_m4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(950, 110, 91, 16));
        label_26 = new QLabel(smu1_m4);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(730, 200, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_34 = new QCAPushButton(smu1_m4);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(500, 420, 31, 21));
        label_40 = new QLabel(smu1_m4);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(380, 340, 59, 14));
        label_57 = new QLabel(smu1_m4);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(380, 380, 59, 14));
        label_52 = new QLabel(smu1_m4);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(580, 520, 71, 16));
        label_53 = new QLabel(smu1_m4);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(580, 540, 71, 16));
        label_65 = new QLabel(smu1_m4);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(380, 540, 59, 14));
        label_63 = new QLabel(smu1_m4);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(380, 500, 59, 14));
        pushButton_54 = new QCAPushButton(smu1_m4);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(450, 380, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        pushButton_53 = new QCAPushButton(smu1_m4);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(530, 600, 31, 21));
        pushButton_64 = new QCAPushButton(smu1_m4);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(450, 580, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        pushButton_41 = new QCAPushButton(smu1_m4);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(530, 480, 31, 21));
        pushButton_58 = new QCAPushButton(smu1_m4);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(450, 460, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_38 = new QLabel(smu1_m4);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(380, 300, 59, 14));
        pushButton_25 = new QCAPushButton(smu1_m4);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(530, 320, 31, 21));
        pushButton_49 = new QCAPushButton(smu1_m4);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(530, 560, 31, 21));
        pushButton_24 = new QCAPushButton(smu1_m4);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(500, 320, 31, 21));
        pushButton_33 = new QCAPushButton(smu1_m4);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(530, 400, 31, 21));
        pushButton_19 = new QCAPushButton(smu1_m4);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(450, 320, 31, 21));
        pushButton_19->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_28 = new QCAPushButton(smu1_m4);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(500, 360, 31, 21));
        lcdNumber_11 = new QCALCDNumber(smu1_m4);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(410, 260, 64, 23));
        lcdNumber_11->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_11->setMode(QLCDNumber::Hex);
        lcdNumber_11->setSegmentStyle(QLCDNumber::Filled);
        label_41 = new QLabel(smu1_m4);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(380, 360, 59, 14));
        label_51 = new QLabel(smu1_m4);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(580, 500, 71, 16));
        pushButton_35 = new QCAPushButton(smu1_m4);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(530, 420, 31, 21));
        pushButton_21 = new QCAPushButton(smu1_m4);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(530, 300, 31, 21));
        pushButton_42 = new QCAPushButton(smu1_m4);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(500, 500, 31, 21));
        pushButton_36 = new QCAPushButton(smu1_m4);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(500, 440, 31, 21));
        label_68 = new QLabel(smu1_m4);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(380, 600, 59, 14));
        label_45 = new QLabel(smu1_m4);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(580, 380, 71, 16));
        lcdNumber_12 = new QCALCDNumber(smu1_m4);
        lcdNumber_12->setObjectName(QStringLiteral("lcdNumber_12"));
        lcdNumber_12->setGeometry(QRect(490, 230, 64, 23));
        lcdNumber_12->setMode(QLCDNumber::Hex);
        label_39 = new QLabel(smu1_m4);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(580, 300, 71, 16));
        pushButton_59 = new QCAPushButton(smu1_m4);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(450, 480, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_62 = new QCAPushButton(smu1_m4);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(450, 540, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_62 = new QLabel(smu1_m4);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(380, 480, 59, 14));
        label_66 = new QLabel(smu1_m4);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(380, 560, 59, 14));
        label_44 = new QLabel(smu1_m4);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(580, 360, 71, 16));
        pushButton_63 = new QCAPushButton(smu1_m4);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(450, 560, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_65 = new QCAPushButton(smu1_m4);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(450, 600, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        label_48 = new QLabel(smu1_m4);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(580, 440, 71, 16));
        pushButton_60 = new QCAPushButton(smu1_m4);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(450, 500, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        label_61 = new QLabel(smu1_m4);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(380, 460, 59, 14));
        pushButton_43 = new QCAPushButton(smu1_m4);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(530, 500, 31, 21));
        pushButton_44 = new QCAPushButton(smu1_m4);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(500, 520, 31, 21));
        pushButton_38 = new QCAPushButton(smu1_m4);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(500, 460, 31, 21));
        pushButton_46 = new QCAPushButton(smu1_m4);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(500, 540, 31, 21));
        label_55 = new QLabel(smu1_m4);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(580, 580, 71, 16));
        label_43 = new QLabel(smu1_m4);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(580, 340, 71, 16));
        label_64 = new QLabel(smu1_m4);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(380, 520, 59, 14));
        label_56 = new QLabel(smu1_m4);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(580, 600, 71, 16));
        pushButton_20 = new QCAPushButton(smu1_m4);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(500, 300, 31, 21));
        label_47 = new QLabel(smu1_m4);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(580, 420, 71, 16));
        label_54 = new QLabel(smu1_m4);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(580, 560, 71, 16));
        pushButton_45 = new QCAPushButton(smu1_m4);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(530, 520, 31, 21));
        label_58 = new QLabel(smu1_m4);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(380, 400, 59, 14));
        pushButton_22 = new QCAPushButton(smu1_m4);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(450, 340, 31, 21));
        pushButton_22->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_30 = new QCAPushButton(smu1_m4);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(500, 380, 31, 21));
        label_46 = new QLabel(smu1_m4);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(580, 400, 71, 16));
        label_42 = new QLabel(smu1_m4);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(580, 320, 71, 16));
        label_50 = new QLabel(smu1_m4);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(580, 480, 71, 16));
        label_67 = new QLabel(smu1_m4);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(380, 580, 59, 14));
        pushButton_26 = new QCAPushButton(smu1_m4);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(500, 340, 31, 21));
        pushButton_27 = new QCAPushButton(smu1_m4);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(530, 340, 31, 21));
        pushButton_31 = new QCAPushButton(smu1_m4);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(530, 380, 31, 21));
        pushButton_51 = new QCAPushButton(smu1_m4);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(530, 580, 31, 21));
        pushButton_29 = new QCAPushButton(smu1_m4);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(530, 360, 31, 21));
        pushButton_18 = new QCAPushButton(smu1_m4);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(450, 300, 31, 21));
        pushButton_40 = new QCAPushButton(smu1_m4);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(500, 480, 31, 21));
        pushButton_48 = new QCAPushButton(smu1_m4);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(500, 560, 31, 21));
        pushButton_56 = new QCAPushButton(smu1_m4);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(450, 420, 31, 21));
        pushButton_56->setStyleSheet(QStringLiteral(""));
        pushButton_61 = new QCAPushButton(smu1_m4);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(450, 520, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_57 = new QCAPushButton(smu1_m4);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(450, 440, 31, 21));
        pushButton_57->setStyleSheet(QStringLiteral(""));
        pushButton_55 = new QCAPushButton(smu1_m4);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(450, 400, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        label_49 = new QLabel(smu1_m4);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(580, 460, 71, 16));
        pushButton_39 = new QCAPushButton(smu1_m4);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(530, 460, 31, 21));
        pushButton_50 = new QCAPushButton(smu1_m4);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(500, 580, 31, 21));
        pushButton_32 = new QCAPushButton(smu1_m4);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(500, 400, 31, 21));
        label_60 = new QLabel(smu1_m4);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(380, 440, 59, 14));
        pushButton_47 = new QCAPushButton(smu1_m4);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(530, 540, 31, 21));
        pushButton_52 = new QCAPushButton(smu1_m4);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(500, 600, 31, 21));
        label_59 = new QLabel(smu1_m4);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(380, 420, 59, 14));
        lcdNumber_13 = new QCALCDNumber(smu1_m4);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(490, 260, 64, 23));
        lcdNumber_13->setStyleSheet(QStringLiteral(""));
        lcdNumber_13->setMode(QLCDNumber::Hex);
        pushButton_23 = new QCAPushButton(smu1_m4);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(450, 360, 31, 21));
        pushButton_23->setStyleSheet(QStringLiteral(""));
        pushButton_37 = new QCAPushButton(smu1_m4);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(530, 440, 31, 21));
        label_13 = new QLabel(smu1_m4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(420, 200, 81, 16));
        label_13->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_12 = new QLabel(smu1_m4);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(110, 400, 111, 16));
        pushButton_15 = new QCAPushButton(smu1_m4);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(240, 440, 31, 31));
        label_11 = new QLabel(smu1_m4);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 350, 121, 16));
        pushButton_10 = new QCAPushButton(smu1_m4);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(250, 320, 61, 22));
        horizontalScrollBar = new QScrollBar(smu1_m4);
        horizontalScrollBar->setObjectName(QStringLiteral("horizontalScrollBar"));
        horizontalScrollBar->setGeometry(QRect(80, 450, 151, 16));
        horizontalScrollBar->setOrientation(Qt::Horizontal);
        label_5 = new QLabel(smu1_m4);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 200, 121, 16));
        label_5->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_10 = new QLabel(smu1_m4);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 320, 111, 16));
        label_8 = new QCALabel(smu1_m4);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(190, 280, 101, 16));
        pushButton_11 = new QCAPushButton(smu1_m4);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(160, 350, 151, 22));
        lcdNumber_3 = new QCALCDNumber(smu1_m4);
        lcdNumber_3->setObjectName(QStringLiteral("lcdNumber_3"));
        lcdNumber_3->setGeometry(QRect(130, 420, 64, 23));
        pushButton_14 = new QCAPushButton(smu1_m4);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(40, 440, 31, 31));
        label_9 = new QLabel(smu1_m4);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 280, 111, 16));
        pushButton_7 = new QCAPushButton(smu1_m4);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(160, 320, 61, 22));
        sofp4Axis_1 = new QCAAxis(smu1_m4);
        sofp4Axis_1->setObjectName(QStringLiteral("sofp4Axis_1"));
        sofp4Axis_1->setGeometry(QRect(700, 440, 345, 27));
        sofp4Axis_1->setMinimumSize(QSize(100, 10));
        sofn4Axis_1 = new QCAAxis(smu1_m4);
        sofn4Axis_1->setObjectName(QStringLiteral("sofn4Axis_1"));
        sofn4Axis_1->setGeometry(QRect(700, 410, 345, 27));
        sofn4Axis_1->setMinimumSize(QSize(100, 10));
        ref4Axis_1 = new QCAAxis(smu1_m4);
        ref4Axis_1->setObjectName(QStringLiteral("ref4Axis_1"));
        ref4Axis_1->setGeometry(QRect(700, 260, 345, 27));
        ref4Axis_1->setMinimumSize(QSize(100, 10));
        pushButton_13 = new QPushButton(smu1_m4);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(970, 380, 51, 22));
        curr4Axis_1 = new QCAAxis(smu1_m4);
        curr4Axis_1->setObjectName(QStringLiteral("curr4Axis_1"));
        curr4Axis_1->setGeometry(QRect(700, 230, 345, 27));
        curr4Axis_1->setMinimumSize(QSize(100, 10));
        label_33 = new QCALabel(smu1_m4);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(820, 390, 59, 14));
        label_32 = new QLabel(smu1_m4);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(700, 390, 111, 16));
        acc4Axis_1 = new QCAAxis(smu1_m4);
        acc4Axis_1->setObjectName(QStringLiteral("acc4Axis_1"));
        acc4Axis_1->setGeometry(QRect(700, 350, 345, 27));
        acc4Axis_1->setMinimumSize(QSize(100, 10));
        label_36 = new QLabel(smu1_m4);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(700, 470, 111, 16));
        max4Axis_1 = new QCAAxis(smu1_m4);
        max4Axis_1->setObjectName(QStringLiteral("max4Axis_1"));
        max4Axis_1->setGeometry(QRect(700, 320, 345, 27));
        max4Axis_1->setMinimumSize(QSize(100, 10));
        pushButton_17 = new QCAPushButton(smu1_m4);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(970, 470, 51, 22));
        pushButton_16 = new QCAPushButton(smu1_m4);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(910, 470, 51, 22));
        speed4Axis_1 = new QCAAxis(smu1_m4);
        speed4Axis_1->setObjectName(QStringLiteral("speed4Axis_1"));
        speed4Axis_1->setGeometry(QRect(700, 290, 345, 27));
        speed4Axis_1->setMinimumSize(QSize(100, 10));
        pushButton_12 = new QCAPushButton(smu1_m4);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(910, 380, 51, 22));
        label_37 = new QCALabel(smu1_m4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(820, 470, 59, 14));
        Axis4 = new QCAAxis(smu1_m4);
        Axis4->setObjectName(QStringLiteral("Axis4"));
        Axis4->setGeometry(QRect(30, 220, 360, 32));

        retranslateUi(smu1_m4);

        QMetaObject::connectSlotsByName(smu1_m4);
    } // setupUi

    void retranslateUi(QDialog *smu1_m4)
    {
        smu1_m4->setWindowTitle(QApplication::translate("smu1_m4", "Dialog", 0));
        pushButton_2->setText(QApplication::translate("smu1_m4", "LSN", 0));
        pushButton_2->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:LsnM4", 0)));
        label_2->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_2->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:ChkAliveM4_.DESC", 0)));
        label_3->setText(QApplication::translate("smu1_m4", "SMU41_1", 0));
        pushButton_5->setText(QApplication::translate("smu1_m4", "Lock", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:LockM4", 0)));
        pushButton_4->setText(QApplication::translate("smu1_m4", "RUN", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:RunM4", 0)));
        label_4->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_4->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdPosM4.EGU", 0)));
        pushButton_6->setText(QApplication::translate("smu1_m4", "LSP", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:LspM4", 0)));
        lcdNumber->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdPosM4", 0)));
        label->setText(QApplication::translate("smu1_m4", "DESC", 0));
        pushButton->setText(QApplication::translate("smu1_m4", "STOP", 0));
        pushButton->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:StopM4", 0)));
        pushButton_3->setText(QApplication::translate("smu1_m4", "REF", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:HomeM4", 0)));
        label_15->setText(QApplication::translate("smu1_m4", "info set", 0));
        label_19->setText(QApplication::translate("smu1_m4", "capture value", 0));
        label_14->setText(QApplication::translate("smu1_m4", "M4", 0));
        label_24->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdCaptValM4", 0)));
        label_25->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdBrakeDistM4", 0)));
        label_16->setText(QApplication::translate("smu1_m4", "current position", 0));
        label_21->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_21->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdPosM4", 0)));
        label_20->setText(QApplication::translate("smu1_m4", "brake distance", 0));
        label_17->setText(QApplication::translate("smu1_m4", "nominal position", 0));
        label_22->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdNomPosM4", 0)));
        label_18->setText(QApplication::translate("smu1_m4", "current speed", 0));
        label_23->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdCurSpeedM4", 0)));
        label_26->setText(QApplication::translate("smu1_m4", "parameter set", 0));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_40->setText(QApplication::translate("smu1_m4", "DIR", 0));
        label_57->setText(QApplication::translate("smu1_m4", "ABS", 0));
        label_52->setText(QString());
        label_53->setText(QApplication::translate("smu1_m4", "HW Speed", 0));
        label_65->setText(QApplication::translate("smu1_m4", "LSP", 0));
        label_63->setText(QApplication::translate("smu1_m4", "ABS", 0));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_38->setText(QApplication::translate("smu1_m4", "ERROR", 0));
        pushButton_25->setText(QString());
        pushButton_25->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_24->setText(QString());
        pushButton_24->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_19->setText(QString());
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_41->setText(QApplication::translate("smu1_m4", "RUN", 0));
        label_51->setText(QApplication::translate("smu1_m4", "Encoder", 0));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_21->setText(QString());
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        label_68->setText(QApplication::translate("smu1_m4", "LOCK", 0));
        label_45->setText(QApplication::translate("smu1_m4", "SW Speed", 0));
        lcdNumber_12->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_39->setText(QApplication::translate("smu1_m4", "User Stop", 0));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_62->setText(QApplication::translate("smu1_m4", "DV_OK", 0));
        label_66->setText(QApplication::translate("smu1_m4", "REF", 0));
        label_44->setText(QApplication::translate("smu1_m4", "Track Err", 0));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_48->setText(QApplication::translate("smu1_m4", "SW LSN", 0));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_61->setText(QApplication::translate("smu1_m4", "70X I", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_55->setText(QApplication::translate("smu1_m4", "LSP", 0));
        label_43->setText(QApplication::translate("smu1_m4", "Ref Err", 0));
        label_64->setText(QApplication::translate("smu1_m4", "LSN", 0));
        label_56->setText(QApplication::translate("smu1_m4", "LSN", 0));
        pushButton_20->setText(QString());
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        label_47->setText(QApplication::translate("smu1_m4", "SW LSP", 0));
        label_54->setText(QApplication::translate("smu1_m4", "DV_ERR", 0));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        label_58->setText(QApplication::translate("smu1_m4", "OSPD", 0));
        pushButton_22->setText(QString());
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_46->setText(QApplication::translate("smu1_m4", "EXT ERR", 0));
        label_42->setText(QApplication::translate("smu1_m4", "POSA", 0));
        label_50->setText(QApplication::translate("smu1_m4", "Powerfail", 0));
        label_67->setText(QApplication::translate("smu1_m4", "CAPT", 0));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_18->setText(QString());
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_40->setText(QString());
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        label_49->setText(QString());
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_60->setText(QApplication::translate("smu1_m4", "SP", 0));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrStateM4", 0)));
        label_59->setText(QString());
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        pushButton_23->setText(QString());
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdStateM4", 0)));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdErrFlagM4", 0)));
        label_13->setText(QApplication::translate("smu1_m4", "error codes", 0));
        label_12->setText(QApplication::translate("smu1_m4", "continous mode", 0));
        pushButton_15->setText(QApplication::translate("smu1_m4", "+", 0));
        pushButton_15->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:ContPosM4", 0)));
        label_11->setText(QApplication::translate("smu1_m4", "move to reference", 0));
        pushButton_10->setText(QApplication::translate("smu1_m4", "+", 0));
        pushButton_10->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:ContPosM4", 0)));
        label_5->setText(QApplication::translate("smu1_m4", "motion commands", 0));
        label_10->setText(QApplication::translate("smu1_m4", "move continous", 0));
        label_8->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_8->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:AbsM4", 0)));
        pushButton_11->setText(QApplication::translate("smu1_m4", "GoRef", 0));
        pushButton_11->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:RefM4", 0)));
        lcdNumber_3->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSpeedM4", 0)));
        pushButton_14->setText(QApplication::translate("smu1_m4", "-", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:ContNegM4", 0)));
        label_9->setText(QApplication::translate("smu1_m4", "move absolute to", 0));
        pushButton_7->setText(QApplication::translate("smu1_m4", "-", 0));
        pushButton_7->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:ContNegM4", 0)));
        sofp4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "soft limit positiv", 0)));
        sofp4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSwLimPosM4", 0)));
        sofp4Axis_1->setProperty("units", QVariant(QString()));
        sofp4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSwLimPosM4", 0)));
        sofn4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "soft limit negativ", 0)));
        sofn4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSwLimNegM4", 0)));
        sofn4Axis_1->setProperty("units", QVariant(QString()));
        sofn4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSwLimNegM4", 0)));
        ref4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "reference positic", 0)));
        ref4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdRefM4", 0)));
        ref4Axis_1->setProperty("units", QVariant(QString()));
        ref4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdRefM4", 0)));
        pushButton_13->setText(QApplication::translate("smu1_m4", "exp", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:AccM4", 0)));
        curr4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "current position", 0)));
        curr4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdPosM4", 0)));
        curr4Axis_1->setProperty("units", QVariant(QApplication::translate("smu1_m4", "steps", 0)));
        curr4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdPosM4", 0)));
        label_33->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdAccM4", 0)));
        label_32->setText(QApplication::translate("smu1_m4", "ramp shape", 0));
        acc4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "acceleration time", 0)));
        acc4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdAccTimeM4", 0)));
        acc4Axis_1->setProperty("units", QVariant(QString()));
        acc4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdAccTimeM4", 0)));
        label_36->setText(QApplication::translate("smu1_m4", "soft limit", 0));
        max4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "maximal speed", 0)));
        max4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdMaxSpeedM4", 0)));
        max4Axis_1->setProperty("units", QVariant(QString()));
        max4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdMaxSpeedM4", 0)));
        pushButton_17->setText(QApplication::translate("smu1_m4", "on", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:SwLimM4", 0)));
        pushButton_16->setText(QApplication::translate("smu1_m4", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:SwLimM4", 0)));
        speed4Axis_1->setProperty("description", QVariant(QApplication::translate("smu1_m4", "speed", 0)));
        speed4Axis_1->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSpeedM4", 0)));
        speed4Axis_1->setProperty("units", QVariant(QString()));
        speed4Axis_1->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSpeedM4", 0)));
        pushButton_12->setText(QApplication::translate("smu1_m4", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:AccM4", 0)));
        label_37->setText(QApplication::translate("smu1_m4", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdSwLimM4", 0)));
        Axis4->setProperty("description", QVariant(QApplication::translate("smu1_m4", "move relative", 0)));
        Axis4->setProperty("pvReadback", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdRelM4", 0)));
        Axis4->setProperty("units", QVariant(QApplication::translate("smu1_m4", "steps", 0)));
        Axis4->setProperty("pv", QVariant(QApplication::translate("smu1_m4", "SMU41_1:rdRelM4", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu1_m4: public Ui_smu1_m4 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU1_M4_H
