/********************************************************************************
** Form generated from reading UI file 'smu1_pgm1m9.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU1_PGM1M9_H
#define UI_SMU1_PGM1M9_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu1_pgm1m9
{
public:
    QCAPushButton *pushButton_51;
    QCALabel *label_25;
    QLabel *label_49;
    QLabel *label_42;
    QLabel *label_17;
    QCAPushButton *pushButton_63;
    QCAPushButton *pushButton_47;
    QLabel *label_54;
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_59;
    QCAPushButton *pushButton_20;
    QLabel *label;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_2;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_27;
    QCALCDNumber *lcdNumber_12;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_49;
    QLabel *label_50;
    QCAPushButton *pushButton_53;
    QCAPushButton *pushButton_30;
    QCAPushButton *pushButton_19;
    QLabel *label_41;
    QCAPushButton *pushButton_4;
    QLabel *label_38;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_11;
    QCAPushButton *pushButton_34;
    QLabel *label_55;
    QCAPushButton *pushButton_38;
    QCAPushButton *pushButton_15;
    QCAPushButton *pushButton_54;
    QLabel *label_39;
    QLabel *label_60;
    QCALabel *label_24;
    QCAPushButton *pushButton_25;
    QLabel *label_46;
    QLabel *label_59;
    QCALabel *label_23;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_23;
    QCAPushButton *pushButton_62;
    QCAPushButton *pushButton_6;
    QLabel *label_62;
    QCALabel *label_2;
    QLabel *label_15;
    QLabel *label_18;
    QCAPushButton *pushButton_36;
    QLabel *label_26;
    QLabel *label_20;
    QCALCDNumber *lcdNumber_13;
    QLabel *label_68;
    QCAPushButton *pushButton;
    QLabel *label_63;
    QCAPushButton *pushButton_5;
    QCAPushButton *pushButton_65;
    QCAPushButton *pushButton_44;
    QCAPushButton *pushButton_24;
    QCALabel *label_6;
    QLabel *label_9;
    QCALabel *label_8;
    QCALabel *label_4;
    QLabel *label_51;
    QCALCDNumber *lcdNumber_3;
    QCAPushButton *pushButton_46;
    QCAPushButton *pushButton_3;
    QLabel *label_40;
    QLabel *label_58;
    QCAPushButton *pushButton_37;
    QLabel *label_19;
    QLabel *label_5;
    QLabel *label_48;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_58;
    QLabel *label_12;
    QLabel *label_10;
    QLabel *label_67;
    QCAPushButton *pushButton_31;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_21;
    QLabel *label_47;
    QCALabel *label_22;
    QCAPushButton *pushButton_7;
    QCAPushButton *pushButton_52;
    QLabel *label_13;
    QLabel *label_45;
    QLabel *label_43;
    QCAPushButton *pushButton_48;
    QLabel *label_56;
    QCAPushButton *pushButton_28;
    QLabel *label_16;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_41;
    QCALCDNumber *lcdNumber_11;
    QCAPushButton *pushButton_42;
    QLabel *label_11;
    QCAPushButton *pushButton_56;
    QCAPushButton *pushButton_14;
    QLabel *label_61;
    QCAPushButton *pushButton_40;
    QCAPushButton *pushButton_35;
    QLabel *label_65;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_33;
    QCALCDNumber *lcdNumber;
    QCAPushButton *pushButton_10;
    QLabel *label_3;
    QLabel *label_14;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_64;
    QCAPushButton *pushButton_60;
    QLabel *label_64;
    QScrollBar *horizontalScrollBar;
    QCALabel *label_21;
    QLabel *label_52;
    QCAPushButton *pushButton_45;
    QLabel *label_57;
    QLabel *label_66;
    QLabel *label_53;
    QLabel *label_44;
    QCALabel *label_37;
    QCAAxis *speed9Axis;
    QPushButton *pushButton_13;
    QLabel *label_36;
    QLabel *label_32;
    QCAPushButton *pushButton_12;
    QCAAxis *sofn9Axis;
    QCAPushButton *pushButton_16;
    QCAAxis *ref9Axis;
    QCALabel *label_33;
    QCAAxis *curr9Axis;
    QCAAxis *acc9Axis;
    QCAPushButton *pushButton_17;
    QCAAxis *max9Axis;
    QCAAxis *sofp9Axis;
    QCAAxis *Axis9;

    void setupUi(QDialog *smu1_pgm1m9)
    {
        if (smu1_pgm1m9->objectName().isEmpty())
            smu1_pgm1m9->setObjectName(QStringLiteral("smu1_pgm1m9"));
        smu1_pgm1m9->resize(1051, 632);
        pushButton_51 = new QCAPushButton(smu1_pgm1m9);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(520, 580, 31, 21));
        label_25 = new QCALabel(smu1_pgm1m9);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(910, 150, 91, 16));
        label_49 = new QLabel(smu1_pgm1m9);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(570, 460, 71, 16));
        label_42 = new QLabel(smu1_pgm1m9);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(570, 320, 71, 16));
        label_17 = new QLabel(smu1_pgm1m9);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(770, 90, 111, 16));
        pushButton_63 = new QCAPushButton(smu1_pgm1m9);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(440, 560, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral(""));
        pushButton_47 = new QCAPushButton(smu1_pgm1m9);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(520, 540, 31, 21));
        label_54 = new QLabel(smu1_pgm1m9);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(570, 560, 71, 16));
        pushButton_18 = new QCAPushButton(smu1_pgm1m9);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(440, 300, 31, 21));
        pushButton_59 = new QCAPushButton(smu1_pgm1m9);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(440, 480, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral(""));
        pushButton_20 = new QCAPushButton(smu1_pgm1m9);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(490, 300, 31, 21));
        label = new QLabel(smu1_pgm1m9);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 20, 59, 14));
        pushButton_55 = new QCAPushButton(smu1_pgm1m9);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(440, 400, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_2 = new QCAPushButton(smu1_pgm1m9);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(170, 120, 81, 22));
        pushButton_2->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        pushButton_32 = new QCAPushButton(smu1_pgm1m9);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(490, 400, 31, 21));
        pushButton_27 = new QCAPushButton(smu1_pgm1m9);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(520, 340, 31, 21));
        lcdNumber_12 = new QCALCDNumber(smu1_pgm1m9);
        lcdNumber_12->setObjectName(QStringLiteral("lcdNumber_12"));
        lcdNumber_12->setGeometry(QRect(490, 230, 64, 23));
        lcdNumber_12->setMode(QLCDNumber::Hex);
        pushButton_26 = new QCAPushButton(smu1_pgm1m9);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(490, 340, 31, 21));
        pushButton_49 = new QCAPushButton(smu1_pgm1m9);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(520, 560, 31, 21));
        label_50 = new QLabel(smu1_pgm1m9);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(570, 480, 71, 16));
        pushButton_53 = new QCAPushButton(smu1_pgm1m9);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(520, 600, 31, 21));
        pushButton_30 = new QCAPushButton(smu1_pgm1m9);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(490, 380, 31, 21));
        pushButton_19 = new QCAPushButton(smu1_pgm1m9);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(440, 320, 31, 21));
        pushButton_19->setStyleSheet(QStringLiteral(""));
        label_41 = new QLabel(smu1_pgm1m9);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(370, 360, 59, 14));
        pushButton_4 = new QCAPushButton(smu1_pgm1m9);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(360, 120, 81, 22));
        label_38 = new QLabel(smu1_pgm1m9);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(370, 300, 59, 14));
        pushButton_39 = new QCAPushButton(smu1_pgm1m9);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(520, 460, 31, 21));
        pushButton_11 = new QCAPushButton(smu1_pgm1m9);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(150, 350, 151, 22));
        pushButton_34 = new QCAPushButton(smu1_pgm1m9);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(490, 420, 31, 21));
        label_55 = new QLabel(smu1_pgm1m9);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(570, 580, 71, 16));
        pushButton_38 = new QCAPushButton(smu1_pgm1m9);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(490, 460, 31, 21));
        pushButton_15 = new QCAPushButton(smu1_pgm1m9);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(230, 440, 31, 31));
        pushButton_54 = new QCAPushButton(smu1_pgm1m9);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(440, 380, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        label_39 = new QLabel(smu1_pgm1m9);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(570, 300, 71, 16));
        label_60 = new QLabel(smu1_pgm1m9);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(370, 440, 59, 14));
        label_24 = new QCALabel(smu1_pgm1m9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(910, 130, 81, 16));
        pushButton_25 = new QCAPushButton(smu1_pgm1m9);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(520, 320, 31, 21));
        label_46 = new QLabel(smu1_pgm1m9);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(570, 400, 71, 16));
        label_59 = new QLabel(smu1_pgm1m9);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(370, 420, 59, 14));
        label_23 = new QCALabel(smu1_pgm1m9);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(910, 110, 91, 16));
        pushButton_22 = new QCAPushButton(smu1_pgm1m9);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(440, 340, 31, 21));
        pushButton_22->setStyleSheet(QStringLiteral(""));
        pushButton_23 = new QCAPushButton(smu1_pgm1m9);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(440, 360, 31, 21));
        pushButton_23->setStyleSheet(QStringLiteral(""));
        pushButton_62 = new QCAPushButton(smu1_pgm1m9);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(440, 540, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral(""));
        pushButton_6 = new QCAPushButton(smu1_pgm1m9);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(560, 120, 81, 22));
        pushButton_6->setStyleSheet(QStringLiteral("background-color: rgb(255, 0, 0);"));
        label_62 = new QLabel(smu1_pgm1m9);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(370, 480, 59, 14));
        label_2 = new QCALabel(smu1_pgm1m9);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 40, 59, 14));
        label_15 = new QLabel(smu1_pgm1m9);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(700, 60, 59, 14));
        label_15->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_18 = new QLabel(smu1_pgm1m9);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(770, 110, 91, 16));
        pushButton_36 = new QCAPushButton(smu1_pgm1m9);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(490, 440, 31, 21));
        label_26 = new QLabel(smu1_pgm1m9);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(690, 200, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_20 = new QLabel(smu1_pgm1m9);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(770, 150, 101, 16));
        lcdNumber_13 = new QCALCDNumber(smu1_pgm1m9);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(490, 260, 64, 23));
        lcdNumber_13->setStyleSheet(QStringLiteral(""));
        lcdNumber_13->setMode(QLCDNumber::Hex);
        label_68 = new QLabel(smu1_pgm1m9);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(370, 600, 59, 14));
        pushButton = new QCAPushButton(smu1_pgm1m9);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(50, 100, 81, 51));
        pushButton->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        label_63 = new QLabel(smu1_pgm1m9);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(370, 500, 59, 14));
        pushButton_5 = new QCAPushButton(smu1_pgm1m9);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(460, 120, 81, 22));
        pushButton_65 = new QCAPushButton(smu1_pgm1m9);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(440, 600, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        pushButton_44 = new QCAPushButton(smu1_pgm1m9);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(490, 520, 31, 21));
        pushButton_24 = new QCAPushButton(smu1_pgm1m9);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(490, 320, 31, 21));
        label_6 = new QCALabel(smu1_pgm1m9);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(940, 10, 191, 16));
        label_6->setStyleSheet(QStringLiteral("color: rgb(170, 0, 0);"));
        label_9 = new QLabel(smu1_pgm1m9);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 280, 111, 16));
        label_8 = new QCALabel(smu1_pgm1m9);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(180, 280, 101, 16));
        label_4 = new QCALabel(smu1_pgm1m9);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(570, 80, 59, 14));
        label_51 = new QLabel(smu1_pgm1m9);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(570, 500, 71, 16));
        lcdNumber_3 = new QCALCDNumber(smu1_pgm1m9);
        lcdNumber_3->setObjectName(QStringLiteral("lcdNumber_3"));
        lcdNumber_3->setGeometry(QRect(120, 420, 64, 23));
        pushButton_46 = new QCAPushButton(smu1_pgm1m9);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(490, 540, 31, 21));
        pushButton_3 = new QCAPushButton(smu1_pgm1m9);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(260, 120, 81, 22));
        pushButton_3->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_40 = new QLabel(smu1_pgm1m9);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(370, 340, 59, 14));
        label_58 = new QLabel(smu1_pgm1m9);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(370, 400, 59, 14));
        pushButton_37 = new QCAPushButton(smu1_pgm1m9);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(520, 440, 31, 21));
        label_19 = new QLabel(smu1_pgm1m9);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(770, 130, 91, 16));
        label_5 = new QLabel(smu1_pgm1m9);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 200, 121, 16));
        label_5->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_48 = new QLabel(smu1_pgm1m9);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(570, 440, 71, 16));
        pushButton_50 = new QCAPushButton(smu1_pgm1m9);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(490, 580, 31, 21));
        pushButton_58 = new QCAPushButton(smu1_pgm1m9);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(440, 460, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral(""));
        label_12 = new QLabel(smu1_pgm1m9);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(100, 400, 111, 16));
        label_10 = new QLabel(smu1_pgm1m9);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(20, 320, 111, 16));
        label_67 = new QLabel(smu1_pgm1m9);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(370, 580, 59, 14));
        pushButton_31 = new QCAPushButton(smu1_pgm1m9);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(520, 380, 31, 21));
        pushButton_61 = new QCAPushButton(smu1_pgm1m9);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(440, 520, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral(""));
        pushButton_21 = new QCAPushButton(smu1_pgm1m9);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(520, 300, 31, 21));
        label_47 = new QLabel(smu1_pgm1m9);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(570, 420, 71, 16));
        label_22 = new QCALabel(smu1_pgm1m9);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(910, 90, 91, 16));
        pushButton_7 = new QCAPushButton(smu1_pgm1m9);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(150, 320, 61, 22));
        pushButton_52 = new QCAPushButton(smu1_pgm1m9);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(490, 600, 31, 21));
        label_13 = new QLabel(smu1_pgm1m9);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(410, 200, 81, 16));
        label_13->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_45 = new QLabel(smu1_pgm1m9);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(570, 380, 71, 16));
        label_43 = new QLabel(smu1_pgm1m9);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(570, 340, 71, 16));
        pushButton_48 = new QCAPushButton(smu1_pgm1m9);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(490, 560, 31, 21));
        label_56 = new QLabel(smu1_pgm1m9);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(570, 600, 71, 16));
        pushButton_28 = new QCAPushButton(smu1_pgm1m9);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(490, 360, 31, 21));
        label_16 = new QLabel(smu1_pgm1m9);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(770, 70, 111, 16));
        pushButton_57 = new QCAPushButton(smu1_pgm1m9);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(440, 440, 31, 21));
        pushButton_57->setStyleSheet(QStringLiteral(""));
        pushButton_41 = new QCAPushButton(smu1_pgm1m9);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(520, 480, 31, 21));
        lcdNumber_11 = new QCALCDNumber(smu1_pgm1m9);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(410, 260, 64, 23));
        lcdNumber_11->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_11->setMode(QLCDNumber::Hex);
        lcdNumber_11->setSegmentStyle(QLCDNumber::Filled);
        pushButton_42 = new QCAPushButton(smu1_pgm1m9);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(490, 500, 31, 21));
        label_11 = new QLabel(smu1_pgm1m9);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 350, 121, 16));
        pushButton_56 = new QCAPushButton(smu1_pgm1m9);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(440, 420, 31, 21));
        pushButton_56->setStyleSheet(QStringLiteral(""));
        pushButton_14 = new QCAPushButton(smu1_pgm1m9);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(30, 440, 31, 31));
        label_61 = new QLabel(smu1_pgm1m9);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(370, 460, 59, 14));
        pushButton_40 = new QCAPushButton(smu1_pgm1m9);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(490, 480, 31, 21));
        pushButton_35 = new QCAPushButton(smu1_pgm1m9);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(520, 420, 31, 21));
        label_65 = new QLabel(smu1_pgm1m9);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(370, 540, 59, 14));
        pushButton_29 = new QCAPushButton(smu1_pgm1m9);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(520, 360, 31, 21));
        pushButton_33 = new QCAPushButton(smu1_pgm1m9);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(520, 400, 31, 21));
        lcdNumber = new QCALCDNumber(smu1_pgm1m9);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(370, 80, 64, 23));
        pushButton_10 = new QCAPushButton(smu1_pgm1m9);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(240, 320, 61, 22));
        label_3 = new QLabel(smu1_pgm1m9);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(360, 30, 71, 16));
        label_14 = new QLabel(smu1_pgm1m9);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(880, 30, 59, 14));
        pushButton_43 = new QCAPushButton(smu1_pgm1m9);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(520, 500, 31, 21));
        pushButton_64 = new QCAPushButton(smu1_pgm1m9);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(440, 580, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        pushButton_60 = new QCAPushButton(smu1_pgm1m9);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(440, 500, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        label_64 = new QLabel(smu1_pgm1m9);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(370, 520, 59, 14));
        horizontalScrollBar = new QScrollBar(smu1_pgm1m9);
        horizontalScrollBar->setObjectName(QStringLiteral("horizontalScrollBar"));
        horizontalScrollBar->setGeometry(QRect(70, 450, 151, 16));
        horizontalScrollBar->setOrientation(Qt::Horizontal);
        label_21 = new QCALabel(smu1_pgm1m9);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(910, 70, 91, 16));
        label_52 = new QLabel(smu1_pgm1m9);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(570, 520, 71, 16));
        pushButton_45 = new QCAPushButton(smu1_pgm1m9);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(520, 520, 31, 21));
        label_57 = new QLabel(smu1_pgm1m9);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(370, 380, 59, 14));
        label_66 = new QLabel(smu1_pgm1m9);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(370, 560, 59, 14));
        label_53 = new QLabel(smu1_pgm1m9);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(570, 540, 71, 16));
        label_44 = new QLabel(smu1_pgm1m9);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(570, 360, 71, 16));
        label_37 = new QCALabel(smu1_pgm1m9);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(790, 470, 59, 14));
        speed9Axis = new QCAAxis(smu1_pgm1m9);
        speed9Axis->setObjectName(QStringLiteral("speed9Axis"));
        speed9Axis->setGeometry(QRect(670, 290, 345, 27));
        speed9Axis->setMinimumSize(QSize(100, 10));
        pushButton_13 = new QPushButton(smu1_pgm1m9);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(940, 380, 51, 22));
        label_36 = new QLabel(smu1_pgm1m9);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(670, 470, 111, 16));
        label_32 = new QLabel(smu1_pgm1m9);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(670, 390, 111, 16));
        pushButton_12 = new QCAPushButton(smu1_pgm1m9);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(880, 380, 51, 22));
        sofn9Axis = new QCAAxis(smu1_pgm1m9);
        sofn9Axis->setObjectName(QStringLiteral("sofn9Axis"));
        sofn9Axis->setGeometry(QRect(670, 410, 345, 27));
        sofn9Axis->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu1_pgm1m9);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(880, 470, 51, 22));
        ref9Axis = new QCAAxis(smu1_pgm1m9);
        ref9Axis->setObjectName(QStringLiteral("ref9Axis"));
        ref9Axis->setGeometry(QRect(670, 260, 345, 27));
        ref9Axis->setMinimumSize(QSize(100, 10));
        label_33 = new QCALabel(smu1_pgm1m9);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(790, 390, 59, 14));
        curr9Axis = new QCAAxis(smu1_pgm1m9);
        curr9Axis->setObjectName(QStringLiteral("curr9Axis"));
        curr9Axis->setGeometry(QRect(670, 230, 345, 27));
        curr9Axis->setMinimumSize(QSize(100, 10));
        acc9Axis = new QCAAxis(smu1_pgm1m9);
        acc9Axis->setObjectName(QStringLiteral("acc9Axis"));
        acc9Axis->setGeometry(QRect(670, 350, 345, 27));
        acc9Axis->setMinimumSize(QSize(100, 10));
        pushButton_17 = new QCAPushButton(smu1_pgm1m9);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(940, 470, 51, 22));
        max9Axis = new QCAAxis(smu1_pgm1m9);
        max9Axis->setObjectName(QStringLiteral("max9Axis"));
        max9Axis->setGeometry(QRect(670, 320, 345, 27));
        max9Axis->setMinimumSize(QSize(100, 10));
        sofp9Axis = new QCAAxis(smu1_pgm1m9);
        sofp9Axis->setObjectName(QStringLiteral("sofp9Axis"));
        sofp9Axis->setGeometry(QRect(670, 440, 345, 27));
        sofp9Axis->setMinimumSize(QSize(100, 10));
        Axis9 = new QCAAxis(smu1_pgm1m9);
        Axis9->setObjectName(QStringLiteral("Axis9"));
        Axis9->setGeometry(QRect(20, 220, 360, 32));

        retranslateUi(smu1_pgm1m9);

        QMetaObject::connectSlotsByName(smu1_pgm1m9);
    } // setupUi

    void retranslateUi(QDialog *smu1_pgm1m9)
    {
        smu1_pgm1m9->setWindowTitle(QApplication::translate("smu1_pgm1m9", "Dialog", 0));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_25->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdBrakeDistM9", 0)));
        label_49->setText(QString());
        label_42->setText(QApplication::translate("smu1_pgm1m9", "POSA", 0));
        label_17->setText(QApplication::translate("smu1_pgm1m9", "nominal position", 0));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_54->setText(QApplication::translate("smu1_pgm1m9", "DV_ERR", 0));
        pushButton_18->setText(QString());
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_20->setText(QString());
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label->setText(QApplication::translate("smu1_pgm1m9", "DESC", 0));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_2->setText(QApplication::translate("smu1_pgm1m9", "LSN", 0));
        pushButton_2->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:LsnM9", 0)));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        lcdNumber_12->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_50->setText(QApplication::translate("smu1_pgm1m9", "Powerfail", 0));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_19->setText(QString());
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        label_41->setText(QApplication::translate("smu1_pgm1m9", "RUN", 0));
        pushButton_4->setText(QApplication::translate("smu1_pgm1m9", "RUN", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:RunM9", 0)));
        label_38->setText(QApplication::translate("smu1_pgm1m9", "ERROR", 0));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_11->setText(QApplication::translate("smu1_pgm1m9", "GoRef", 0));
        pushButton_11->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:RefM9", 0)));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        label_55->setText(QApplication::translate("smu1_pgm1m9", "LSP", 0));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_15->setText(QApplication::translate("smu1_pgm1m9", "+", 0));
        pushButton_15->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ContPosM9", 0)));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        label_39->setText(QApplication::translate("smu1_pgm1m9", "User Stop", 0));
        label_60->setText(QApplication::translate("smu1_pgm1m9", "SP", 0));
        label_24->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdCaptValM9", 0)));
        pushButton_25->setText(QString());
        pushButton_25->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_46->setText(QApplication::translate("smu1_pgm1m9", "EXT ERR", 0));
        label_59->setText(QString());
        label_23->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_23->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdCurSpeedM9", 0)));
        pushButton_22->setText(QString());
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_23->setText(QString());
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_6->setText(QApplication::translate("smu1_pgm1m9", "LSP", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:LspM9", 0)));
        label_62->setText(QApplication::translate("smu1_pgm1m9", "DV_OK", 0));
        label_2->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_2->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ChkAliveM9_.DESC", 0)));
        label_15->setText(QApplication::translate("smu1_pgm1m9", "info set", 0));
        label_18->setText(QApplication::translate("smu1_pgm1m9", "current speed", 0));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_26->setText(QApplication::translate("smu1_pgm1m9", "parameter set", 0));
        label_20->setText(QApplication::translate("smu1_pgm1m9", "brake distance", 0));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_68->setText(QApplication::translate("smu1_pgm1m9", "LOCK", 0));
        pushButton->setText(QApplication::translate("smu1_pgm1m9", "STOP", 0));
        pushButton->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:StopM8", 0)));
        label_63->setText(QApplication::translate("smu1_pgm1m9", "ABS", 0));
        pushButton_5->setText(QApplication::translate("smu1_pgm1m9", "Lock", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:LockM9", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_24->setText(QString());
        pushButton_24->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_6->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_6->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ChkAliveM9_.SEVR", 0)));
        label_9->setText(QApplication::translate("smu1_pgm1m9", "move absolute to", 0));
        label_8->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_8->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:AbsM9", 0)));
        label_4->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_4->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdPosM9.EGU", 0)));
        label_51->setText(QApplication::translate("smu1_pgm1m9", "Encoder", 0));
        lcdNumber_3->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSpeedM9", 0)));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_3->setText(QApplication::translate("smu1_pgm1m9", "REF", 0));
        pushButton_3->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:HomeM9", 0)));
        label_40->setText(QApplication::translate("smu1_pgm1m9", "DIR", 0));
        label_58->setText(QApplication::translate("smu1_pgm1m9", "OSPD", 0));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_19->setText(QApplication::translate("smu1_pgm1m9", "capture value", 0));
        label_5->setText(QApplication::translate("smu1_pgm1m9", "motion commands", 0));
        label_48->setText(QApplication::translate("smu1_pgm1m9", "SW LSN", 0));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        label_12->setText(QApplication::translate("smu1_pgm1m9", "continous mode", 0));
        label_10->setText(QApplication::translate("smu1_pgm1m9", "move continous", 0));
        label_67->setText(QApplication::translate("smu1_pgm1m9", "CAPT", 0));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_21->setText(QString());
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_47->setText(QApplication::translate("smu1_pgm1m9", "SW LSP", 0));
        label_22->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_22->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdNomPosM9", 0)));
        pushButton_7->setText(QApplication::translate("smu1_pgm1m9", "-", 0));
        pushButton_7->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ContNegM9", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        label_13->setText(QApplication::translate("smu1_pgm1m9", "error codes", 0));
        label_45->setText(QApplication::translate("smu1_pgm1m9", "SW Speed", 0));
        label_43->setText(QApplication::translate("smu1_pgm1m9", "Ref Err", 0));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        label_56->setText(QApplication::translate("smu1_pgm1m9", "LSN", 0));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        label_16->setText(QApplication::translate("smu1_pgm1m9", "current position", 0));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        label_11->setText(QApplication::translate("smu1_pgm1m9", "move to reference", 0));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_14->setText(QApplication::translate("smu1_pgm1m9", "-", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ContNegM9", 0)));
        label_61->setText(QApplication::translate("smu1_pgm1m9", "70X I", 0));
        pushButton_40->setText(QString());
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrStateM9", 0)));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_65->setText(QApplication::translate("smu1_pgm1m9", "LSP", 0));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        lcdNumber->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdPosM9", 0)));
        pushButton_10->setText(QApplication::translate("smu1_pgm1m9", "+", 0));
        pushButton_10->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:ContPosM9", 0)));
        label_3->setText(QApplication::translate("smu1_pgm1m9", "SMU41_1", 0));
        label_14->setText(QApplication::translate("smu1_pgm1m9", "M9", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdStateM9", 0)));
        label_64->setText(QApplication::translate("smu1_pgm1m9", "LSN", 0));
        label_21->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_21->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdPosM9", 0)));
        label_52->setText(QString());
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdErrFlagM9", 0)));
        label_57->setText(QApplication::translate("smu1_pgm1m9", "ABS", 0));
        label_66->setText(QApplication::translate("smu1_pgm1m9", "REF", 0));
        label_53->setText(QApplication::translate("smu1_pgm1m9", "HW Speed", 0));
        label_44->setText(QApplication::translate("smu1_pgm1m9", "Track Err", 0));
        label_37->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSwLimM9", 0)));
        speed9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "speed", 0)));
        speed9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSpeedM9", 0)));
        speed9Axis->setProperty("units", QVariant(QString()));
        speed9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSpeedM9", 0)));
        pushButton_13->setText(QApplication::translate("smu1_pgm1m9", "exp", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:AccM9", 0)));
        label_36->setText(QApplication::translate("smu1_pgm1m9", "soft limit", 0));
        label_32->setText(QApplication::translate("smu1_pgm1m9", "ramp shape", 0));
        pushButton_12->setText(QApplication::translate("smu1_pgm1m9", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:AccM9", 0)));
        sofn9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "soft limit negativ", 0)));
        sofn9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSwLimNegM9", 0)));
        sofn9Axis->setProperty("units", QVariant(QString()));
        sofn9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSwLimNegM9", 0)));
        pushButton_16->setText(QApplication::translate("smu1_pgm1m9", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:SwLimM9", 0)));
        ref9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "reference positic", 0)));
        ref9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdRefM9", 0)));
        ref9Axis->setProperty("units", QVariant(QString()));
        ref9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdRefM9", 0)));
        label_33->setText(QApplication::translate("smu1_pgm1m9", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdAccM9", 0)));
        curr9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "current position", 0)));
        curr9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdPosM9", 0)));
        curr9Axis->setProperty("units", QVariant(QApplication::translate("smu1_pgm1m9", "steps", 0)));
        curr9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdPosM9", 0)));
        acc9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "acceleration time", 0)));
        acc9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdAccTimeM9", 0)));
        acc9Axis->setProperty("units", QVariant(QString()));
        acc9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdAccTimeM9", 0)));
        pushButton_17->setText(QApplication::translate("smu1_pgm1m9", "on", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:SwLimM9", 0)));
        max9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "maximal speed", 0)));
        max9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdMaxSpeedM9", 0)));
        max9Axis->setProperty("units", QVariant(QString()));
        max9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdMaxSpeedM9", 0)));
        sofp9Axis->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "soft limit positiv", 0)));
        sofp9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSwLimPosM9", 0)));
        sofp9Axis->setProperty("units", QVariant(QString()));
        sofp9Axis->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdSwLimPosM9", 0)));
        Axis9->setProperty("description", QVariant(QApplication::translate("smu1_pgm1m9", "move relative", 0)));
        Axis9->setProperty("pvReadback", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdRelM9", 0)));
        Axis9->setProperty("units", QVariant(QApplication::translate("smu1_pgm1m9", "steps", 0)));
        Axis9->setProperty("pv", QVariant(QApplication::translate("smu1_pgm1m9", "SMU41_1:rdRelM9", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu1_pgm1m9: public Ui_smu1_pgm1m9 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU1_PGM1M9_H
