/********************************************************************************
** Form generated from reading UI file 'smu2_m7.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU2_M7_H
#define UI_SMU2_M7_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu2_m7
{
public:
    QCAPushButton *pushButton_6;
    QLabel *label_44;
    QCALCDNumber *lcdNumber_11;
    QLabel *label_46;
    QCAPushButton *pushButton_18;
    QCALabel *label_45;
    QCAPushButton *pushButton_13;
    QCAPushButton *pushButton_4;
    QCAPushButton *pushButton_17;
    QCALabel *label_13;
    QCAPushButton *pushButton_5;
    QLabel *label_39;
    QCALabel *label_41;
    QLabel *label_19;
    QCALabel *label_38;
    QLabel *label_18;
    QLabel *label_23;
    QLabel *label_20;
    QCALabel *label_24;
    QLabel *label_43;
    QLabel *label_40;
    QCALabel *label_42;
    QCALabel *label_25;
    QLabel *label_26;
    QCAPushButton *pushButton_34;
    QCAPushButton *pushButton_28;
    QCALCDNumber *lcdNumber_16;
    QLabel *label_65;
    QCAPushButton *pushButton_40;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_31;
    QCAPushButton *pushButton_63;
    QCAPushButton *pushButton_27;
    QLabel *label_73;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_73;
    QLabel *label_58;
    QCAPushButton *pushButton_44;
    QLabel *label_85;
    QCAPushButton *pushButton_48;
    QCAPushButton *pushButton_58;
    QCAPushButton *pushButton_53;
    QCAPushButton *pushButton_38;
    QCAPushButton *pushButton_67;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_63;
    QCAPushButton *pushButton_35;
    QLabel *label_59;
    QLabel *label_66;
    QCAPushButton *pushButton_49;
    QCALCDNumber *lcdNumber_15;
    QLabel *label_81;
    QCAPushButton *pushButton_62;
    QCAPushButton *pushButton_52;
    QCAPushButton *pushButton_55;
    QLabel *label_77;
    QLabel *label_75;
    QCAPushButton *pushButton_59;
    QLabel *label_84;
    QCAPushButton *pushButton_54;
    QCAPushButton *pushButton_66;
    QLabel *label_71;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_60;
    QCAPushButton *pushButton_65;
    QLabel *label_76;
    QLabel *label_64;
    QLabel *label_80;
    QCAPushButton *pushButton_36;
    QCAPushButton *pushButton_42;
    QLabel *label_69;
    QLabel *label_55;
    QLabel *label_60;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_69;
    QCAPushButton *pushButton_37;
    QCAPushButton *pushButton_30;
    QLabel *label_79;
    QCAPushButton *pushButton_46;
    QCAPushButton *pushButton_61;
    QLabel *label_62;
    QLabel *label_74;
    QLabel *label_86;
    QCAPushButton *pushButton_71;
    QLabel *label_78;
    QCAPushButton *pushButton_72;
    QLabel *label_57;
    QCAPushButton *pushButton_47;
    QLabel *label_70;
    QCAPushButton *pushButton_57;
    QLabel *label_61;
    QCAPushButton *pushButton_56;
    QLabel *label_83;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_64;
    QLabel *label_72;
    QCAPushButton *pushButton_68;
    QCAPushButton *pushButton_70;
    QCALCDNumber *lcdNumber_14;
    QCAPushButton *pushButton_51;
    QLabel *label_82;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_41;
    QLabel *label_56;
    QCAPushButton *pushButton_45;
    QLabel *label_48;
    QLabel *label_51;
    QCAPushButton *pushButton_20;
    QScrollBar *horizontalScrollBar_2;
    QCAPushButton *pushButton_23;
    QCAPushButton *pushButton_22;
    QCAPushButton *pushButton_19;
    QCALabel *label_47;
    QLabel *label_49;
    QLabel *label_54;
    QCAPushButton *pushButton_21;
    QCALCDNumber *lcdNumber_13;
    QLabel *label_53;
    QLabel *label_36;
    QCAAxis *speed7Axis;
    QCAAxis *ref7Axis;
    QCAPushButton *pushButton_16;
    QCAAxis *max7Axis;
    QCAAxis *sofn7Axis;
    QCAAxis *curr7Axis;
    QCAPushButton *pushButton_12;
    QPushButton *pushButton_14;
    QCAAxis *acc7Axis;
    QLabel *label_32;
    QCAAxis *sofp7Axis;
    QCALabel *label_37;
    QCAPushButton *pushButton_74;
    QCALabel *label_33;
    QCAAxis *Axis7;

    void setupUi(QDialog *smu2_m7)
    {
        if (smu2_m7->objectName().isEmpty())
            smu2_m7->setObjectName(QStringLiteral("smu2_m7"));
        smu2_m7->resize(984, 632);
        pushButton_6 = new QCAPushButton(smu2_m7);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(310, 120, 81, 22));
        label_44 = new QLabel(smu2_m7);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(310, 30, 71, 16));
        lcdNumber_11 = new QCALCDNumber(smu2_m7);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(320, 80, 64, 23));
        label_46 = new QLabel(smu2_m7);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(20, 20, 59, 14));
        pushButton_18 = new QCAPushButton(smu2_m7);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(510, 120, 81, 22));
        label_45 = new QCALabel(smu2_m7);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 40, 59, 14));
        pushButton_13 = new QCAPushButton(smu2_m7);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(210, 120, 81, 22));
        pushButton_4 = new QCAPushButton(smu2_m7);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(20, 91, 81, 51));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_17 = new QCAPushButton(smu2_m7);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(410, 120, 81, 22));
        label_13 = new QCALabel(smu2_m7);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(520, 80, 59, 14));
        pushButton_5 = new QCAPushButton(smu2_m7);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(120, 120, 81, 22));
        label_39 = new QLabel(smu2_m7);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(710, 70, 111, 16));
        label_41 = new QCALabel(smu2_m7);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(850, 70, 91, 16));
        label_19 = new QLabel(smu2_m7);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(710, 90, 111, 16));
        label_38 = new QCALabel(smu2_m7);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(850, 90, 91, 16));
        label_18 = new QLabel(smu2_m7);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(640, 60, 59, 14));
        label_18->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_23 = new QLabel(smu2_m7);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(820, 30, 59, 14));
        label_20 = new QLabel(smu2_m7);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(710, 130, 91, 16));
        label_24 = new QCALabel(smu2_m7);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(850, 130, 81, 16));
        label_43 = new QLabel(smu2_m7);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(710, 110, 91, 16));
        label_40 = new QLabel(smu2_m7);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(710, 150, 101, 16));
        label_42 = new QCALabel(smu2_m7);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(850, 150, 91, 16));
        label_25 = new QCALabel(smu2_m7);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(850, 110, 91, 16));
        label_26 = new QLabel(smu2_m7);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(640, 230, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_34 = new QCAPushButton(smu2_m7);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(440, 420, 31, 21));
        pushButton_28 = new QCAPushButton(smu2_m7);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(390, 300, 31, 21));
        lcdNumber_16 = new QCALCDNumber(smu2_m7);
        lcdNumber_16->setObjectName(QStringLiteral("lcdNumber_16"));
        lcdNumber_16->setGeometry(QRect(440, 270, 64, 23));
        lcdNumber_16->setStyleSheet(QStringLiteral(""));
        lcdNumber_16->setMode(QLCDNumber::Hex);
        label_65 = new QLabel(smu2_m7);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(320, 540, 59, 14));
        pushButton_40 = new QCAPushButton(smu2_m7);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(440, 480, 31, 21));
        pushButton_33 = new QCAPushButton(smu2_m7);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(470, 400, 31, 21));
        pushButton_31 = new QCAPushButton(smu2_m7);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(470, 380, 31, 21));
        pushButton_63 = new QCAPushButton(smu2_m7);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(390, 560, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_27 = new QCAPushButton(smu2_m7);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(440, 300, 31, 21));
        label_73 = new QLabel(smu2_m7);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(320, 300, 59, 14));
        pushButton_29 = new QCAPushButton(smu2_m7);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(470, 360, 31, 21));
        pushButton_73 = new QCAPushButton(smu2_m7);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(390, 320, 31, 21));
        pushButton_73->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_58 = new QLabel(smu2_m7);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(320, 360, 59, 14));
        pushButton_44 = new QCAPushButton(smu2_m7);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(440, 520, 31, 21));
        label_85 = new QLabel(smu2_m7);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(520, 440, 71, 16));
        pushButton_48 = new QCAPushButton(smu2_m7);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(440, 400, 31, 21));
        pushButton_58 = new QCAPushButton(smu2_m7);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(390, 460, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_53 = new QCAPushButton(smu2_m7);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(470, 600, 31, 21));
        pushButton_38 = new QCAPushButton(smu2_m7);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(470, 340, 31, 21));
        pushButton_67 = new QCAPushButton(smu2_m7);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(440, 560, 31, 21));
        label_67 = new QLabel(smu2_m7);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(320, 580, 59, 14));
        label_68 = new QLabel(smu2_m7);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(320, 600, 59, 14));
        label_63 = new QLabel(smu2_m7);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(520, 340, 71, 16));
        pushButton_35 = new QCAPushButton(smu2_m7);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(390, 340, 31, 21));
        pushButton_35->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_59 = new QLabel(smu2_m7);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(520, 320, 71, 16));
        label_66 = new QLabel(smu2_m7);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(520, 500, 71, 16));
        pushButton_49 = new QCAPushButton(smu2_m7);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(470, 560, 31, 21));
        lcdNumber_15 = new QCALCDNumber(smu2_m7);
        lcdNumber_15->setObjectName(QStringLiteral("lcdNumber_15"));
        lcdNumber_15->setGeometry(QRect(440, 240, 64, 23));
        lcdNumber_15->setMode(QLCDNumber::Hex);
        label_81 = new QLabel(smu2_m7);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(520, 460, 71, 16));
        pushButton_62 = new QCAPushButton(smu2_m7);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(390, 540, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_52 = new QCAPushButton(smu2_m7);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(440, 600, 31, 21));
        pushButton_55 = new QCAPushButton(smu2_m7);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(390, 400, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        label_77 = new QLabel(smu2_m7);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(520, 600, 71, 16));
        label_75 = new QLabel(smu2_m7);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(520, 540, 71, 16));
        pushButton_59 = new QCAPushButton(smu2_m7);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(390, 480, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_84 = new QLabel(smu2_m7);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(520, 580, 71, 16));
        pushButton_54 = new QCAPushButton(smu2_m7);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(390, 380, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        pushButton_66 = new QCAPushButton(smu2_m7);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(470, 520, 31, 21));
        label_71 = new QLabel(smu2_m7);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(520, 300, 71, 16));
        pushButton_39 = new QCAPushButton(smu2_m7);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(470, 460, 31, 21));
        pushButton_60 = new QCAPushButton(smu2_m7);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(390, 500, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        pushButton_65 = new QCAPushButton(smu2_m7);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(390, 600, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        label_76 = new QLabel(smu2_m7);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(320, 560, 59, 14));
        label_64 = new QLabel(smu2_m7);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(320, 520, 59, 14));
        label_80 = new QLabel(smu2_m7);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(520, 360, 71, 16));
        pushButton_36 = new QCAPushButton(smu2_m7);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(440, 440, 31, 21));
        pushButton_42 = new QCAPushButton(smu2_m7);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(440, 500, 31, 21));
        label_69 = new QLabel(smu2_m7);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(520, 520, 71, 16));
        label_55 = new QLabel(smu2_m7);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(520, 380, 71, 16));
        label_60 = new QLabel(smu2_m7);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(320, 440, 59, 14));
        pushButton_43 = new QCAPushButton(smu2_m7);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(470, 500, 31, 21));
        pushButton_26 = new QCAPushButton(smu2_m7);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(440, 340, 31, 21));
        pushButton_69 = new QCAPushButton(smu2_m7);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(390, 440, 31, 21));
        pushButton_69->setStyleSheet(QStringLiteral(""));
        pushButton_37 = new QCAPushButton(smu2_m7);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(470, 440, 31, 21));
        pushButton_30 = new QCAPushButton(smu2_m7);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(390, 360, 31, 21));
        pushButton_30->setStyleSheet(QStringLiteral(""));
        label_79 = new QLabel(smu2_m7);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(520, 560, 71, 16));
        pushButton_46 = new QCAPushButton(smu2_m7);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(440, 540, 31, 21));
        pushButton_61 = new QCAPushButton(smu2_m7);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(390, 520, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_62 = new QLabel(smu2_m7);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(320, 480, 59, 14));
        label_74 = new QLabel(smu2_m7);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(320, 420, 59, 14));
        label_86 = new QLabel(smu2_m7);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(320, 400, 59, 14));
        pushButton_71 = new QCAPushButton(smu2_m7);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(470, 320, 31, 21));
        label_78 = new QLabel(smu2_m7);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(320, 340, 59, 14));
        pushButton_72 = new QCAPushButton(smu2_m7);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(390, 420, 31, 21));
        pushButton_72->setStyleSheet(QStringLiteral(""));
        label_57 = new QLabel(smu2_m7);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(320, 380, 59, 14));
        pushButton_47 = new QCAPushButton(smu2_m7);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(470, 540, 31, 21));
        label_70 = new QLabel(smu2_m7);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(520, 480, 71, 16));
        pushButton_57 = new QCAPushButton(smu2_m7);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(470, 420, 31, 21));
        label_61 = new QLabel(smu2_m7);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(320, 460, 59, 14));
        pushButton_56 = new QCAPushButton(smu2_m7);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(470, 300, 31, 21));
        label_83 = new QLabel(smu2_m7);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(360, 200, 81, 16));
        label_83->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_50 = new QCAPushButton(smu2_m7);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(440, 580, 31, 21));
        pushButton_64 = new QCAPushButton(smu2_m7);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(390, 580, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        label_72 = new QLabel(smu2_m7);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(320, 500, 59, 14));
        pushButton_68 = new QCAPushButton(smu2_m7);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(440, 460, 31, 21));
        pushButton_70 = new QCAPushButton(smu2_m7);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(440, 320, 31, 21));
        lcdNumber_14 = new QCALCDNumber(smu2_m7);
        lcdNumber_14->setObjectName(QStringLiteral("lcdNumber_14"));
        lcdNumber_14->setGeometry(QRect(360, 270, 64, 23));
        lcdNumber_14->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_14->setMode(QLCDNumber::Hex);
        lcdNumber_14->setSegmentStyle(QLCDNumber::Filled);
        pushButton_51 = new QCAPushButton(smu2_m7);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(470, 580, 31, 21));
        label_82 = new QLabel(smu2_m7);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(520, 400, 71, 16));
        pushButton_32 = new QCAPushButton(smu2_m7);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(440, 380, 31, 21));
        pushButton_41 = new QCAPushButton(smu2_m7);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(470, 480, 31, 21));
        label_56 = new QLabel(smu2_m7);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(520, 420, 71, 16));
        pushButton_45 = new QCAPushButton(smu2_m7);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(440, 360, 31, 21));
        label_48 = new QLabel(smu2_m7);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 320, 111, 16));
        label_51 = new QLabel(smu2_m7);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(10, 200, 121, 16));
        label_51->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_20 = new QCAPushButton(smu2_m7);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(220, 440, 31, 31));
        horizontalScrollBar_2 = new QScrollBar(smu2_m7);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(60, 450, 151, 16));
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        pushButton_23 = new QCAPushButton(smu2_m7);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(140, 320, 61, 22));
        pushButton_22 = new QCAPushButton(smu2_m7);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(230, 320, 61, 22));
        pushButton_19 = new QCAPushButton(smu2_m7);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(20, 440, 31, 31));
        label_47 = new QCALabel(smu2_m7);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(170, 280, 101, 16));
        label_49 = new QLabel(smu2_m7);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(90, 400, 111, 16));
        label_54 = new QLabel(smu2_m7);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 280, 111, 16));
        pushButton_21 = new QCAPushButton(smu2_m7);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(140, 350, 151, 22));
        lcdNumber_13 = new QCALCDNumber(smu2_m7);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(110, 420, 64, 23));
        label_53 = new QLabel(smu2_m7);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 350, 121, 16));
        label_36 = new QLabel(smu2_m7);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(610, 500, 111, 16));
        speed7Axis = new QCAAxis(smu2_m7);
        speed7Axis->setObjectName(QStringLiteral("speed7Axis"));
        speed7Axis->setGeometry(QRect(610, 320, 345, 27));
        speed7Axis->setMinimumSize(QSize(100, 10));
        ref7Axis = new QCAAxis(smu2_m7);
        ref7Axis->setObjectName(QStringLiteral("ref7Axis"));
        ref7Axis->setGeometry(QRect(610, 290, 345, 27));
        ref7Axis->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu2_m7);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(820, 500, 51, 22));
        max7Axis = new QCAAxis(smu2_m7);
        max7Axis->setObjectName(QStringLiteral("max7Axis"));
        max7Axis->setGeometry(QRect(610, 350, 345, 27));
        max7Axis->setMinimumSize(QSize(100, 10));
        sofn7Axis = new QCAAxis(smu2_m7);
        sofn7Axis->setObjectName(QStringLiteral("sofn7Axis"));
        sofn7Axis->setGeometry(QRect(610, 440, 345, 27));
        sofn7Axis->setMinimumSize(QSize(100, 10));
        curr7Axis = new QCAAxis(smu2_m7);
        curr7Axis->setObjectName(QStringLiteral("curr7Axis"));
        curr7Axis->setGeometry(QRect(610, 260, 345, 27));
        curr7Axis->setMinimumSize(QSize(100, 10));
        pushButton_12 = new QCAPushButton(smu2_m7);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(820, 410, 51, 22));
        pushButton_14 = new QPushButton(smu2_m7);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(880, 410, 51, 22));
        acc7Axis = new QCAAxis(smu2_m7);
        acc7Axis->setObjectName(QStringLiteral("acc7Axis"));
        acc7Axis->setGeometry(QRect(610, 380, 345, 27));
        acc7Axis->setMinimumSize(QSize(100, 10));
        label_32 = new QLabel(smu2_m7);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(610, 420, 111, 16));
        sofp7Axis = new QCAAxis(smu2_m7);
        sofp7Axis->setObjectName(QStringLiteral("sofp7Axis"));
        sofp7Axis->setGeometry(QRect(610, 470, 345, 27));
        sofp7Axis->setMinimumSize(QSize(100, 10));
        label_37 = new QCALabel(smu2_m7);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(730, 500, 59, 14));
        pushButton_74 = new QCAPushButton(smu2_m7);
        pushButton_74->setObjectName(QStringLiteral("pushButton_74"));
        pushButton_74->setGeometry(QRect(880, 500, 51, 22));
        label_33 = new QCALabel(smu2_m7);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(730, 420, 59, 14));
        Axis7 = new QCAAxis(smu2_m7);
        Axis7->setObjectName(QStringLiteral("Axis7"));
        Axis7->setGeometry(QRect(10, 230, 360, 32));

        retranslateUi(smu2_m7);

        QMetaObject::connectSlotsByName(smu2_m7);
    } // setupUi

    void retranslateUi(QDialog *smu2_m7)
    {
        smu2_m7->setWindowTitle(QApplication::translate("smu2_m7", "Dialog", 0));
        pushButton_6->setText(QApplication::translate("smu2_m7", "RUN", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:RunM7", 0)));
        label_44->setText(QApplication::translate("smu2_m7", "SMU41_2", 0));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdPosM7", 0)));
        label_46->setText(QApplication::translate("smu2_m7", "DESC", 0));
        pushButton_18->setText(QApplication::translate("smu2_m7", "LSP", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:LspM7", 0)));
        label_45->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:ChkAliveM7_.DESC", 0)));
        pushButton_13->setText(QApplication::translate("smu2_m7", "REF", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:HomeM7", 0)));
        pushButton_4->setText(QApplication::translate("smu2_m7", "STOP", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:StopM7", 0)));
        pushButton_17->setText(QApplication::translate("smu2_m7", "Lock", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:LockM7", 0)));
        label_13->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdPosM7.EGU", 0)));
        pushButton_5->setText(QApplication::translate("smu2_m7", "LSN", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:LsnM7", 0)));
        label_39->setText(QApplication::translate("smu2_m7", "current position", 0));
        label_41->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_41->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdPosM7", 0)));
        label_19->setText(QApplication::translate("smu2_m7", "nominal position", 0));
        label_38->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdNomPosM7", 0)));
        label_18->setText(QApplication::translate("smu2_m7", "info set", 0));
        label_23->setText(QApplication::translate("smu2_m7", "M7", 0));
        label_20->setText(QApplication::translate("smu2_m7", "capture value", 0));
        label_24->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdCaptValM7", 0)));
        label_43->setText(QApplication::translate("smu2_m7", "current speed", 0));
        label_40->setText(QApplication::translate("smu2_m7", "brake distance", 0));
        label_42->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_42->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdBrakeDistM7", 0)));
        label_25->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdCurSpeedM7", 0)));
        label_26->setText(QApplication::translate("smu2_m7", "parameter set", 0));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        lcdNumber_16->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_65->setText(QApplication::translate("smu2_m7", "LSP", 0));
        pushButton_40->setText(QString());
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_73->setText(QApplication::translate("smu2_m7", "ERROR", 0));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_73->setText(QString());
        pushButton_73->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_58->setText(QApplication::translate("smu2_m7", "RUN", 0));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        label_85->setText(QApplication::translate("smu2_m7", "SW LSN", 0));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_67->setText(QString());
        pushButton_67->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        label_67->setText(QApplication::translate("smu2_m7", "CAPT", 0));
        label_68->setText(QApplication::translate("smu2_m7", "LOCK", 0));
        label_63->setText(QApplication::translate("smu2_m7", "Ref Err", 0));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_59->setText(QApplication::translate("smu2_m7", "POSA", 0));
        label_66->setText(QApplication::translate("smu2_m7", "Encoder", 0));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        lcdNumber_15->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        label_81->setText(QString());
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_77->setText(QApplication::translate("smu2_m7", "LSN", 0));
        label_75->setText(QApplication::translate("smu2_m7", "HW Speed", 0));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_84->setText(QApplication::translate("smu2_m7", "LSP", 0));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_66->setText(QString());
        pushButton_66->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_71->setText(QApplication::translate("smu2_m7", "User Stop", 0));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_76->setText(QApplication::translate("smu2_m7", "REF", 0));
        label_64->setText(QApplication::translate("smu2_m7", "LSN", 0));
        label_80->setText(QApplication::translate("smu2_m7", "Track Err", 0));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        label_69->setText(QString());
        label_55->setText(QApplication::translate("smu2_m7", "SW Speed", 0));
        label_60->setText(QApplication::translate("smu2_m7", "SP", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_69->setText(QString());
        pushButton_69->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_79->setText(QApplication::translate("smu2_m7", "DV_ERR", 0));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_62->setText(QApplication::translate("smu2_m7", "DV_OK", 0));
        label_74->setText(QString());
        label_86->setText(QApplication::translate("smu2_m7", "OSPD", 0));
        pushButton_71->setText(QString());
        pushButton_71->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_78->setText(QApplication::translate("smu2_m7", "DIR", 0));
        pushButton_72->setText(QString());
        pushButton_72->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_57->setText(QApplication::translate("smu2_m7", "ABS", 0));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_70->setText(QApplication::translate("smu2_m7", "Powerfail", 0));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_61->setText(QApplication::translate("smu2_m7", "70X I", 0));
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_83->setText(QApplication::translate("smu2_m7", "error codes", 0));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        label_72->setText(QApplication::translate("smu2_m7", "ABS", 0));
        pushButton_68->setText(QString());
        pushButton_68->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        pushButton_70->setText(QString());
        pushButton_70->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        lcdNumber_14->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdStateM7", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_82->setText(QApplication::translate("smu2_m7", "EXT ERR", 0));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrFlagM7", 0)));
        label_56->setText(QApplication::translate("smu2_m7", "SW LSP", 0));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdErrStateM7", 0)));
        label_48->setText(QApplication::translate("smu2_m7", "move continous", 0));
        label_51->setText(QApplication::translate("smu2_m7", "motion commands", 0));
        pushButton_20->setText(QApplication::translate("smu2_m7", "+", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:ContPosM7", 0)));
        pushButton_23->setText(QApplication::translate("smu2_m7", "-", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:ContNegM7", 0)));
        pushButton_22->setText(QApplication::translate("smu2_m7", "+", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:ContPosM7", 0)));
        pushButton_19->setText(QApplication::translate("smu2_m7", "-", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:ContNegM7", 0)));
        label_47->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_47->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:AbsM7", 0)));
        label_49->setText(QApplication::translate("smu2_m7", "continous mode", 0));
        label_54->setText(QApplication::translate("smu2_m7", "move absolute to", 0));
        pushButton_21->setText(QApplication::translate("smu2_m7", "GoRef", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:RefM7", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSpeedM7", 0)));
        label_53->setText(QApplication::translate("smu2_m7", "move to reference", 0));
        label_36->setText(QApplication::translate("smu2_m7", "soft limit", 0));
        speed7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "speed", 0)));
        speed7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSpeedM7", 0)));
        speed7Axis->setProperty("units", QVariant(QString()));
        speed7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSpeedM7", 0)));
        ref7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "reference positic", 0)));
        ref7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdRefM7", 0)));
        ref7Axis->setProperty("units", QVariant(QString()));
        ref7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdRefM7", 0)));
        pushButton_16->setText(QApplication::translate("smu2_m7", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:SwLimM7", 0)));
        max7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "maximal speed", 0)));
        max7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdMaxSpeedM7", 0)));
        max7Axis->setProperty("units", QVariant(QString()));
        max7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdMaxSpeedM7", 0)));
        sofn7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "soft limit negativ", 0)));
        sofn7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSwLimNegM7", 0)));
        sofn7Axis->setProperty("units", QVariant(QString()));
        sofn7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSwLimNegM7", 0)));
        curr7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "current position", 0)));
        curr7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdPosM7", 0)));
        curr7Axis->setProperty("units", QVariant(QApplication::translate("smu2_m7", "steps", 0)));
        curr7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdPosM7", 0)));
        pushButton_12->setText(QApplication::translate("smu2_m7", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:AccM7", 0)));
        pushButton_14->setText(QApplication::translate("smu2_m7", "exp", 0));
        pushButton_14->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:AccM7", 0)));
        acc7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "acceleration time", 0)));
        acc7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdAccTimeM7", 0)));
        acc7Axis->setProperty("units", QVariant(QString()));
        acc7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdAccTimeM7", 0)));
        label_32->setText(QApplication::translate("smu2_m7", "ramp shape", 0));
        sofp7Axis->setProperty("description", QVariant(QApplication::translate("smu2_m7", "soft limit positiv", 0)));
        sofp7Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSwLimPosM7", 0)));
        sofp7Axis->setProperty("units", QVariant(QString()));
        sofp7Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSwLimPosM7", 0)));
        label_37->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdSwLimM7", 0)));
        pushButton_74->setText(QApplication::translate("smu2_m7", "on", 0));
        pushButton_74->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:SwLimM7", 0)));
        label_33->setText(QApplication::translate("smu2_m7", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdAccM7", 0)));
        Axis7->setProperty("description", QVariant(QApplication::translate("smu2_m7", "move relative", 0)));
        Axis7->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdRelM7", 0)));
        Axis7->setProperty("units", QVariant(QApplication::translate("smu2_m7", "steps", 0)));
        Axis7->setProperty("pv", QVariant(QApplication::translate("smu2_m7", "SMU41_2:rdRelM7", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu2_m7: public Ui_smu2_m7 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU2_M7_H
