/********************************************************************************
** Form generated from reading UI file 'smu2_m9.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SMU2_M9_H
#define UI_SMU2_M9_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QScrollBar>
#include "qcaaxis.h"
#include "qcalabel.h"
#include "qcalcdnumber.h"
#include "qcapushbutton.h"

QT_BEGIN_NAMESPACE

class Ui_smu2_m9
{
public:
    QLabel *label_39;
    QLabel *label_19;
    QLabel *label_18;
    QCALabel *label_38;
    QLabel *label_43;
    QCALabel *label_25;
    QCALabel *label_24;
    QCALabel *label_42;
    QLabel *label_20;
    QLabel *label_23;
    QCALabel *label_41;
    QLabel *label_40;
    QLabel *label_26;
    QCAPushButton *pushButton_13;
    QCAPushButton *pushButton_4;
    QCAPushButton *pushButton_6;
    QLabel *label_44;
    QCALCDNumber *lcdNumber_11;
    QLabel *label_46;
    QCAPushButton *pushButton_18;
    QCAPushButton *pushButton_17;
    QCALabel *label_45;
    QCALabel *label_13;
    QCAPushButton *pushButton_5;
    QLabel *label_48;
    QCAPushButton *pushButton_21;
    QCAPushButton *pushButton_20;
    QLabel *label_53;
    QLabel *label_54;
    QCAPushButton *pushButton_23;
    QCALCDNumber *lcdNumber_13;
    QCALabel *label_47;
    QScrollBar *horizontalScrollBar_2;
    QCAPushButton *pushButton_19;
    QCAPushButton *pushButton_22;
    QLabel *label_49;
    QLabel *label_51;
    QLabel *label_69;
    QLabel *label_59;
    QLabel *label_77;
    QLabel *label_84;
    QCAPushButton *pushButton_31;
    QLabel *label_58;
    QCAPushButton *pushButton_35;
    QCAPushButton *pushButton_44;
    QLabel *label_66;
    QLabel *label_73;
    QLabel *label_65;
    QLabel *label_83;
    QCAPushButton *pushButton_29;
    QCAPushButton *pushButton_54;
    QLabel *label_57;
    QCAPushButton *pushButton_61;
    QCAPushButton *pushButton_63;
    QLabel *label_61;
    QCAPushButton *pushButton_43;
    QCAPushButton *pushButton_45;
    QCAPushButton *pushButton_51;
    QCAPushButton *pushButton_34;
    QLabel *label_63;
    QCAPushButton *pushButton_40;
    QLabel *label_79;
    QCAPushButton *pushButton_67;
    QCAPushButton *pushButton_41;
    QCAPushButton *pushButton_52;
    QLabel *label_74;
    QLabel *label_82;
    QCAPushButton *pushButton_46;
    QCAPushButton *pushButton_26;
    QCAPushButton *pushButton_36;
    QCAPushButton *pushButton_30;
    QCAPushButton *pushButton_64;
    QCAPushButton *pushButton_48;
    QLabel *label_76;
    QLabel *label_81;
    QCAPushButton *pushButton_56;
    QLabel *label_72;
    QCAPushButton *pushButton_49;
    QCALCDNumber *lcdNumber_15;
    QLabel *label_71;
    QCAPushButton *pushButton_32;
    QCAPushButton *pushButton_38;
    QLabel *label_86;
    QLabel *label_67;
    QCAPushButton *pushButton_71;
    QCAPushButton *pushButton_65;
    QCAPushButton *pushButton_55;
    QCAPushButton *pushButton_60;
    QCAPushButton *pushButton_28;
    QCAPushButton *pushButton_68;
    QCAPushButton *pushButton_37;
    QCAPushButton *pushButton_39;
    QCAPushButton *pushButton_47;
    QCAPushButton *pushButton_58;
    QCAPushButton *pushButton_27;
    QLabel *label_80;
    QLabel *label_68;
    QLabel *label_62;
    QCAPushButton *pushButton_73;
    QLabel *label_55;
    QLabel *label_85;
    QLabel *label_78;
    QLabel *label_56;
    QCAPushButton *pushButton_33;
    QCAPushButton *pushButton_62;
    QCALCDNumber *lcdNumber_14;
    QCAPushButton *pushButton_72;
    QLabel *label_64;
    QCALCDNumber *lcdNumber_16;
    QLabel *label_60;
    QCAPushButton *pushButton_50;
    QCAPushButton *pushButton_57;
    QCAPushButton *pushButton_70;
    QLabel *label_75;
    QCAPushButton *pushButton_59;
    QCAPushButton *pushButton_42;
    QCAPushButton *pushButton_53;
    QLabel *label_70;
    QCAPushButton *pushButton_66;
    QCAPushButton *pushButton_69;
    QLabel *label_36;
    QCALabel *label_37;
    QCAAxis *speed9Axis;
    QCAAxis *ref9Axis;
    QCAAxis *acc9Axis;
    QLabel *label_32;
    QCAAxis *sofn9Axis;
    QCAAxis *max9Axis;
    QCAPushButton *pushButton_16;
    QCALabel *label_33;
    QCAAxis *curr9Axis;
    QCAPushButton *pushButton_12;
    QCAAxis *sofp9Axis;
    QCAAxis *Axis9;

    void setupUi(QDialog *smu2_m9)
    {
        if (smu2_m9->objectName().isEmpty())
            smu2_m9->setObjectName(QStringLiteral("smu2_m9"));
        smu2_m9->resize(1163, 656);
        label_39 = new QLabel(smu2_m9);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(920, 70, 111, 16));
        label_19 = new QLabel(smu2_m9);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(920, 90, 111, 16));
        label_18 = new QLabel(smu2_m9);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(850, 60, 59, 14));
        label_18->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_38 = new QCALabel(smu2_m9);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(1060, 90, 91, 16));
        label_43 = new QLabel(smu2_m9);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(920, 110, 91, 16));
        label_25 = new QCALabel(smu2_m9);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(1060, 110, 91, 16));
        label_24 = new QCALabel(smu2_m9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(1060, 130, 81, 16));
        label_42 = new QCALabel(smu2_m9);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1060, 150, 91, 16));
        label_20 = new QLabel(smu2_m9);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(920, 130, 91, 16));
        label_23 = new QLabel(smu2_m9);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(1030, 30, 59, 14));
        label_41 = new QCALabel(smu2_m9);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(1060, 70, 91, 16));
        label_40 = new QLabel(smu2_m9);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(920, 150, 101, 16));
        label_26 = new QLabel(smu2_m9);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(820, 220, 101, 16));
        label_26->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_13 = new QCAPushButton(smu2_m9);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(220, 120, 81, 22));
        pushButton_4 = new QCAPushButton(smu2_m9);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(30, 91, 81, 51));
        pushButton_4->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 255);"));
        pushButton_6 = new QCAPushButton(smu2_m9);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(320, 120, 81, 22));
        label_44 = new QLabel(smu2_m9);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(320, 30, 71, 16));
        lcdNumber_11 = new QCALCDNumber(smu2_m9);
        lcdNumber_11->setObjectName(QStringLiteral("lcdNumber_11"));
        lcdNumber_11->setGeometry(QRect(330, 80, 64, 23));
        label_46 = new QLabel(smu2_m9);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(30, 20, 59, 14));
        pushButton_18 = new QCAPushButton(smu2_m9);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(520, 120, 81, 22));
        pushButton_17 = new QCAPushButton(smu2_m9);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(420, 120, 81, 22));
        label_45 = new QCALabel(smu2_m9);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(30, 40, 59, 14));
        label_13 = new QCALabel(smu2_m9);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(530, 80, 59, 14));
        pushButton_5 = new QCAPushButton(smu2_m9);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(130, 120, 81, 22));
        label_48 = new QLabel(smu2_m9);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 340, 111, 16));
        pushButton_21 = new QCAPushButton(smu2_m9);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(160, 370, 151, 22));
        pushButton_20 = new QCAPushButton(smu2_m9);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(240, 460, 31, 31));
        label_53 = new QLabel(smu2_m9);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(30, 370, 121, 16));
        label_54 = new QLabel(smu2_m9);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(30, 300, 111, 16));
        pushButton_23 = new QCAPushButton(smu2_m9);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(160, 340, 61, 22));
        lcdNumber_13 = new QCALCDNumber(smu2_m9);
        lcdNumber_13->setObjectName(QStringLiteral("lcdNumber_13"));
        lcdNumber_13->setGeometry(QRect(130, 440, 64, 23));
        label_47 = new QCALabel(smu2_m9);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(190, 300, 101, 16));
        horizontalScrollBar_2 = new QScrollBar(smu2_m9);
        horizontalScrollBar_2->setObjectName(QStringLiteral("horizontalScrollBar_2"));
        horizontalScrollBar_2->setGeometry(QRect(80, 470, 151, 16));
        horizontalScrollBar_2->setOrientation(Qt::Horizontal);
        pushButton_19 = new QCAPushButton(smu2_m9);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(40, 460, 31, 31));
        pushButton_22 = new QCAPushButton(smu2_m9);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(250, 340, 61, 22));
        label_49 = new QLabel(smu2_m9);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(110, 420, 111, 16));
        label_51 = new QLabel(smu2_m9);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(30, 220, 121, 16));
        label_51->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        label_69 = new QLabel(smu2_m9);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(640, 540, 71, 16));
        label_59 = new QLabel(smu2_m9);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(640, 340, 71, 16));
        label_77 = new QLabel(smu2_m9);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(640, 620, 71, 16));
        label_84 = new QLabel(smu2_m9);
        label_84->setObjectName(QStringLiteral("label_84"));
        label_84->setGeometry(QRect(640, 600, 71, 16));
        pushButton_31 = new QCAPushButton(smu2_m9);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(590, 400, 31, 21));
        label_58 = new QLabel(smu2_m9);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(440, 380, 59, 14));
        pushButton_35 = new QCAPushButton(smu2_m9);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(510, 360, 31, 21));
        pushButton_35->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_44 = new QCAPushButton(smu2_m9);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(560, 540, 31, 21));
        label_66 = new QLabel(smu2_m9);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(640, 520, 71, 16));
        label_73 = new QLabel(smu2_m9);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(440, 320, 59, 14));
        label_65 = new QLabel(smu2_m9);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(440, 560, 59, 14));
        label_83 = new QLabel(smu2_m9);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(480, 220, 81, 16));
        label_83->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        pushButton_29 = new QCAPushButton(smu2_m9);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(590, 380, 31, 21));
        pushButton_54 = new QCAPushButton(smu2_m9);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(510, 400, 31, 21));
        pushButton_54->setStyleSheet(QStringLiteral(""));
        label_57 = new QLabel(smu2_m9);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(440, 400, 59, 14));
        pushButton_61 = new QCAPushButton(smu2_m9);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(510, 540, 31, 21));
        pushButton_61->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_63 = new QCAPushButton(smu2_m9);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(510, 580, 31, 21));
        pushButton_63->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_61 = new QLabel(smu2_m9);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(440, 480, 59, 14));
        pushButton_43 = new QCAPushButton(smu2_m9);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(590, 520, 31, 21));
        pushButton_45 = new QCAPushButton(smu2_m9);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(560, 380, 31, 21));
        pushButton_51 = new QCAPushButton(smu2_m9);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(590, 600, 31, 21));
        pushButton_34 = new QCAPushButton(smu2_m9);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(560, 440, 31, 21));
        label_63 = new QLabel(smu2_m9);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(640, 360, 71, 16));
        pushButton_40 = new QCAPushButton(smu2_m9);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(560, 500, 31, 21));
        label_79 = new QLabel(smu2_m9);
        label_79->setObjectName(QStringLiteral("label_79"));
        label_79->setGeometry(QRect(640, 580, 71, 16));
        pushButton_67 = new QCAPushButton(smu2_m9);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(560, 580, 31, 21));
        pushButton_41 = new QCAPushButton(smu2_m9);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(590, 500, 31, 21));
        pushButton_52 = new QCAPushButton(smu2_m9);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(560, 620, 31, 21));
        label_74 = new QLabel(smu2_m9);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(440, 440, 59, 14));
        label_82 = new QLabel(smu2_m9);
        label_82->setObjectName(QStringLiteral("label_82"));
        label_82->setGeometry(QRect(640, 420, 71, 16));
        pushButton_46 = new QCAPushButton(smu2_m9);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(560, 560, 31, 21));
        pushButton_26 = new QCAPushButton(smu2_m9);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(560, 360, 31, 21));
        pushButton_36 = new QCAPushButton(smu2_m9);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(560, 460, 31, 21));
        pushButton_30 = new QCAPushButton(smu2_m9);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(510, 380, 31, 21));
        pushButton_30->setStyleSheet(QStringLiteral(""));
        pushButton_64 = new QCAPushButton(smu2_m9);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(510, 600, 31, 21));
        pushButton_64->setStyleSheet(QStringLiteral(""));
        pushButton_48 = new QCAPushButton(smu2_m9);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(560, 420, 31, 21));
        label_76 = new QLabel(smu2_m9);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(440, 580, 59, 14));
        label_81 = new QLabel(smu2_m9);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(640, 480, 71, 16));
        pushButton_56 = new QCAPushButton(smu2_m9);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(590, 320, 31, 21));
        label_72 = new QLabel(smu2_m9);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(440, 520, 59, 14));
        pushButton_49 = new QCAPushButton(smu2_m9);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(590, 580, 31, 21));
        lcdNumber_15 = new QCALCDNumber(smu2_m9);
        lcdNumber_15->setObjectName(QStringLiteral("lcdNumber_15"));
        lcdNumber_15->setGeometry(QRect(560, 260, 64, 23));
        lcdNumber_15->setMode(QLCDNumber::Hex);
        label_71 = new QLabel(smu2_m9);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(640, 320, 71, 16));
        pushButton_32 = new QCAPushButton(smu2_m9);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(560, 400, 31, 21));
        pushButton_38 = new QCAPushButton(smu2_m9);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(590, 360, 31, 21));
        label_86 = new QLabel(smu2_m9);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(440, 420, 59, 14));
        label_67 = new QLabel(smu2_m9);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(440, 600, 59, 14));
        pushButton_71 = new QCAPushButton(smu2_m9);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(590, 340, 31, 21));
        pushButton_65 = new QCAPushButton(smu2_m9);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(510, 620, 31, 21));
        pushButton_65->setStyleSheet(QStringLiteral(""));
        pushButton_55 = new QCAPushButton(smu2_m9);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(510, 420, 31, 21));
        pushButton_55->setStyleSheet(QStringLiteral(""));
        pushButton_60 = new QCAPushButton(smu2_m9);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(510, 520, 31, 21));
        pushButton_60->setStyleSheet(QStringLiteral(""));
        pushButton_28 = new QCAPushButton(smu2_m9);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(510, 320, 31, 21));
        pushButton_68 = new QCAPushButton(smu2_m9);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(560, 480, 31, 21));
        pushButton_37 = new QCAPushButton(smu2_m9);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(590, 460, 31, 21));
        pushButton_39 = new QCAPushButton(smu2_m9);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(590, 480, 31, 21));
        pushButton_47 = new QCAPushButton(smu2_m9);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(590, 560, 31, 21));
        pushButton_58 = new QCAPushButton(smu2_m9);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(510, 480, 31, 21));
        pushButton_58->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_27 = new QCAPushButton(smu2_m9);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(560, 320, 31, 21));
        label_80 = new QLabel(smu2_m9);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(640, 380, 71, 16));
        label_68 = new QLabel(smu2_m9);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(440, 620, 59, 14));
        label_62 = new QLabel(smu2_m9);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(440, 500, 59, 14));
        pushButton_73 = new QCAPushButton(smu2_m9);
        pushButton_73->setObjectName(QStringLiteral("pushButton_73"));
        pushButton_73->setGeometry(QRect(510, 340, 31, 21));
        pushButton_73->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        label_55 = new QLabel(smu2_m9);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(640, 400, 71, 16));
        label_85 = new QLabel(smu2_m9);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(640, 460, 71, 16));
        label_78 = new QLabel(smu2_m9);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(440, 360, 59, 14));
        label_56 = new QLabel(smu2_m9);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(640, 440, 71, 16));
        pushButton_33 = new QCAPushButton(smu2_m9);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(590, 420, 31, 21));
        pushButton_62 = new QCAPushButton(smu2_m9);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(510, 560, 31, 21));
        pushButton_62->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        lcdNumber_14 = new QCALCDNumber(smu2_m9);
        lcdNumber_14->setObjectName(QStringLiteral("lcdNumber_14"));
        lcdNumber_14->setGeometry(QRect(480, 290, 64, 23));
        lcdNumber_14->setStyleSheet(QStringLiteral("color: rgb(0, 170, 127);"));
        lcdNumber_14->setMode(QLCDNumber::Hex);
        lcdNumber_14->setSegmentStyle(QLCDNumber::Filled);
        pushButton_72 = new QCAPushButton(smu2_m9);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(510, 440, 31, 21));
        pushButton_72->setStyleSheet(QStringLiteral(""));
        label_64 = new QLabel(smu2_m9);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(440, 540, 59, 14));
        lcdNumber_16 = new QCALCDNumber(smu2_m9);
        lcdNumber_16->setObjectName(QStringLiteral("lcdNumber_16"));
        lcdNumber_16->setGeometry(QRect(560, 290, 64, 23));
        lcdNumber_16->setStyleSheet(QStringLiteral(""));
        lcdNumber_16->setMode(QLCDNumber::Hex);
        label_60 = new QLabel(smu2_m9);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(440, 460, 59, 14));
        pushButton_50 = new QCAPushButton(smu2_m9);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(560, 600, 31, 21));
        pushButton_57 = new QCAPushButton(smu2_m9);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(590, 440, 31, 21));
        pushButton_70 = new QCAPushButton(smu2_m9);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(560, 340, 31, 21));
        label_75 = new QLabel(smu2_m9);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(640, 560, 71, 16));
        pushButton_59 = new QCAPushButton(smu2_m9);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(510, 500, 31, 21));
        pushButton_59->setStyleSheet(QStringLiteral("background-color: rgb(0, 170, 127);"));
        pushButton_42 = new QCAPushButton(smu2_m9);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(560, 520, 31, 21));
        pushButton_53 = new QCAPushButton(smu2_m9);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(590, 620, 31, 21));
        label_70 = new QLabel(smu2_m9);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(640, 500, 71, 16));
        pushButton_66 = new QCAPushButton(smu2_m9);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(590, 540, 31, 21));
        pushButton_69 = new QCAPushButton(smu2_m9);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(510, 460, 31, 21));
        pushButton_69->setStyleSheet(QStringLiteral(""));
        label_36 = new QLabel(smu2_m9);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(790, 500, 111, 16));
        label_37 = new QCALabel(smu2_m9);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(910, 500, 59, 14));
        speed9Axis = new QCAAxis(smu2_m9);
        speed9Axis->setObjectName(QStringLiteral("speed9Axis"));
        speed9Axis->setGeometry(QRect(790, 320, 345, 27));
        speed9Axis->setMinimumSize(QSize(100, 10));
        ref9Axis = new QCAAxis(smu2_m9);
        ref9Axis->setObjectName(QStringLiteral("ref9Axis"));
        ref9Axis->setGeometry(QRect(790, 290, 345, 27));
        ref9Axis->setMinimumSize(QSize(100, 10));
        acc9Axis = new QCAAxis(smu2_m9);
        acc9Axis->setObjectName(QStringLiteral("acc9Axis"));
        acc9Axis->setGeometry(QRect(790, 380, 345, 27));
        acc9Axis->setMinimumSize(QSize(100, 10));
        label_32 = new QLabel(smu2_m9);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(790, 420, 111, 16));
        sofn9Axis = new QCAAxis(smu2_m9);
        sofn9Axis->setObjectName(QStringLiteral("sofn9Axis"));
        sofn9Axis->setGeometry(QRect(790, 440, 345, 27));
        sofn9Axis->setMinimumSize(QSize(100, 10));
        max9Axis = new QCAAxis(smu2_m9);
        max9Axis->setObjectName(QStringLiteral("max9Axis"));
        max9Axis->setGeometry(QRect(790, 350, 345, 27));
        max9Axis->setMinimumSize(QSize(100, 10));
        pushButton_16 = new QCAPushButton(smu2_m9);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(1000, 500, 51, 22));
        label_33 = new QCALabel(smu2_m9);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(910, 420, 59, 14));
        curr9Axis = new QCAAxis(smu2_m9);
        curr9Axis->setObjectName(QStringLiteral("curr9Axis"));
        curr9Axis->setGeometry(QRect(790, 260, 345, 27));
        curr9Axis->setMinimumSize(QSize(100, 10));
        pushButton_12 = new QCAPushButton(smu2_m9);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(1000, 410, 51, 22));
        sofp9Axis = new QCAAxis(smu2_m9);
        sofp9Axis->setObjectName(QStringLiteral("sofp9Axis"));
        sofp9Axis->setGeometry(QRect(790, 470, 345, 27));
        sofp9Axis->setMinimumSize(QSize(100, 10));
        Axis9 = new QCAAxis(smu2_m9);
        Axis9->setObjectName(QStringLiteral("Axis9"));
        Axis9->setGeometry(QRect(30, 250, 360, 32));

        retranslateUi(smu2_m9);

        QMetaObject::connectSlotsByName(smu2_m9);
    } // setupUi

    void retranslateUi(QDialog *smu2_m9)
    {
        smu2_m9->setWindowTitle(QApplication::translate("smu2_m9", "Dialog", 0));
        label_39->setText(QApplication::translate("smu2_m9", "current position", 0));
        label_19->setText(QApplication::translate("smu2_m9", "nominal position", 0));
        label_18->setText(QApplication::translate("smu2_m9", "info set", 0));
        label_38->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_38->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdNomPosM9", 0)));
        label_43->setText(QApplication::translate("smu2_m9", "current speed", 0));
        label_25->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_25->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdCurSpeedM9", 0)));
        label_24->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_24->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdCaptValM9", 0)));
        label_42->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_42->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdBrakeDistM9", 0)));
        label_20->setText(QApplication::translate("smu2_m9", "capture value", 0));
        label_23->setText(QApplication::translate("smu2_m9", "M9", 0));
        label_41->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_41->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdPosM9", 0)));
        label_40->setText(QApplication::translate("smu2_m9", "brake distance", 0));
        label_26->setText(QApplication::translate("smu2_m9", "parameter set", 0));
        pushButton_13->setText(QApplication::translate("smu2_m9", "REF", 0));
        pushButton_13->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:HomeM9", 0)));
        pushButton_4->setText(QApplication::translate("smu2_m9", "STOP", 0));
        pushButton_4->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:StopM9", 0)));
        pushButton_6->setText(QApplication::translate("smu2_m9", "RUN", 0));
        pushButton_6->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:RunM9", 0)));
        label_44->setText(QApplication::translate("smu2_m9", "SMU41_2", 0));
        lcdNumber_11->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdPosM9", 0)));
        label_46->setText(QApplication::translate("smu2_m9", "DESC", 0));
        pushButton_18->setText(QApplication::translate("smu2_m9", "LSP", 0));
        pushButton_18->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:LspM9", 0)));
        pushButton_17->setText(QApplication::translate("smu2_m9", "Lock", 0));
        pushButton_17->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:LockM9", 0)));
        label_45->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_45->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:ChkAliveM9_.DESC", 0)));
        label_13->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_13->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdPosM9.EGU", 0)));
        pushButton_5->setText(QApplication::translate("smu2_m9", "LSN", 0));
        pushButton_5->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:LsnM9", 0)));
        label_48->setText(QApplication::translate("smu2_m9", "move continous", 0));
        pushButton_21->setText(QApplication::translate("smu2_m9", "GoRef", 0));
        pushButton_21->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:RefM9", 0)));
        pushButton_20->setText(QApplication::translate("smu2_m9", "+", 0));
        pushButton_20->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:ContPosM9", 0)));
        label_53->setText(QApplication::translate("smu2_m9", "move to reference", 0));
        label_54->setText(QApplication::translate("smu2_m9", "move absolute to", 0));
        pushButton_23->setText(QApplication::translate("smu2_m9", "-", 0));
        pushButton_23->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:ContNegM9", 0)));
        lcdNumber_13->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSpeedM9", 0)));
        label_47->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_47->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:AbsM9", 0)));
        pushButton_19->setText(QApplication::translate("smu2_m9", "-", 0));
        pushButton_19->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:ContNegM9", 0)));
        pushButton_22->setText(QApplication::translate("smu2_m9", "+", 0));
        pushButton_22->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:ContPosM9", 0)));
        label_49->setText(QApplication::translate("smu2_m9", "continous mode", 0));
        label_51->setText(QApplication::translate("smu2_m9", "motion commands", 0));
        label_69->setText(QString());
        label_59->setText(QApplication::translate("smu2_m9", "POSA", 0));
        label_77->setText(QApplication::translate("smu2_m9", "LSN", 0));
        label_84->setText(QApplication::translate("smu2_m9", "LSP", 0));
        pushButton_31->setText(QString());
        pushButton_31->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_58->setText(QApplication::translate("smu2_m9", "RUN", 0));
        pushButton_35->setText(QString());
        pushButton_35->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_44->setText(QString());
        pushButton_44->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_66->setText(QApplication::translate("smu2_m9", "Encoder", 0));
        label_73->setText(QApplication::translate("smu2_m9", "ERROR", 0));
        label_65->setText(QApplication::translate("smu2_m9", "LSP", 0));
        label_83->setText(QApplication::translate("smu2_m9", "error codes", 0));
        pushButton_29->setText(QString());
        pushButton_29->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_54->setText(QString());
        pushButton_54->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        label_57->setText(QApplication::translate("smu2_m9", "ABS", 0));
        pushButton_61->setText(QString());
        pushButton_61->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_63->setText(QString());
        pushButton_63->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        label_61->setText(QApplication::translate("smu2_m9", "70X I", 0));
        pushButton_43->setText(QString());
        pushButton_43->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_45->setText(QString());
        pushButton_45->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_51->setText(QString());
        pushButton_51->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_34->setText(QString());
        pushButton_34->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_63->setText(QApplication::translate("smu2_m9", "Ref Err", 0));
        pushButton_40->setText(QString());
        pushButton_40->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_79->setText(QApplication::translate("smu2_m9", "DV_ERR", 0));
        pushButton_67->setText(QString());
        pushButton_67->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_41->setText(QString());
        pushButton_41->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_52->setText(QString());
        pushButton_52->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_74->setText(QString());
        label_82->setText(QApplication::translate("smu2_m9", "EXT ERR", 0));
        pushButton_46->setText(QString());
        pushButton_46->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_26->setText(QString());
        pushButton_26->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_36->setText(QString());
        pushButton_36->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_30->setText(QString());
        pushButton_30->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_64->setText(QString());
        pushButton_64->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_48->setText(QString());
        pushButton_48->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_76->setText(QApplication::translate("smu2_m9", "REF", 0));
        label_81->setText(QString());
        pushButton_56->setText(QString());
        pushButton_56->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_72->setText(QApplication::translate("smu2_m9", "ABS", 0));
        pushButton_49->setText(QString());
        pushButton_49->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        lcdNumber_15->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        label_71->setText(QApplication::translate("smu2_m9", "User Stop", 0));
        pushButton_32->setText(QString());
        pushButton_32->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_38->setText(QString());
        pushButton_38->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_86->setText(QApplication::translate("smu2_m9", "OSPD", 0));
        label_67->setText(QApplication::translate("smu2_m9", "CAPT", 0));
        pushButton_71->setText(QString());
        pushButton_71->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_65->setText(QString());
        pushButton_65->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_55->setText(QString());
        pushButton_55->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_60->setText(QString());
        pushButton_60->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_28->setText(QString());
        pushButton_28->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_68->setText(QString());
        pushButton_68->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_37->setText(QString());
        pushButton_37->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_39->setText(QString());
        pushButton_39->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_47->setText(QString());
        pushButton_47->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_58->setText(QString());
        pushButton_58->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_27->setText(QString());
        pushButton_27->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_80->setText(QApplication::translate("smu2_m9", "Track Err", 0));
        label_68->setText(QApplication::translate("smu2_m9", "LOCK", 0));
        label_62->setText(QApplication::translate("smu2_m9", "DV_OK", 0));
        pushButton_73->setText(QString());
        pushButton_73->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        label_55->setText(QApplication::translate("smu2_m9", "SW Speed", 0));
        label_85->setText(QApplication::translate("smu2_m9", "SW LSN", 0));
        label_78->setText(QApplication::translate("smu2_m9", "DIR", 0));
        label_56->setText(QApplication::translate("smu2_m9", "SW LSP", 0));
        pushButton_33->setText(QString());
        pushButton_33->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_62->setText(QString());
        pushButton_62->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        lcdNumber_14->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_72->setText(QString());
        pushButton_72->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        label_64->setText(QApplication::translate("smu2_m9", "LSN", 0));
        lcdNumber_16->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_60->setText(QApplication::translate("smu2_m9", "SP", 0));
        pushButton_50->setText(QString());
        pushButton_50->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_57->setText(QString());
        pushButton_57->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_70->setText(QString());
        pushButton_70->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_75->setText(QApplication::translate("smu2_m9", "HW Speed", 0));
        pushButton_59->setText(QString());
        pushButton_59->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        pushButton_42->setText(QString());
        pushButton_42->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrStateM9", 0)));
        pushButton_53->setText(QString());
        pushButton_53->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        label_70->setText(QApplication::translate("smu2_m9", "Powerfail", 0));
        pushButton_66->setText(QString());
        pushButton_66->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdErrFlagM9", 0)));
        pushButton_69->setText(QString());
        pushButton_69->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdStateM9", 0)));
        label_36->setText(QApplication::translate("smu2_m9", "soft limit", 0));
        label_37->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_37->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSwLimM9", 0)));
        speed9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "speed", 0)));
        speed9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSpeedM9", 0)));
        speed9Axis->setProperty("units", QVariant(QString()));
        speed9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSpeedM9", 0)));
        ref9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "reference positic", 0)));
        ref9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdRefM9", 0)));
        ref9Axis->setProperty("units", QVariant(QString()));
        ref9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdRefM9", 0)));
        acc9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "acceleration time", 0)));
        acc9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdAccTimeM9", 0)));
        acc9Axis->setProperty("units", QVariant(QString()));
        acc9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdAccTimeM9", 0)));
        label_32->setText(QApplication::translate("smu2_m9", "ramp shape", 0));
        sofn9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "soft limit negativ", 0)));
        sofn9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSwLimNegM9", 0)));
        sofn9Axis->setProperty("units", QVariant(QString()));
        sofn9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSwLimNegM9", 0)));
        max9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "maximal speed", 0)));
        max9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdMaxSpeedM9", 0)));
        max9Axis->setProperty("units", QVariant(QString()));
        max9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdMaxSpeedM9", 0)));
        pushButton_16->setText(QApplication::translate("smu2_m9", "off", 0));
        pushButton_16->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:SwLimM9", 0)));
        label_33->setText(QApplication::translate("smu2_m9", "TextLabel", 0));
        label_33->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdAccM9", 0)));
        curr9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "current position", 0)));
        curr9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdPosM9", 0)));
        curr9Axis->setProperty("units", QVariant(QApplication::translate("smu2_m9", "steps", 0)));
        curr9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdPosM9", 0)));
        pushButton_12->setText(QApplication::translate("smu2_m9", "sin2", 0));
        pushButton_12->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:AccM9", 0)));
        sofp9Axis->setProperty("description", QVariant(QApplication::translate("smu2_m9", "soft limit positiv", 0)));
        sofp9Axis->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSwLimPosM9", 0)));
        sofp9Axis->setProperty("units", QVariant(QString()));
        sofp9Axis->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdSwLimPosM9", 0)));
        Axis9->setProperty("description", QVariant(QApplication::translate("smu2_m9", "move relative", 0)));
        Axis9->setProperty("pvReadback", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdRelM9", 0)));
        Axis9->setProperty("units", QVariant(QApplication::translate("smu2_m9", "steps", 0)));
        Axis9->setProperty("pv", QVariant(QApplication::translate("smu2_m9", "SMU41_2:rdRelM9", 0)));
    } // retranslateUi

};

namespace Ui {
    class smu2_m9: public Ui_smu2_m9 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SMU2_M9_H
